### ISSUE TITLE
Collabora integration stopped working after update due to change of hash in URL

### ISSUE THREAD

**Issue by d10r** [nextcloud/richdocuments#162] opened 2018-01-31 09:36 UTC
After updating to the latest `collabora/code` docker image, I couldn't open files associated to the Collabora App in Nextcloud anymore.
Trying to do so resulted in such error entries in the log of the docker container:
`wsd-00027-00035 08:56:07.362320 [ websrv_poll ] ERR  FileServerRequestHandler: File not found: Invalid URI request: [/loleaflet/277d2b8/loleaflet.html?WOPISrc=https%3A%2F%2Fsome.privatedomain.net%2Fapps%2Frichdocuments%2Fwopi%2Ffiles%2F15672_oczvq0b2cfu8&title=blog3.odt&lang=en&closebutton=1&revisionhistory=1].| wsd/FileServer.cpp:312`

Looking at `https://some.privatedomain.net/hosting/discovery`, I figured out that the hash in the URL (the part after `/loleaflet/`) had changed from `277d2b8` to something else. Searching for this string, I observed that the file `nextcloud/data/appdata_oczvq0b2cfu8/richdocuments/richdocuments/discovery.xml` still contained *old* URLs (with `277d2b8`). Deleting that file fixed the problem.

I don't know what this hash in the URL represents and when it changes. If more information is needed, let me know which.

**Config**:
Nextcloud 12.0.4 on Ubuntu 16.04
Collabora Code 3.0.0 (git hash: 81c8935) in Docker on Debian 8.10
Latest version of the Collabora Plugin (updated before updating the Docker image)

**Comment by pranavk** [comment] 2018-01-31 09:47
Hash is the git hash of Collabora Online you are using.

**Comment by thebearon** [comment] 2018-04-07 00:17
Actually, I just realized this and #115 are the same issues. Closing as duplicate.

**Closed by thebearon** 2018-04-07 00:17 UTC

**Comment by danger89** [comment] 2019-02-26 18:15
bear in mind #115 is very vague in my eye and thus ambiguous about what is/was the root cause. And what they tried to achieve fixing. Since there is no output log of Collabora Online/Libreoffice Online.
