### ISSUE TITLE
Readme file displayed over document in link share mode

### ISSUE THREAD

**Issue by drikqlis** [nextcloud/richdocuments#1428] opened 2021-03-12 09:34 UTC
**Describe the bug**
When accessing shared folder by link (not logged in user) when the folder has readme file and you open document in Collabora, readme file is displayed over the document.

**To Reproduce**
1. Share folder with readme file by link.
2. Open the link in private window.
3. Open any document in Collabora.
4. See error.

**Expected behavior**
Readme file should be below.

**Screenshots**
![obraz](https://user-images.githubusercontent.com/19647553/110920928-3c5e4280-831e-11eb-93e3-eed1f77bf4fb.png)
![obraz](https://user-images.githubusercontent.com/19647553/110920960-48e29b00-831e-11eb-936a-be743291614c.png)

**Client details:**
 - OS: Windows
 - Browser Chrome, Firefox

## Server details

**Operating system**:
Ubuntu 18.04 LTS
**Web server:**
Apache
**Database:**
MariaDB
**PHP version:**
7.3
**Nextcloud version:**
20.0.8
**Version of the richdocuments app**
3.7.17

**Comment by juliushaertl** [comment] 2021-04-09 06:26
Cannot reproduce this with 20.0.8 and the latest collabora release. Since you seem to be using a custom theme could you check if that might be causing this?

**Comment by juliushaertl** [comment] 2021-04-09 06:27
Oh nevermind, now i can also see that happening.

**Comment by steffen-moser** [comment] 2021-06-21 10:13
I can confirm that this problem still exists in Nextcloud 20.0.10 and Collabora 6.4.9.

**Comment by joshtrichards** [comment] 2023-11-07 15:05
I can't reproduce this today. Can anyone of you on this thread still do so?

**Comment by juliushaertl** [comment] 2023-11-07 16:53
Right, we fixed this quite some time ago.

Let me close this.

Thanks @joshtrichards for all the hard triaging work not only here but across repos. It is very much appreciated 💙

**Closed by juliushaertl** 2023-11-07 16:53 UTC
Labels: bug, 1. to develop
