### ISSUE TITLE
Allow use of local time isntead of UTC in spreadsheets

### ISSUE THREAD

**Issue by grj1978** [nextcloud/richdocuments#3646] opened 2024-05-01 20:37 UTC
**Is your feature request related to a problem? Please describe.**
It could be considered a problem. Spreadsheets reference UTC (or maybe its RTC) time instead local time. I can't see anywhere in the app options to set which time to use.

Nextcloud Hub 8 29.0.0 (docker)

-installed though app interface
Collabora Online - Built-in CODE Server Version 24.4.103
Nextcloud Office Version 8.4.0

**Describe the solution you'd like**

Please provide a way to set which time source is used for spreadsheets. 

**Describe alternatives you've considered**

Modifying spreadsheet logic, but this doesn't work when the desktop application uses local time.

**Additional context**

**Comment by juliushaertl** [comment] 2024-05-07 07:11
This is an upstream issue in Collabora Online. I'd close this as a duplicate of https://github.com/CollaboraOnline/online/issues/3733 (while the initial report is about writer, it also mentions that this is a general issue with any time reference)

**Closed by juliushaertl** 2024-05-07 07:11 UTC
