### ISSUE TITLE
Better logging if reverse proxy is misconfigured

### ISSUE THREAD

**Issue by maurerle** [nextcloud/richdocuments#981] opened 2020-05-23 20:26 UTC
**Is your feature request related to a problem? Please describe.**
Since 3.6 the capabilities endpoint is needed which was a breaking change for a lot of Nextcloud configurations.
The problem I have with this is, that this has not been mentioned in the release notes. Neither through the Nextcloud Appstore RSS-Feed nor the github releases page or RSS-Feed.
Which makes it nearly impossible to not break your instance when upgrading to 3.6. And the error message does not help a lot.

**Describe the solution you'd like**
While there is already an issue for making the capabilities check optional to not break existing instances, another approach would be to enhance the logging if the instance is misconfigured.
Currently it only says "the server is not configured" when opening a file but the check from the configuration in nextcloud succeeds.
The capabilities route should be checked there too and give a more precise message so that people can fix their instance without digging github issues.
Maybe there are more things which can be logged (misconfigured websockets or so)

**Describe alternatives you've considered**

**Additional context**
There are probably a lot of configurations (probably the ones existing longer than a year or relying on https://icewind.nl/entry/collabora-online/ when set up) which would break because some example configurations did not include this.
Please communicate breaking changes a little more verbose in the future! 😃 

@icewind1991 please add a note to the begging of your post, so that future visitors will not run into this issue.

**Comment by juliushaertl** [comment] 2020-05-26 16:14
Duplicate of https://github.com/nextcloud/richdocuments/issues/949

**Closed by juliushaertl** 2020-05-26 16:14 UTC
