### ISSUE TITLE
Dont work after installation

### ISSUE THREAD

**Issue by marcmanusch** [nextcloud/richdocuments#163] opened 2018-02-01 22:24 UTC
### Steps to reproduce
1. Install
2. create or open a document
3. ERROR

### Expected behaviour
Open the document

### Actual behaviour
ERROR

### Version
Nextcloud 12.0.5

### LOG

GuzzleHttp\Exception\RequestException: cURL error 3: <url> malformed
	0	/var/www/vhosts/XYZ.de/cloud.XYZ.de/3rdparty/guzzlehttp/guzzle/src/RequestFsm.php - line 103: GuzzleHttp\Exception\RequestException wrapException(Object(GuzzleHttp\Message\Request), Object(GuzzleHttp\Ring\Exception\RingException))
	1	/var/www/vhosts/XYZ.de/cloud.XYZ.de/3rdparty/guzzlehttp/guzzle/src/RequestFsm.php - line 132: GuzzleHttp\RequestFsm->__invoke(Object(GuzzleHttp\Transaction))
	2	/var/www/vhosts/XYZ.de/cloud.XYZ.de/3rdparty/react/promise/src/FulfilledPromise.php - line 25: GuzzleHttp\RequestFsm->GuzzleHttp\{closure}(*** sensitive parameters replaced ***)
	3	/var/www/vhosts/XYZ.de/cloud.XYZ.de/3rdparty/guzzlehttp/ringphp/src/Future/CompletedFutureValue.php - line 55: React\Promise\FulfilledPromise->then(Object(Closure), NULL, NULL)
	4	/var/www/vhosts/XYZ.de/cloud.XYZ.de/3rdparty/guzzlehttp/guzzle/src/Message/FutureResponse.php - line 43: GuzzleHttp\Ring\Future\CompletedFutureValue->then(Object(Closure), NULL, NULL)
	5	/var/www/vhosts/XYZ.de/cloud.XYZ.de/3rdparty/guzzlehttp/guzzle/src/RequestFsm.php - line 134: GuzzleHttp\Message\FutureResponse proxy(Object(GuzzleHttp\Ring\Future\CompletedFutureArray), Object(Closure))
	6	/var/www/vhosts/XYZ.de/cloud.XYZ.de/3rdparty/guzzlehttp/guzzle/src/Client.php - line 165: GuzzleHttp\RequestFsm->__invoke(Object(GuzzleHttp\Transaction))
	7	/var/www/vhosts/XYZ.de/cloud.XYZ.de/3rdparty/guzzlehttp/guzzle/src/Client.php - line 125: GuzzleHttp\Client->send(Object(GuzzleHttp\Message\Request))
	8	/var/www/vhosts/XYZ.de/cloud.XYZ.de/lib/private/Http/Client/Client.php - line 138: GuzzleHttp\Client->get('/hosting/discov...', Array)
	9	/var/www/vhosts/XYZ.de/cloud.XYZ.de/apps/richdocuments/lib/WOPI/DiscoveryManager.php - line 84: OC\Http\Client\Client->get('/hosting/discov...')
	10	/var/www/vhosts/XYZ.de/cloud.XYZ.de/apps/richdocuments/lib/WOPI/Parser.php - line 41: OCA\Richdocuments\WOPI\DiscoveryManager->get()
	11	/var/www/vhosts/XYZ.de/cloud.XYZ.de/apps/richdocuments/lib/TokenManager.php - line 122: OCA\Richdocuments\WOPI\Parser->getUrlSrc('application/vnd...')
	12	/var/www/vhosts/XYZ.de/cloud.XYZ.de/apps/richdocuments/lib/Controller/DocumentController.php - line 168: OCA\Richdocuments\TokenManager->getToken(*** sensitive parameters replaced ***)
	13	[internal function] OCA\Richdocuments\Controller\DocumentController->index('21943')
	14	/var/www/vhosts/XYZ.de/cloud.XYZ.de/lib/private/AppFramework/Http/Dispatcher.php - line 160: call_user_func_array(Array, Array)
	15	/var/www/vhosts/XYZ.de/cloud.XYZ.de/lib/private/AppFramework/Http/Dispatcher.php - line 90: OC\AppFramework\Http\Dispatcher->executeController(Object(OCA\Richdocuments\Controller\DocumentController), 'index')
	16	/var/www/vhosts/XYZ.de/cloud.XYZ.de/lib/private/AppFramework/App.php - line 114: OC\AppFramework\Http\Dispatcher->dispatch(Object(OCA\Richdocuments\Controller\DocumentController), 'index')
	17	/var/www/vhosts/XYZ.de/cloud.XYZ.de/lib/private/AppFramework/Routing/RouteActionHandler.php - line 47: OC\AppFramework\App main('OCA\\Richdocumen...', 'index', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)
	18	[internal function] OC\AppFramework\Routing\RouteActionHandler->__invoke(Array)
	19	/var/www/vhosts/XYZ.de/cloud.XYZ.de/lib/private/Route/Router.php - line 299: call_user_func(Object(OC\AppFramework\Routing\RouteActionHandler), Array)
	20	/var/www/vhosts/XYZ.de/cloud.XYZ.de/lib/base.php - line 1004: OC\Route\Router->match('/apps/richdocum...')
	21	/var/www/vhosts/XYZ.de/cloud.XYZ.de/index.php - line 48: OC handleRequest()
	22	{main}

**Comment by thebearon** [comment] 2018-02-05 20:32
Dupe of #58.

**Closed by thebearon** 2018-02-05 20:32 UTC
