### ISSUE TITLE
Failing in opening the file from the left side-bar

### ISSUE THREAD

**Issue by pmarini-nc** [nextcloud/richdocuments#1696] opened 2021-08-02 16:15 UTC
**Describe the bug**

In a Nextcloud server with Collabora CODE as Office Collaboration Suite backend, opening the file from the left side-bar fails.

**To Reproduce**
1. Click on the three dotted menu of a spreadsheet file, then Details
2. Click on the white area above the Details menu (upper-right corner)
3. The file should be opened in Collabora, but it isn't. Error: `Failed to load Collabora Online Development Edition - please try again later`

**Expected behavior**

The file should be opened in Collabora.

**Screenshots**
![Peek 2021-08-02 18-03](https://user-images.githubusercontent.com/85954408/127891612-5dbca623-94b2-40cb-8e5b-857acdcceae1.gif)

## Server details
[system-report.md](https://github.com/nextcloud/richdocuments/files/6918190/system-report.md)

**Comment by juliushaertl** [comment] 2021-08-02 16:22
Extracting the file id for the richdocuments url that is being opened seems to fail as the url contains `{fileId}`

**Comment by joshtrichards** [comment] 2023-11-15 23:16
I can't reproduce this behavior today. I can't find the relevant PR, but pretty certain it's fixed as checked across a couple environments - both NC26 and NC27 based. Feel free to follow-up if still experiencing this, but closing on that basis.

**Closed by joshtrichards** 2023-11-15 23:16 UTC
Labels: bug, 1. to develop
