### ISSUE TITLE
App disabled after upgrade on PHP7.0

### ISSUE THREAD

**Issue by ralcazar-oeg** [nextcloud/richdocuments#594] opened 2019-09-04 16:41 UTC
**Describe the bug**
After upgrade to collabora 3.4.0 collabora is disabled. If I click enable nothing happens, and log show error:
"TypeError: Return value of OCA\Richdocuments\AppInfo\Application::updateCSP() must be an instance of OCA\Richdocuments\AppInfo\void, none returned"

Other nextcloud instance use the same collabora server and is working like a charm, so error follows to upgrade v3.4.0 in this test instance.

Each time I go to apps collabora is disabled and I can enabled it, but it does nothing

**Client details:**
Tested in multiple clients and browsers

## Server details

**Operating system**: Ubuntu 16.04

**Web server: Apache 2.4

**Database: mysql

**PHP version: 7.0.33

**Nextcloud version: 15.0.11

**Version of the richdocuments app**

**Version of Collabora Online**

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
[no app in context] Error: TypeError: Return value of OCA\Richdocuments\AppInfo\Application::updateCSP() must be an instance of OCA\Richdocuments\AppInfo\void, none returned at <<closure>>

0. /var/www/alcazar/apps/richdocuments/appinfo/app.php line 66
   updateCSP("*** sensitive parameters replaced ***")
1. /var/www/alcazar/lib/private/legacy/app.php line 261
   require_once("/var/www/alcaza ... p")
2. /var/www/alcazar/lib/private/legacy/app.php line 154
   requireAppFile(OCA\Richdocuments\AppInfo\Application {})
3. /var/www/alcazar/lib/private/legacy/app.php line 127
   loadApp("richdocuments")
4. /var/www/alcazar/apps/dav/appinfo/app.php line 30
   loadApps(["dav"])
5. /var/www/alcazar/lib/private/legacy/app.php line 261
   require_once("/var/www/alcaza ... p")
6. /var/www/alcazar/lib/private/legacy/app.php line 154
   requireAppFile("dav")
7. /var/www/alcazar/lib/private/legacy/app.php line 127
   loadApp("dav")
8. /var/www/alcazar/lib/base.php line 972
   loadApps()
9. /var/www/alcazar/index.php line 42
   handleRequest()

GET /alcazar/index.php/apps/files
from ******* by ralcazar at 2019-09-04T16:23:47+00:00
#### Browser log
```

</details>

Maybe this issue is related to this
https://github.com/nextcloud/richdocuments/pull/593

**Comment by juliushaertl** [comment] 2019-09-04 16:45
The issue is that a syntax used now is not suppported with PHP7.0. This should have been catched by our CI, but seems it didn't https://drone.nextcloud.com/nextcloud/richdocuments/108/2/2 I'll look into that

**Comment by dragonchaser** [comment] 2019-09-05 14:52
Having the same issue here, hope it can be fixed soon :)

**Comment by fasterit** [comment] 2019-09-05 15:50
Commit https://github.com/nextcloud/richdocuments/pull/598/commits/cfb9b3a2e430e73804e3bbfd1d46d5d1c8c589bc has the one-line fix you need.

**Comment by florealcab** [comment] 2019-09-05 19:12
I have a similar issue: unable to enable the app (click show app enable, but if I refresh the page it is disabled back).

But in logs I have another error: ￼OCP\AppFramework\QueryException: Could not resolve OCA\Federation\TrustedServers! Class OCA\Federation\TrustedServers does not exist

The fix proposed by @fasterit does not resolve anything for me... It's quite annoying

**Comment by florealcab** [comment] 2019-09-05 19:14
And I have php7.2, so it's not the cause proposed by @juliushaertl for me. I can't say if it's from the 3.4 version precisely but I can say it's quite recent.

I have the latest nextcloud 16 version (16.0.4)

**Comment by juliushaertl** [comment] 2019-09-06 08:30
@florealcab https://github.com/nextcloud/richdocuments/pull/593 should to the trick I'll push out a new release once the other patch is reviewed.

**Comment by pitchum** [comment] 2019-09-06 09:07
Applying the following patch seems to solve the issue for me:
```
--- apps/richdocuments/lib/AppInfo/Application.php
+++ apps/richdocuments/lib/AppInfo/Application.php
@@ -85,7 +85,7 @@
 
        }
 
-       public function updateCSP(): void {
+       public function updateCSP() {
                $container = $this->getContainer();
 
                $publicWopiUrl = $container->getServer()->getConfig()->getAppValue('richdocuments', 'public_wopi_url', '');
```

Can someone confirm that it's safe to apply this workaround on production server?

**Comment by pitchum** [comment] 2019-09-06 09:45
@juliushaertl actually the proper fix is in #598

**Comment by juliushaertl** [comment] 2019-09-06 11:16
For this issue, yes, for the one @florealcab mentioned it is #593

**Closed** 2019-09-06 16:22 UTC
Labels: bug

**Comment by florealcab** [comment] 2019-09-08 15:53
Thank you, enabling Federation app did the trick for me (still work with 3.4.1 version, but I did it in 3.4.0 version first)
