### ISSUE TITLE
OpenDocument Icons in Activity Stream Broken if Richdocuments App Is Active

### ISSUE THREAD

**Issue by gohrner** [nextcloud/richdocuments#421] opened 2019-02-28 11:26 UTC
**Describe the bug**
If the Richdocuments app (Collabora App) as installed and active, the Activity Stream contains broken file icons for all OpenDocument files.

**To Reproduce**
1. Install and configure the Richdocuments App (Collabora App)
2. Open an office document (ODS or ODT)
3. Open Activity Stream

**Expected behavior**
The entries refering to the office document should show a document icon or document preview.

**Actual behavior**
The entries refering to the office document show an "broken image" icon.

As soon as I disable the Richdocuments app, the icons work again.

**Screenshots**
See screenshot. Not that the icons for non-existing office files (the deleted file in the screenshot) still work even with activated Richdocuments app.

![image](https://user-images.githubusercontent.com/26199042/53563189-8d45d880-3b53-11e9-8eea-4616c7ebd3f0.png)

## Server details

**PHP version:** 7.0.33

**Nextcloud version:** 14.0.7

**Version of the richdocuments app** 3.2.1

**Version of Collabora Online** 4.0 final

**Comment by juliushaertl** [comment] 2019-02-28 12:41
Do you have installed Nextcloud in a subdirectory? In that case it might be fixes with the next release in https://github.com/nextcloud/richdocuments/pull/405

**Comment by gohrner** [comment] 2019-02-28 12:45
My Nextcloud-URL ist https://nextcloud.example.org/ (if that's the question). So, probably, the answer is "no".

If I click "open image in new tab" in the "broken image icon", I get a window containg the text "[]".

**Comment by juliushaertl** [comment] 2019-02-28 13:13
@gohrner I assume the image url is for the preview endpoint?

In that case can you post the output of https://your-collabora-domain/hosting/capabilities ?

**Comment by juliushaertl** [comment] 2019-02-28 13:14
I guess we need to properly fallback to mimetype icons here if the previews are not available.

**Comment by gohrner** [comment] 2019-02-28 14:05
> @gohrner I assume the image url is for the preview endpoint?

`https://nextcloud.example.org/core/preview.png?file=/filepath/file.ods&c=00deadbeef&x=150&y=150`

> In that case can you post the output of https://your-collabora-domain/hosting/capabilities ?

`{"convert-to":{"available":false},"hasMobileSupport":true,"hasTemplateSaveAs":true}`

**Comment by juliushaertl** [comment] 2019-02-28 16:14
Ah I could reproduce, I'll look into it.

**Comment by Hell-o-Admin** [comment] 2019-03-03 18:16
Hey guys, in my opinion, this missing icon error in a follow up to this:

Duplicate of #427 

@gohrner please check if you have this error in your nextcloud logs:
`TypeError: Argument 2 passed to GuzzleHttp\Psr7\MultipartStream::addElement() must be of the type array, string given, called in /var/www/html/3rdparty/guzzlehttp/psr7/src/MultipartStream.php on line 70`

My guess is, that when the preview creation fails, the files app falls back to the default icon of the file type, but the activity app doesn´t have that error handling, so the browser show a missing image.

so i would say, the failing preview generation causes this and maybe activity could be handling the error better.

let me know if you need more info. as stated in #427, you will find some more details here: [https://help.nextcloud.com/t/collabora-error-on-nextcloud-15-0-5/48668](url)

**Comment by gohrner** [comment] 2019-03-04 06:05
No, I have no error related to `MultipartStream`:

'''
$ egrep MultipartStream nextcloud.log 
$
'''

**Comment by Hell-o-Admin** [comment] 2019-03-04 10:33
> 
> 
> No, I have no error related to `MultipartStream`:
> 
> ```
> $ egrep MultipartStream nextcloud.log 
> $
> ```

Thats is odd. Are your sure, that your log level of nextcloud is at least 2?

**Comment by gohrner** [comment] 2019-03-04 17:27
I do have loglevel 2: `'loglevel' => 2,`

Disabling previews altogether removes the "broken image" icons (not surprisingly).

Does this setting have any other effect, i.e. where else may I lose previews?

I noticed that the document sidebar never displays previews for office documents, only the document icon images, so there's no difference.

So if the only effect of `'enable_previews' => false,` is that it fixes the Activity Stream, this setting should probably be default...

**Comment by Hell-o-Admin** [comment] 2019-03-04 17:34
Ok, 3.2.3 fixed the TypeError (@juliushaertl thank you!), but not the missing icon in activity stream or the preview generation of those documents. I´m wondering, how i could find out, why the preview generation is failing in my case.

**Comment by gohrner** [comment] 2019-03-04 17:35
In my case it may be related to a problem on the Collabora side, but I need to investigate this - I'm using the CODE docker container which only listens on the localhost IPv4 address, and any Apache reverse proxy forwarding to this address. So IPv6 should not be involved...

```
wsd-00030-00040 2019-03-04 17:28:52.610993 [ websrv_poll ] ERR  Requesting address is denied: ::ffff:172.17.0.1| wsd/LOOLWSD.cpp:1971
```

**Comment by Hell-o-Admin** [comment] 2019-03-05 11:06
@gohrner I´ve been looking into this error.
- Finally managed to disable IPv6 easily in the loolwsd.xml by adding this ` -e "extra_params=--o:net.proto=IPv4"` to the my docker run line - but that just removes the `::ffff` from the error
- Also found out, that the IP 172.17.0.1 belongs to the docker IP bridge configuration, which is shown by 'docker network inspect bridge' - while 172.17.0.2 is the IP of the container.

I´ll try to add the bridge IP to allowed hosts in loolwsd. Mayb fixes previesws and the activity bug aswell.

**Comment by Hell-o-Admin** [comment] 2019-03-08 10:19
Little Update:

It would definitly help, if you check the capabilities before you post a preview request.

When i host the docker Container on localhost / 127.0.0.1 and use nginx as a reverse proxy on my local lan adress (192.168.x.x) the hosting/capabilities show:
`{"convert-to":{"available":false},"hasMobileSupport":true,"hasTemplateSaveAs":true}`
The preview request is denied, because the post_allow restriction in the loolwsd.xml of the docker image, which doesn´t allow the bridge gateway address.
If i start the docker image to listen on my local lan (192.168.x.x:9980:9980) and still use nginx to reverse proxy with differnt ssl certs from port 443 to 9988 i dont use the brigde and the hosting/capabilities switch to:
`{"convert-to":{"available":true},"hasMobileSupport":true,"hasTemplateSaveAs":true}`

So i would agree to #439 be solving the issue in activity and the docker error. The problem with the post_allow is to be solved in the collabora CODE image.

**Closed** 2019-03-08 10:39 UTC
Labels: 1. to develop, bug

**Comment by gohrner** [comment] 2019-03-13 18:59
> So if the only effect of `'enable_previews' => false,` is that it fixes the Activity Stream, this setting should probably be default...

Ok, that's not the only change - with "enable_previews" false the whole gallery feature does not work any more at all, so that's also no option...

**Comment by gohrner** [comment] 2019-03-13 19:00
> The problem with the post_allow is to be solved in the collabora CODE image.

Did you open an issue in the LibreOffice Online bugtracker for that?

**Comment by Hell-o-Admin** [comment] 2019-03-14 09:59
@gohrner 
I didn´t open a ticket because I managed to add the bridge IP to the post allowed hosts. For my setup it required these additional params to the docker run command:
`-e extra_params='--o:net.proto=IPv4 --o:net.post_allow.host[4]=172.17.0.1'`
You might have to change the IP according to your docker brigde IP (as seen in the error) and the number in brakets [4] has to point to an existing entry in your loolwsd.xml (starting with 0), which you want to override. Since im not using IPv6, i choose the last IPv6 entry for localhost (::1).
