### ISSUE TITLE
Back Button is missing on iPad

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/richdocuments#2398] opened 2022-08-23 05:35 UTC
IPadOS 15.6
Nextcloud Office: 6.2.0

Generally it's working in the Browser and on smartphones. 
![grafik](https://user-images.githubusercontent.com/24530680/186077855-c586c74d-60bc-4222-8198-be63febfd0bc.png)

**Comment by PheaNotYou** [comment] 2022-08-31 08:54
We have the same problem…and it’s even more frustrating for our technologically-less-gifted employees.
So far, opening Collabora-charts and documents in the iOS app is a trap.
Desktop Nextcloud Collabora Online version is running smooth, but on the (different) iPads - all iOS 15.6.1 - there’s the missing “back-button” when viewing/modifying charts and documents.
There seems to be an invisible button (where there should be a real one - left upper screen corner) but only for a few seconds/actions, then it vanishes.

**Comment by thebearon** [comment] 2022-09-06 11:14
There was never a back button in the Nextcloud iOS app, but indeed there should be a close (X) on the right side of the menu bar that's missing currently.

**Comment by juliushaertl** [comment] 2022-09-21 19:03
Should be fixed by #2451

**Closed by juliushaertl** 2022-09-21 19:03 UTC

**Comment by Giusemx** [comment] 2022-11-22 21:10
I didn't understand, if this bug will be fixed or not. I try to simulate the issue von firefox browser with more mobile views, like iPad Air, Pro etc. And the issue is not there. But on the iPad Pro and on and android Tablet, the issue is there. No Possibility to leave the documents when start editing it. So, i didn't understand if the issue will be fixed, or is supposed that the issue is not there, because of simulating the tablets the issue is not there...
