### ISSUE TITLE
Opening a federated shared document not working

### ISSUE THREAD

**Issue by lachmanfrantisek** [nextcloud/richdocuments#15] opened 2017-01-13 13:38 UTC
### Steps to reproduce
1. Install two *nextcloud* servers.
2. Run two [collabora/code](https://hub.docker.com/r/collabora/code/) servers via docker. (tested with `2.0.1`+`2.0.1` and `2.0.1`+`1.9.8`)
3. Setup [collabora app](https://apps.nextcloud.com/apps/richdocuments) (`1.1.25`) on both servers.
4. Create document in one server.
5. Share document via federated sharing with user from second server.
5. Open document in the second server.

### Expected behaviour
Open document.

> Probably by the first *code server* to allow collaboration. And if there is not any *code server* running, then in the second one. Or at least by the second *code server* without collaboration.

### Actual behaviour
Internal server error.

### Server configuration
**Operating system**: Ubuntu Server 16.04

**Web server:**  nginx

**Database:** pgsql  9.6.0

**PHP version:** 7.0.14

**Nextcloud version:** 11.0.1 (daily) + 11.0.0 (stable)

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh docker images (updated via new image from nextcloud 10)

**Where did you install Nextcloud from:**  [wonderfall/nextcloud:latest](https://hub.docker.com/r/wonderfall/nextcloud/) and [wonderfall/nextcloud:daily](https://hub.docker.com/r/wonderfall/nextcloud/) 

**List of activated apps:**
<details>
<summary>App list</summary>
Activity, Collaborative tags, Comments, Deteted files, Extenral storage support, Federation, File sharing, First run wizard, Gallery, Log Reader, Mail template editor, Nextcloud announcements, Notifications, Password policy, PDF viewer, Server info, Share by mail, Text editor, Theming Update notification, Usage survey, Versions, Video player, Announcement Center, AppOrder, Audio Player, Bookmakrks, Calendar, Collabora Online (1.1.25), Contacts, Direct Menu, Markdown Editor, News, Nextcloud SMS, Notes, OwnBackup, QOwnNotesAPI, Reader (ebook reader), Tasks, Two Factor TOTP PRovider, Two Factor U2F
</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>

```
<?php
$CONFIG = array (
  'datadirectory' => '/data',
  'apps_paths' => 
  array (
    0 => 
    array (
      'path' => '/nextcloud/apps',
      'url' => '/apps',
      'writable' => false,
    ),
    1 => 
    array (
      'path' => '/apps2',
      'url' => '/apps2',
      'writable' => true,
    ),
  ),
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'redis' => 
  array (
    'host' => '/tmp/redis.sock',
    'port' => 0,
    'timeout' => 0.0,
  ),
  'instanceid' => '123456',
  'passwordsalt' => '123456',
  'secret' => '123456',
  'trusted_domains' => 
  array (
    0 => 'nc1.com',
    1 => 'nc2.com',
  ),
  'overwrite.cli.url' => 'https://nc1.com',
  'dbtype' => 'pgsql',
  'version' => '11.0.1.0',
  'dbname' => 'nextcloud',
  'dbhost' => 'nc-postgres',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'mail_from_address' => 'nc',
  'logtimezone' => 'Europe/Prague',
  'logdateformat' => 'Y-m-d H:i:s',
  'dbuser' => 'dbuser',
  'dbpassword' => '123456',
  'installed' => true,
  'updater.release.channel' => 'daily',
  'maintenance' => false,
  'mail_domain' => 'smtpdomain',
  'mail_smtpmode' => 'smtp',
  'appstore.experimental.enabled' => true,
  'appstoreenabled' => true,
  'appstoreurl' => 'https://apps.nextcloud.com/api/v0',
  'mail_smtpsecure' => 'ssl',
  'mail_smtphost' => 'smtphost',
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtpauth' => 1,
  'mail_smtpport' => '465',
  'mail_smtpname' => 'nextcloud',
  'mail_smtppassword' => '123456',
  'loglevel' => 0,
);
```
```
<?php
$CONFIG = array (
  'datadirectory' => '/data',
  'apps_paths' => 
  array (
    0 => 
    array (
      'path' => '/nextcloud/apps',
      'url' => '/apps',
      'writable' => false,
    ),
    1 => 
    array (
      'path' => '/apps2',
      'url' => '/apps2',
      'writable' => true,
    ),
  ),
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'redis' => 
  array (
    'host' => '/tmp/redis.sock',
    'port' => 0,
    'timeout' => 0.0,
  ),
  'instanceid' => '123465',
  'passwordsalt' => '123456',
  'secret' => '123456',
  'trusted_domains' => 
  array (
    0 => 'nc3.com',
  ),
  'overwrite.cli.url' => 'https://nc3.com',
  'dbtype' => 'pgsql',
  'version' => '11.0.0.10',
  'dbname' => 'nextcloud',
  'dbhost' => 'nextcloud-postgres',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'mail_from_address' => 'nc',
  'logtimezone' => 'UTC',
  'logdateformat' => 'Y-m-d H:i:s',
  'dbuser' => 'dbuser',
  'dbpassword' => '12346',
  'installed' => true,
  'maintenance' => false,
  'mail_domain' => 'smtpdomain',
  'mail_smtpmode' => 'smtp',
  'appstore.experimental.enabled' => true,
  'mail_smtphost' => 'smtphost',
  'mail_smtpport' => '465',
  'mail_smtpauth' => 1,
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtpsecure' => 'ssl',
  'mail_smtpname' => 'nextcloud',
  'mail_smtppassword' => '123465',
  'loglevel' => 1,
);

```

</details>

**Are you using external storage, if yes which one:** dropbox, google-drive, sftp

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:**

- Firefox Nightly 53.0a1 (2016-11-25) (64-bit)
- Firefox 50.1.0
- Chromium 55.0.2883.87

**Operating system:** Linux Mint 18.7 64bit

#### Nextcloud log (data/nextcloud.log)

<details>
<summary>Nextcloud log</summary>

```

```

```
Error: Call to a member function getUID() on null

    /apps2/richdocuments/lib/Controller/DocumentController.php - line 103: OCA\Richdocuments\TokenManager->getToken(*** sensitive parameters replaced ***)
    [internal function] OCA\Richdocuments\Controller\DocumentController->index('536_/')
    /nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 160: call_user_func_array(Array, Array)
    /nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 90: OC\AppFramework\Http\Dispatcher->executeController(Object(OCA\Richdocuments\Controller\DocumentController), 'index')
    /nextcloud/lib/private/AppFramework/App.php - line 114: OC\AppFramework\Http\Dispatcher->dispatch(Object(OCA\Richdocuments\Controller\DocumentController), 'index')
    /nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php - line 47: OC\AppFramework\App main('OCA\\Richdocumen...', 'index', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)
    [internal function] OC\AppFramework\Routing\RouteActionHandler->__invoke(Array)
    /nextcloud/lib/private/Route/Router.php - line 299: call_user_func(Object(OC\AppFramework\Routing\RouteActionHandler), Array)
    /nextcloud/lib/base.php - line 1010: OC\Route\Router->match('/apps/richdocum...')
    /nextcloud/index.php - line 40: OC handleRequest()
    {main}
```
</details>

&nbsp;

> There can be some mismatch in my setup but it would be nice to make it work.
> Thank you for such a great app.

**Comment by tcitworld** [comment] 2017-08-07 21:39
Can reproduce this.

**Comment by TheBrones** [comment] 2017-11-14 15:32
I'm also dealing with this. I have 2 Nextcloud servers and one Collabora server but I get a error.

**Comment by Pesticles** [comment] 2018-03-27 00:42
Still a problem with 13.0.1
Perhaps we can change the behaviour of federated file to download instead of attempting to open in collabora, until this is fixed properly?

**Comment by MorrisJobke** [comment] 2018-04-03 10:25
cc @schiessle

**Comment by schiessle** [comment] 2018-04-04 15:46
I assume that this is a general problem with all external storage. Can you verify that the problem also exists if you create a webdav, sshfs,... mount as external storage?

If my assumption is correct then we probably should first create a local copy and write it back if the user is done with editing. Probably something for the collabora app then.

**Comment by javierurien** [comment] 2018-06-25 17:41
Hello there,

  I have a similar problem. I configured Collabora and get to edit a document that lives in an External Storage. The problem I face is that there is no collaborative edition, two users open the same file there is no visibility between them, and the changes of only one survives the edition.
  Is this a byproduct of the solution mentioned in this thread? Is there a way to get collaborative editing for External Storage files?

Regards.

**Comment by nemhods** [comment] 2018-08-02 14:46
This seems to be a limitation of Collabora as well as the competitor Onlyoffice in conjunction with Nextcloud/Owncloud. From the OnlyOffice documentation:

> Adding the storage using the External storages app has issues with the co-editing in some cases. If the connection is made using the same authorization keys (the Username and password or Global credentials authentication type is selected), then the co-editing is available for the users. If different authorization keys are used (Log-in credentials, save in database or User entered, store in database authentication options), the co-editing is not available. When the Log-in credentials, save in session authentication type is used, the files cannot be opened in the editor. 

OnlyOffice devs have acknowledged this here: https://github.com/ONLYOFFICE/onlyoffice-owncloud/issues/132
@schiessle this might be worth opening a seperate issue about. Im afraid solving this would require some serious rewriting about how exactly Nextcloud and Collabora exchange files. A concerted effort of both Nextcloud and Collabora devs might be required.

**Comment by juliushaertl** [comment] 2019-01-18 12:40
Closing as a duplicate of https://github.com/nextcloud/richdocuments/issues/267

**Closed by juliushaertl** 2019-01-18 12:40 UTC
Labels: enhancement

**Comment by lachmanfrantisek** [comment] 2019-01-18 13:06
@juliushaertl You probably want to close the other one or add the `enhancement` label to the second issue...;)

**Comment by juliushaertl** [comment] 2019-01-18 13:09
@lachmanfrantisek I just recognized that there was a comment that is has worked before in the other post, so I kept the bug :wink: 
> I have this exact problem. Both nextclouds are upgraded to 14.0.3, although the problem started some time ago with version 13.?

**Comment by Desdemo** [comment] 2019-04-10 02:26
Is this problem solved? I have the same situation now.

**Comment by codejamninja** [comment] 2019-11-28 09:46
I'm facing the same issue with nextcloud `17.0.1` and onlyoffice `5.4.1.39`. Are there any plans to fix this?

**Comment by rollanders** [comment] 2020-01-09 16:54
I cannot open federated documents in Collabora, but OnlyOffice works normally. 
When I try open with collabora I get an error "Failed to load Collabora Online Development Edition - please try again later". I can open the file with OnlyOffice normally. Collabora works normally for normal non-federated files.

**Comment by Gordonfreeman882** [comment] 2020-02-25 14:55
This should be opened! It seems not to work as it should .
Running two federated NC 17.0.1.1 both having the same CODE defined in the Collabora App.
A shared document should open but it doesn't. Same Errormessage here: "Failed to load Collabora Online Development Edition - please try again later"

For non federated files Collabora work as expected from both NCs.
Using latest Apps and an manual installed Collabora CODE Server.
