### ISSUE TITLE
Cannot create new documents with new template function

### ISSUE THREAD

**Issue by ghost** [nextcloud/richdocuments#359] opened 2019-01-18 10:06 UTC
Debian 9.6 64Bit
NGINX 1.15.8 TLS1.3
OpenSSL_1_1_1-stable
PHP 7.3
MariaDB 10.3
docker 18.09.1
LOOLWSD 4.0.0 (git hash: 173510f)
LOKit Collabora Office 6.0-18 (git hash: e74e598)
Nextcloud 15.0.2
Collabora/Richdocuments: 3.1.1

Maybe related to: https://github.com/nextcloud/richdocuments/issues/355

Collabora works like a charme (THANK YOU!) for already existing documents.
![grafik](https://user-images.githubusercontent.com/20593693/51379980-fa0b9300-1b10-11e9-8e9e-41929921bd3a.png)

Creating new documents will fail at step "choose template" with the following errors:

![grafik](https://user-images.githubusercontent.com/20593693/51379521-e3b10780-1b0f-11e9-898e-9739d07bc6ea.png)

![grafik](https://user-images.githubusercontent.com/20593693/51379548-f9bec800-1b0f-11e9-95a9-270fd5c85c15.png)

![grafik](https://user-images.githubusercontent.com/20593693/51379572-09d6a780-1b10-11e9-843c-1d4d99d8eb28.png)

> Exception: /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 166: OCA\Richdocuments\Controller\DocumentController->index("-1")/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 99: OC\AppFramework\Http\Dispatcher->executeController(OCA\Richdocu ... {}, "index")/var/www/nextcloud/lib/private/AppFramework/App.php - line 118: OC\AppFramework\Http\Dispatcher->dispatch(OCA\Richdocu ... {}, "index")/var/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php - line 47: OC\AppFramework\App::main("OCA\\Richdo ... r", "index", OC\AppFramew ... {}, { _route: "r ... "})<<closure>>OC\AppFramework\Routing\RouteActionHandler->__invoke({ _route: "r ... "})/var/www/nextcloud/lib/private/Route/Router.php - line 297: call_user_func(OC\AppFramew ... {}, { _route: "r ... "})/var/www/nextcloud/lib/base.php - line 987: OC\Route\Router->match("/apps/richdocuments/index")/var/www/nextcloud/index.php - line 42: OC::handleRequest()

> Cannot declare class OCA\Richdocuments\Controller\DocumentController, because the name is already in use at /var/www/nextcloud/apps/richdocuments/lib/Controller/DocumentController.php#0

The adminpanel looks like
![grafik](https://user-images.githubusercontent.com/20593693/51379653-2ffc4780-1b10-11e9-91b7-e11d97d00ac8.png)

![grafik](https://user-images.githubusercontent.com/20593693/51379705-50c49d00-1b10-11e9-9ead-2bb750e005f1.png)

I would really appreciate your assistance, please let me know what you would like to have to investigate further.
Cheers, Carsten (https://www.c-rieger.de/nextcloud-and-collabora-nginx/)

**Comment by riegercloud** [comment] 2019-01-18 10:19
I found a quick workaround:
`cp -ar /var/www/nextcloud/apps/richdocuments/assets/ /var/nc_data/<user>/files`
Then select the copied asset folder as template folder and create a new office document:

![grafik](https://user-images.githubusercontent.com/20593693/51380699-9b471900-1b12-11e9-9ea9-a3bf0bff6455.png)

The new created document will be created and will also appear within the collabora app:
![grafik](https://user-images.githubusercontent.com/20593693/51380766-bf0a5f00-1b12-11e9-9b06-e13dea19f735.png)

**Comment by juliushaertl** [comment] 2019-01-18 12:24
The empty templates should actually get copied to the appdata folder. Can you check if data/appdata_*/richdocuments/empty_templates/ contains those?

**Comment by riegercloud** [comment] 2019-01-18 12:39
root@nc:/var/nc_data/appdata_*/richdocuments/empty_templates# ls -lsa
insgesamt 40
 4 drwxr-xr-x 2 www-data www-data  4096 Jan 16 08:27 .
 4 drwxr-xr-x 5 www-data www-data  4096 Jan 16 08:27 ..
 8 -rw-r--r-- 1 www-data www-data  7747 Jan 16 08:27 document.ott
16 -rw-r--r-- 1 www-data www-data 13732 Jan 16 08:27 presentation.otp
 8 -rw-r--r-- 1 www-data www-data  6855 Jan 16 08:27 spreadsheet.ots
root@nc:/var/nc_data/appdata_oc84hxlnpsu0/richdocuments/empty_templates#

**Comment by riegercloud** [comment] 2019-01-18 12:42
if you are interested in i can re-scan (occ files:scan --all) and / or re-install collabora?

**Comment by riegercloud** [comment] 2019-01-18 13:12
Yes, after a re-scan (occ files:scan) new documents can be created from scratch (templates from appdata_*/richdocuments/empty_templates) but only if they will get a specific/unique document name. 
If the name won't be set while creating it the process will still fail as shown below:

![grafik](https://user-images.githubusercontent.com/20593693/51388585-33043180-1b2a-11e9-99df-3def4614b07d.png)

![grafik](https://user-images.githubusercontent.com/20593693/51388598-457e6b00-1b2a-11e9-8ee5-8b85e03f41fc.png)
![grafik](https://user-images.githubusercontent.com/20593693/51388618-529b5a00-1b2a-11e9-937a-c4d144db1b88.png)

**Comment by juliushaertl** [comment] 2019-01-18 13:14
cc @rullzer

**Comment by mhow2** [comment] 2019-02-04 16:19
And what about the template's preview image broken as seen in https://help.nextcloud.com/t/template-selection-empty-and-broken-image/46524 ?

**Comment by joergmschulz** [comment] 2019-02-04 17:04
just the same. Broken here as well.

**Comment by joergmschulz** [comment] 2019-02-07 18:31
issue persists in 3.2.0

**Comment by hifihedgehog** [comment] 2019-02-08 19:38
Same. I also cannot open any files.

**Comment by Happyfeet01** [comment] 2019-02-10 02:28
Have the same issue. Maybe an reason why mobile editing in Nextcloud Android App stop working?

**Comment by juliushaertl** [comment] 2019-02-13 09:04
> (1) two issues remains: templates won't appear without re-scan (occ files:scan)

Strange, I could not reproduce this. :thinking: I wonder if it might have been a storage issue when trying to copy the files over. Any change you still have the log files from the point when upgrading richdocuments?

> (2) blank page if no template is selected on create

This one is fixed on master already

**Comment by joergmschulz** [comment] 2019-02-15 15:58
confirmed - the current version from NC app store fixes the issue as far as I can see

**Comment by michag86** [comment] 2019-02-19 21:50
Since app version 3.2.0 I cannot create new documents from templates.
The template settings disappeared from admin and personal settings.
Tested with collabora code 4.0.0.6

**Comment by michag86** [comment] 2019-02-19 22:27
When I try to create a new document and select one template (empty default also), I get this error:
Failed to load Collabora Online - please try again later

And this is logged in nextcloud.log:
```
{"reqId":"m4Y8Qx2yq8uUtodx8bKr","level":3,"time":"2019-02-19T23:24:13+01:00","remoteAddr":"92.117.40.214","user":"micha","app":"no app in context","method":"GET","url":"\/nc\/apps\/richdocuments\/indexTemplate?templateId=604866&fileName=test15.ods&dir=%2Ftmp&requesttoken=w7Ljx9EW35s00Gm%2FvJjta%2FoYKqSZeLtbWC8RQwd%2BLYs%3D%3Al4DQkeQupfABtgDWhKuKDZ9KaczQMvZjPWhcGVUwfaA%3D","message":{"Exception":"OCP\\Lock\\LockedException","Message":"\"files\/c037583bd7655012651fbd0f372422de\" is locked","Code":0,"Trace":[{"file":"\/var\/www\/htdocs\/nc\/lib\/private\/Files\/Storage\/Common.php","line":778,"function":"changeLock","class":"OC\\Lock\\DBLockingProvider","type":"->","args":["files\/c037583bd7655012651fbd0f372422de",2]},{"file":"\/var\/www\/htdocs\/nc\/lib\/private\/Files\/Storage\/Wrapper\/Wrapper.php","line":615,"function":"changeLock","class":"OC\\Files\\Storage\\Common","type":"->","args":["files\/tmp\/test15.ods",2,{"__class__":"OC\\Lock\\DBLockingProvider"}]},{"file":"\/var\/www\/htdocs\/nc\/lib\/private\/Files\/Storage\/Wrapper\/Wrapper.php","line":615,"function":"changeLock","class":"OC\\Files\\Storage\\Wrapper\\Wrapper","type":"->","args":["files\/tmp\/test15.ods",2,{"__class__":"OC\\Lock\\DBLockingProvider"}]},{"file":"\/var\/www\/htdocs\/nc\/lib\/private\/Files\/Storage\/Wrapper\/Wrapper.php","line":615,"function":"changeLock","class":"OC\\Files\\Storage\\Wrapper\\Wrapper","type":"->","args":["files\/tmp\/test15.ods",2,{"__class__":"OC\\Lock\\DBLockingProvider"}]},{"file":"\/var\/www\/htdocs\/nc\/lib\/private\/Files\/View.php","line":1970,"function":"changeLock","class":"OC\\Files\\Storage\\Wrapper\\Wrapper","type":"->","args":["files\/tmp\/test15.ods",2,{"__class__":"OC\\Lock\\DBLockingProvider"}]},{"file":"\/var\/www\/htdocs\/nc\/lib\/private\/Files\/View.php","line":1141,"function":"changeLock","class":"OC\\Files\\View","type":"->","args":["\/micha\/files\/tmp\/test15.ods",2]},{"file":"\/var\/www\/htdocs\/nc\/lib\/private\/Files\/View.php","line":567,"function":"basicOperation","class":"OC\\Files\\View","type":"->","args":["touch","\/micha\/files\/tmp\/test15.ods",["touch","create","write"],null]},{"file":"\/var\/www\/htdocs\/nc\/lib\/private\/Files\/Node\/Folder.php","line":181,"function":"touch","class":"OC\\Files\\View","type":"->","args":["\/micha\/files\/tmp\/test15.ods"]},{"file":"\/var\/www\/htdocs\/nc\/apps\/richdocuments\/lib\/Controller\/DocumentController.php","line":256,"function":"newFile","class":"OC\\Files\\Node\\Folder","type":"->","args":["test15.ods"]},{"file":"\/var\/www\/htdocs\/nc\/lib\/private\/AppFramework\/Http\/Dispatcher.php","line":166,"function":"template","class":"OCA\\Richdocuments\\Controller\\DocumentController","type":"->","args":[604866,"test15.ods","\/tmp"]},{"file":"\/var\/www\/htdocs\/nc\/lib\/private\/AppFramework\/Http\/Dispatcher.php","line":99,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Richdocuments\\Controller\\DocumentController"},"template"]},{"file":"\/var\/www\/htdocs\/nc\/lib\/private\/AppFramework\/App.php","line":118,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Richdocuments\\Controller\\DocumentController"},"template"]},{"file":"\/var\/www\/htdocs\/nc\/lib\/private\/AppFramework\/Routing\/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Richdocuments\\Controller\\DocumentController","template",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"_route":"richdocuments.document.template"}]},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->","args":[{"_route":"richdocuments.document.template"}]},{"file":"\/var\/www\/htdocs\/nc\/lib\/private\/Route\/Router.php","line":297,"function":"call_user_func","args":[{"__class__":"OC\\AppFramework\\Routing\\RouteActionHandler"},{"_route":"richdocuments.document.template"}]},{"file":"\/var\/www\/htdocs\/nc\/lib\/base.php","line":987,"function":"match","class":"OC\\Route\\Router","type":"->","args":["\/apps\/richdocuments\/indexTemplate"]},{"file":"\/var\/www\/htdocs\/nc\/index.php","line":42,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"\/var\/www\/htdocs\/nc\/lib\/private\/Lock\/DBLockingProvider.php","Line":271,"CustomMessage":"--"},"userAgent":"Mozilla\/5.0 (X11; Ubuntu; Linux x86_64; rv:65.0) Gecko\/20100101 Firefox\/65.0","version":"15.0.4.0"}
{"reqId":"m4Y8Qx2yq8uUtodx8bKr","level":3,"time":"2019-02-19T23:24:13+01:00","remoteAddr":"92.117.40.214","user":"micha","app":"index","method":"GET","url":"\/nc\/apps\/richdocuments\/indexTemplate?templateId=604866&fileName=test15.ods&dir=%2Ftmp&requesttoken=w7Ljx9EW35s00Gm%2FvJjta%2FoYKqSZeLtbWC8RQwd%2BLYs%3D%3Al4DQkeQupfABtgDWhKuKDZ9KaczQMvZjPWhcGVUwfaA%3D","message":{"Exception":"OCP\\Lock\\LockedException","Message":"\"tmp\/test15.ods\" is locked","Code":0,"Trace":[{"file":"\/var\/www\/htdocs\/nc\/lib\/private\/Files\/View.php","line":1141,"function":"changeLock","class":"OC\\Files\\View","type":"->","args":["\/micha\/files\/tmp\/test15.ods",2]},{"file":"\/var\/www\/htdocs\/nc\/lib\/private\/Files\/View.php","line":567,"function":"basicOperation","class":"OC\\Files\\View","type":"->","args":["touch","\/micha\/files\/tmp\/test15.ods",["touch","create","write"],null]},{"file":"\/var\/www\/htdocs\/nc\/lib\/private\/Files\/Node\/Folder.php","line":181,"function":"touch","class":"OC\\Files\\View","type":"->","args":["\/micha\/files\/tmp\/test15.ods"]},{"file":"\/var\/www\/htdocs\/nc\/apps\/richdocuments\/lib\/Controller\/DocumentController.php","line":256,"function":"newFile","class":"OC\\Files\\Node\\Folder","type":"->","args":["test15.ods"]},{"file":"\/var\/www\/htdocs\/nc\/lib\/private\/AppFramework\/Http\/Dispatcher.php","line":166,"function":"template","class":"OCA\\Richdocuments\\Controller\\DocumentController","type":"->","args":[604866,"test15.ods","\/tmp"]},{"file":"\/var\/www\/htdocs\/nc\/lib\/private\/AppFramework\/Http\/Dispatcher.php","line":99,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Richdocuments\\Controller\\DocumentController"},"template"]},{"file":"\/var\/www\/htdocs\/nc\/lib\/private\/AppFramework\/App.php","line":118,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Richdocuments\\Controller\\DocumentController"},"template"]},{"file":"\/var\/www\/htdocs\/nc\/lib\/private\/AppFramework\/Routing\/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Richdocuments\\Controller\\DocumentController","template",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"_route":"richdocuments.document.template"}]},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->","args":[{"_route":"richdocuments.document.template"}]},{"file":"\/var\/www\/htdocs\/nc\/lib\/private\/Route\/Router.php","line":297,"function":"call_user_func","args":[{"__class__":"OC\\AppFramework\\Routing\\RouteActionHandler"},{"_route":"richdocuments.document.template"}]},{"file":"\/var\/www\/htdocs\/nc\/lib\/base.php","line":987,"function":"match","class":"OC\\Route\\Router","type":"->","args":["\/apps\/richdocuments\/indexTemplate"]},{"file":"\/var\/www\/htdocs\/nc\/index.php","line":42,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"\/var\/www\/htdocs\/nc\/lib\/private\/Files\/View.php","Line":1976,"Previous":{"Exception":"OCP\\Lock\\LockedException","Message":"\"files\/c037583bd7655012651fbd0f372422de\" is locked","Code":0,"Trace":[{"file":"\/var\/www\/htdocs\/nc\/lib\/private\/Files\/Storage\/Common.php","line":778,"function":"changeLock","class":"OC\\Lock\\DBLockingProvider","type":"->","args":["files\/c037583bd7655012651fbd0f372422de",2]},{"file":"\/var\/www\/htdocs\/nc\/lib\/private\/Files\/Storage\/Wrapper\/Wrapper.php","line":615,"function":"changeLock","class":"OC\\Files\\Storage\\Common","type":"->","args":["files\/tmp\/test15.ods",2,{"__class__":"OC\\Lock\\DBLockingProvider"}]},{"file":"\/var\/www\/htdocs\/nc\/lib\/private\/Files\/Storage\/Wrapper\/Wrapper.php","line":615,"function":"changeLock","class":"OC\\Files\\Storage\\Wrapper\\Wrapper","type":"->","args":["files\/tmp\/test15.ods",2,{"__class__":"OC\\Lock\\DBLockingProvider"}]},{"file":"\/var\/www\/htdocs\/nc\/lib\/private\/Files\/Storage\/Wrapper\/Wrapper.php","line":615,"function":"changeLock","class":"OC\\Files\\Storage\\Wrapper\\Wrapper","type":"->","args":["files\/tmp\/test15.ods",2,{"__class__":"OC\\Lock\\DBLockingProvider"}]},{"file":"\/var\/www\/htdocs\/nc\/lib\/private\/Files\/View.php","line":1970,"function":"changeLock","class":"OC\\Files\\Storage\\Wrapper\\Wrapper","type":"->","args":["files\/tmp\/test15.ods",2,{"__class__":"OC\\Lock\\DBLockingProvider"}]},{"file":"\/var\/www\/htdocs\/nc\/lib\/private\/Files\/View.php","line":1141,"function":"changeLock","class":"OC\\Files\\View","type":"->","args":["\/micha\/files\/tmp\/test15.ods",2]},{"file":"\/var\/www\/htdocs\/nc\/lib\/private\/Files\/View.php","line":567,"function":"basicOperation","class":"OC\\Files\\View","type":"->","args":["touch","\/micha\/files\/tmp\/test15.ods",["touch","create","write"],null]},{"file":"\/var\/www\/htdocs\/nc\/lib\/private\/Files\/Node\/Folder.php","line":181,"function":"touch","class":"OC\\Files\\View","type":"->","args":["\/micha\/files\/tmp\/test15.ods"]},{"file":"\/var\/www\/htdocs\/nc\/apps\/richdocuments\/lib\/Controller\/DocumentController.php","line":256,"function":"newFile","class":"OC\\Files\\Node\\Folder","type":"->","args":["test15.ods"]},{"file":"\/var\/www\/htdocs\/nc\/lib\/private\/AppFramework\/Http\/Dispatcher.php","line":166,"function":"template","class":"OCA\\Richdocuments\\Controller\\DocumentController","type":"->","args":[604866,"test15.ods","\/tmp"]},{"file":"\/var\/www\/htdocs\/nc\/lib\/private\/AppFramework\/Http\/Dispatcher.php","line":99,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Richdocuments\\Controller\\DocumentController"},"template"]},{"file":"\/var\/www\/htdocs\/nc\/lib\/private\/AppFramework\/App.php","line":118,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Richdocuments\\Controller\\DocumentController"},"template"]},{"file":"\/var\/www\/htdocs\/nc\/lib\/private\/AppFramework\/Routing\/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Richdocuments\\Controller\\DocumentController","template",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"_route":"richdocuments.document.template"}]},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->","args":[{"_route":"richdocuments.document.template"}]},{"file":"\/var\/www\/htdocs\/nc\/lib\/private\/Route\/Router.php","line":297,"function":"call_user_func","args":[{"__class__":"OC\\AppFramework\\Routing\\RouteActionHandler"},{"_route":"richdocuments.document.template"}]},{"file":"\/var\/www\/htdocs\/nc\/lib\/base.php","line":987,"function":"match","class":"OC\\Route\\Router","type":"->","args":["\/apps\/richdocuments\/indexTemplate"]},{"file":"\/var\/www\/htdocs\/nc\/index.php","line":42,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"\/var\/www\/htdocs\/nc\/lib\/private\/Lock\/DBLockingProvider.php","Line":271},"CustomMessage":"--"},"userAgent":"Mozilla\/5.0 (X11; Ubuntu; Linux x86_64; rv:65.0) Gecko\/20100101 Firefox\/65.0","version":"15.0.4.0"}
```

After this error, there is a new document with 0 bytes size.

Tested with App Version 3.2.1

@juliushaertl @thebearon

**Comment by juliushaertl** [comment] 2019-02-20 11:32
@rullzer Any idea why the file might be locked?

**Comment by rmeissn** [comment] 2019-02-20 13:01
This might be related to #355 .

My observations with v3.2.1:
* By default the app opened newly created files (all templates) with the writer app (e.g. instead of calc) - I don't know what fixed it for me, but it works now. I moved the templates a few times and did some rescans.
* templates have no pictures (see last picture of initial posting) - I guess there should be a preview?!
* I can't delete or upload templates in the settings dialog
* There are only three templates in the settings dialog, even though there should be six (see below)

Content of data/appdata_oc.../richdocuments/templates/
```
total 72
 4 drwxr-xr-x 2 991 991  4096 Feb 20 13:33 .
 4 drwxr-xr-x 5 991 991  4096 Feb 20 13:26 ..
 8 -rw-r--r-- 1 991 991  7706 Feb 20 11:08 document.ott
16 -rw-r--r-- 1 991 991 13690 Feb 20 11:08 presentation.otp
 8 -rw-r--r-- 1 991 991  6799 Feb 20 11:08 spreadsheet.ots
16 -rw-r--r-- 1 991 991 13090 Feb 20 13:33 template.odp
 8 -rw-r--r-- 1 991 991  7134 Feb 20 13:33 template.ods
 8 -rw-r--r-- 1 991 991  7938 Feb 20 13:33 template.odt
```

Content of data/appdata_oc.../richdocuments/empty_templates/
```
total 40
 4 drwxr-xr-x 2 991 991  4096 Feb 20 13:31 .
 4 drwxr-xr-x 5 991 991  4096 Feb 20 13:26 ..
 8 -rw-r--r-- 1 991 991  7706 Feb 20 13:31 document.ott
16 -rw-r--r-- 1 991 991 13690 Feb 20 13:31 presentation.otp
 8 -rw-r--r-- 1 991 991  6799 Feb 20 13:31 spreadsheet.ots
```

**Comment by juliushaertl** [comment] 2019-02-26 20:56
> 4\. There are only three templates in the settings dialog, even though there should be six (see below)

Just having the three templates there is correct. The other ones (template.*) are fallback files that will just be used to create new files if the collabora version doesn't support templates.

**Comment by peteman52** [comment] 2019-02-27 11:37
Issue persists, went back to 3.0.0
Is there a timeline for new updates?

**Comment by PpaiSanchez** [comment] 2019-03-22 15:25
I now have the same mistakes. The NextCloud server is completely new installed. Question: Can I completely disable this function of the templates? This totally annoys.
Thank you.

**Comment by brknkfr** [comment] 2019-03-28 10:25
Another hint: After copying the templates to appdata_XXX/richdocuments/templates, run
`occ files:scan-app-data`

**Comment by brtptrs** [comment] 2019-04-12 14:22
For us the problem was solved this way:
1) Delete Duplicate files between data/appdata_oc.../richdocuments/templates and data/appdata_oc.../richdocuments/empty_templates/
2) Rerun occ files:scan-app-data

**Comment by beccon4** [comment] 2019-06-05 19:10
Unfortunately none of the hints and workarounds help in my case.

Creating a new document asks for a template. No matter where the one I select comes from

![grafik](https://user-images.githubusercontent.com/12436716/58982458-c934ad80-87d4-11e9-8034-9bb2e743bab2.png)

... the Libre Office Online canvas opens - but not with the ods file but with the ott file name (Modern.ott in my case)

![grafik](https://user-images.githubusercontent.com/12436716/58982570-0d27b280-87d5-11e9-9077-31bedcc144cf.png)

Then I can edit the file - type in something - but saving fails miserably:

![grafik](https://user-images.githubusercontent.com/12436716/58982736-6a236880-87d5-11e9-91fa-8612a5aa92b1.png)

There is no log entry in 
- apache access.log
- apache error.log
- nextcloud.log
- loolwsd.log

To make matters worse - my newly created file is empty (0 bytes) and cannot be opened.

What now?

System:
- Debian: SMP Debian 4.9.168-1+deb9u2 (2019-05-13) x86_64 GNU/Linux
- Nextcloud 16.0.1
- LibreOffice Online LOOLWSD 3.0.0 (git hash: 8a1761a)  LOKit
Collabora Office 5.3-39 (git hash: 150d6f4)
- Collabora Online 3.3.8

**Comment by joergmschulz** [comment] 2019-06-05 19:21
your loolwsd and collabora versions seem to be a bit outdated - can you try and install more recent versions?
![grafik](https://user-images.githubusercontent.com/6523646/58983777-de5f0b80-87d7-11e9-901a-7e4021b4cd18.png)

**Comment by enoch85** [comment] 2019-09-28 18:28
I don't know if this is related but here's hos my log looks like since the past few weeks:

![Screenshot from 2019-09-28 20:26:29](https://user-images.githubusercontent.com/4511254/65820863-59887980-e22e-11e9-87b2-cfb9ffcb062e.png)

**Collabora Online Nextcloud App:** 3.4.2
**Docker image:** Latest

**Comment by juliushaertl** [comment] 2019-10-04 14:03
@enoch85 Please open a new issue, this seems unrelated.

**Comment by juliushaertl** [comment] 2021-01-08 15:55
Please check if this is still an issue with the latest richdocuments and collabora release after running `occ richdocuments:update-empty-templates` This should make sure that the templates are properly put in place if anything got wrong in the past with them.

**Closed by juliushaertl** 2021-01-08 15:55 UTC
Labels: bug, info needed
