### ISSUE TITLE
Restricting to Groups no longer works

### ISSUE THREAD

**Issue by danimo** [nextcloud/richdocuments#3018] opened 2023-06-15 13:57 UTC
**Describe the bug**

After ugprading to NC 26 with version 8.0.2, the restriction to certain groups as outlined in the screenshot below no longer has any effect. The Office app will open for everyone.

**To Reproduce**
1. Go to 'Administration Settings'
2. Click on 'Office'
3. Click "Restrict Usage to specific group"
4. Pick a group
5. Log in as a member of group not chosen in in Step 4.
6. Click on an office document
7. See Document opening in `richdocuments` app instead of receiving a download dialog

**Expected behavior**
Nextcloud should behave as though the `richdocuments` app was not installed to members of all groups but the one in the allow list.

**Screenshots**

<img width="937" alt="image" src="https://github.com/nextcloud/richdocuments/assets/1315934/d48e506c-a25e-41d5-bf89-aed9662884f2">

**Client details:**
 - OS: [iOS, Linux]
 - Browser [Chromium]
 - Version [e.g. 26.0.2]

## Server details

**Operating system**:
 Containerized

**Web server:**
 nginx
**Database:**
 Postgres

**PHP version:**
8.1

**Nextcloud version:**
26.0.2

**Version of the richdocuments app**
8.0.2

**Version of Collabora Online**
22.05.14.3.1

**Comment by danimo** [comment] 2023-06-15 13:58
I could independently verify the behavior on the setup of an external service provider (Hetzner), so it doesn't seem to be an issue of my setup.

**Comment by joshtrichards** [comment] 2023-07-13 14:08
Hi @danimo - So far I'm unable to reproduce this behavior. The closest I can get is that if I restrict access (in a different browser session) then re-attempt access without reloading - it'll try to open CODE, but fails (blank screen). If I reload first in the restricted session then it properly downloads as expected.

Can you provide the output of `./occ config:list richdocuments`?

**Comment by joshtrichards** [comment] 2024-03-25 16:23
Closing due to lack of follow-up info, no further reports, and also inability to reproduce.

**Closed by joshtrichards** 2024-03-25 16:23 UTC
Labels: bug, 1. to develop, needs info, feature: settings
