### ISSUE TITLE
Nextcloud app doesn't open Office doc

### ISSUE THREAD

**Issue by azertylr** [nextcloud/richdocuments#3468] opened 2024-02-12 19:29 UTC
**Describe the bug**
Opening an office file in Nextcloud app doesn't open Nextcloud Office doc (it is working on webbrowser)

**To Reproduce**
1. Open Nextcloud Android App
2. Open an ods/xls/... doc
3. Doc doesn't open

**Client details:**
 - OS: Android 13
 - App: Nextcloud 3.27.0
 - Collabora: Code 23.05.8.4
 - Nextcloud: 28.0.2

**Log**
*.*.*.* - [] "GET /ocs/v2.php/cloud/user?format=json HTTP/2.0" 200 465 "-" "Mozilla/5.0 (Android) Nextcloud-android/3.27.0"

**Comment by contactnat** [comment] 2024-02-12 21:16
I have had the same problem for a while now, I have seen similar issues raised a few times but seems to not get anywhere, interested to see if this gets resolved.

**Comment by joshtrichards** [comment] 2024-02-12 22:48
Duplicate of nextcloud/android#12338

**Closed by joshtrichards** 2024-02-12 22:48 UTC
