### ISSUE TITLE
6.1.0 no longer plays nice with OnlyOffice

### ISSUE THREAD

**Issue by brendan-pike** [nextcloud/richdocuments#2281] opened 2022-06-22 10:25 UTC
We need to run both Collabora and Onlyoffice which had worked fine because I set Onlyoffice to only handle specific file types. 
Today I upgraded to nextcloud 24.02 as well as Nextcloud Office app to 6.1.0.  Now when I click on a .docx file it opens in Collabora which it never did before.
If I right click on a docx file and select "Open in OnlyOffice" then it will correctly open in OnlyOffice.

How can I stop Nextcloud Office from handling specific file types?

**Comment by Raudius** [comment] 2022-06-22 11:54
Hi, thanks for the report!

Unfortunately it is not currently possible to choose what files Nextcloud Office can handle. At a glance I don't think this change in behaviour would be caused by the 6.1.0 update. I will try having a closer look.

In the meantime can you check your Onlyoffice settings:  
  * Under the option `The default application for opening the format`, is `docx` selected? 
  * If so could you try un-selecting and selecting it again?

You can also try asking in the onlyoffice repo. It is possible that something in their code doesn't play nicely with the server update.

**Comment by brendan-pike** [comment] 2022-06-22 13:16
Hi Raudius

Yes Onlyoffice has docx selected and yes I also thought to try disable/re-enabling this but it didn't help.

I'll reporting it to onlyoffice as well and see what comes.

Cheers

**Comment by proxyconcept** [comment] 2022-06-29 12:01
I think it's related to #1400 and #1783 

And the solution should come from nextcloud/server#8105

But I remain surprised and somewhat disappointed to still not see anything coming on this subject...

**Comment by proxyconcept** [comment] 2022-07-06 10:13
I just made a new clean pull request.

I can understand that this solution can't be merged upstream (because it's a bit arbitrary with the choices of mime types associations), but for us it's a great workaround: this patch is required when we have a nextcloud instance with both NextcloudOffice and OnlyOffice.

PS (tips) : this app https://lab.libreho.st/libre.sh/nextcloud-apps/multioffice is cool in order to have a nice menu to create files

**Comment by brendan-pike** [comment] 2022-07-07 03:39
Thank you for sharing proxyconcept and for that amazing menu app too. I was starting to think I was the only person in the world to use both Collabora along side OnlyOffice.
Hopefully nextcloud will come up with a robust mime selector type solution

**Comment by lucbuzenval** [comment] 2022-07-22 15:23
> I just made a new clean pull request.
> 
> I can understand that this solution can't be merged upstream (because it's a bit arbitrary with the choices of mime types associations), but for us it's a great workaround: this patch is required when we have a nextcloud instance with both NextcloudOffice and OnlyOffice.
> 
> PS (tips) : this app https://lab.libreho.st/libre.sh/nextcloud-apps/multioffice is cool in order to have a nice menu to create files

Thank you @proxyconcept but how to install https://lab.libreho.st/libre.sh/nextcloud-apps/multioffice ?

Best regards

**Comment by proxyconcept** [comment] 2022-07-22 16:58
> Thank you @proxyconcept but how to install https://lab.libreho.st/libre.sh/nextcloud-apps/multioffice ?

This app is not available in the Nextcloud App Store, but manual installation is easy: you juste have to put the code in a subfolder inside your apps folder.

For example: `git clone "https://lab.libreho.st/libre.sh/nextcloud-apps/multioffice.git" /var/www/nextcloud/apps/multioffice`

**Closed** 2023-09-08 21:23 UTC
