### ISSUE TITLE
Create new file icons missing since 3.2.1

### ISSUE THREAD

**Issue by michag86** [nextcloud/richdocuments#410] opened 2019-02-19 21:06 UTC
Icons on add file dialog missing since 3.2.1

![grafik](https://user-images.githubusercontent.com/6691165/53047259-56582e80-3492-11e9-8d17-1d1523f8193d.png)

This was working in 3.2.0

cc @timar @pranavk @MorrisJobke

**Comment by thebearon** [comment] 2019-02-19 21:30
Thanks for the bug report, the issue is already fixed by #405 in master.

**Closed by thebearon** 2019-02-19 21:30 UTC
Labels: bug

**Comment by michag86** [comment] 2019-02-19 21:31
Thanks! Hope this will be released soon.
