### ISSUE TITLE
[PHP] Fehler: Undefined array key "type"

### ISSUE THREAD

**Issue by michaelfliegner** [nextcloud/richdocuments#4305] opened 2024-12-03 21:04 UTC
**Describe the bug**
just a logged exception, cannot associate to functionality

**To Reproduce**

**Expected behavior**

**Screenshots**

**Client details:**
 - Device: [e.g. iPhone6, desktop]

## Server details

** OS **:
Ubuntu 24.04
**Web server:**

**Database:**

**PHP version:**

**Nextcloud version:**
30.0.2 AIO 10.0.0
**Version of the richdocuments app**

**Version of Collabora Online**

**Configuration of the richdocuments app**
```
Insert the output of `./occ config:list richdocuments` (or equivalent adapted for your runtime environment)
```

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
[PHP] Fehler: Undefined array key "type" at /var/www/html/custom_apps/richdocuments/lib/Service/TemplateFieldService.php#96
	GET /ocs/v2.php/apps/files/api/v1/templates
	von 149.233.227.230 von MichaelFliegner um 13.11.2024, 18:34:20
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

</details>

**Comment by juliusknorr** [comment] 2024-12-03 21:27
Thanks for taking the time to report this. We have a fix pending that will become available with the next release.

Closing as a duplicate of https://github.com/nextcloud/richdocuments/issues/4228

**Closed by juliusknorr** 2024-12-03 21:27 UTC
