### ISSUE TITLE
Error richdocument OCP\Files\NotPermittedException: when file access control on file

### ISSUE THREAD

**Issue by manu-p** [nextcloud/richdocuments#1763] opened 2021-09-16 07:03 UTC
When a folder and/or file is tagged and a **File Access Control** control flow is set up to filter access to it, such as something like :

- when the folder/file is tagged with "thisTag" 
 
and 
- the user's not member of group "thisGroup" 

then block access, 
 
a user member of group "thisGroup" trying to open and document with Collabora Online - Built-in CODE Server gets the following message displayed:

> Failed to load the document. Please ensure the file type is supported and not corrupted, and try again.

The NC logs shows a **Error richdocument OCP\Files\NotPermittedException:**, see below.

When the control flow is removed, the opening of the same file works fine.
When the tag is put on the file, but no File Access Control flow set up, the opening of the same file works fine.
Files of other types, such as pdf, under the same File Access Control flow open successfully.

**To Reproduce**
1. Add a File Access Control flow with condition as above (tagged thisTag and user not member of thisGroup)
2. Add the tag thisTag to a document file (.od*)
3. Put a user in the group thisGroup
4. Open the tagged document when logged as the previous user
5. See error

**Expected behavior**
Users being allowed to open the document open it successfully.

**Client details:**
 - OS: All
 - Browser: all
 - Version: all
 - Device: all

## Server details

**Operating system**: Ubuntu 20.04

**Web server:** Apache 2.4

**Database:** MySQL 8

**PHP version:** 7.4

**Nextcloud version:** 21.0.4

**Version of the richdocuments app**: 6.4.806

**Version of Collabora Online**: 4.2.3

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```

{"reqId":"XXzvHFoo8uQeqci4LRwd","level":3,"time":"2021-09-15T14:59:26+00:00","remoteAddr":"127.0.0.1","user":"--","app":"richdocuments","method":"GET","url":"/index.php/apps/richdocuments/wopi/files/1322388_ocexfnilz0j7/contents?access_token=hjyHyTUtxLeLkZ8YuZxnXfe2efMV4BqG&access_token_ttl=0&reuse_cookies=__Host-nc_sameSiteCookielax%3Dtrue%3A__Host-nc_sameSiteCookiestrict%3Dtrue%3Aocexfnilz0j7%3D6moinlaav01ct6gd72ervmhrft%3Aoc_sessionPassphrase%3DiAwV7R5W9mCcwVuBpPR9AQTfnNeQFe3Stgz31AFtGChG7KDETH2s%2BYHJSWkMluWaRmya3KlYTVE7qpB2LlsOK905MOFVbS4W1lXjA%2BCNzG%2BZ6cr574q23wtUpSdpU1PX%3Anc_username%3DuserName%3Anc_token%3DrZVjea%2FsgmAqJd%2B%2FRCdot4AJYbJSBaAC%3Anc_session_id%3D6moinlaav01ct6gd72ervmhrft%2Fws%3FWOPISrc%3Dhttps%3A%2F%2Fcloud.site.com%2Findex.php%2Fapps%2Frichdocuments%2Fwopi%2Ffiles%2F1322388_ocexfnilz0j7&compat=","message":{"Exception":"OCP\\Files\\NotPermittedException","Message":"","Code":0,"Trace":[{"file":"/var/www/nextcloud/apps/richdocuments/lib/Controller/WopiController.php","line":402,"function":"fopen","class":"OC\\Files\\Node\\File","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":218,"function":"getFile","class":"OCA\\Richdocuments\\Controller\\WopiController","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":127,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":157,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":302,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/nextcloud/lib/base.php","line":993,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/nextcloud/index.php","line":37,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/nextcloud/lib/private/Files/Node/File.php","Line":119,"CustomMessage":"getFile failed"},"userAgent":"LOOLWSD WOPI Agent 6.4.8","version":"21.0.4.1","id":"61420a4fafc17"}
```
</details>

**Comment by KnudH** [comment] 2022-08-30 11:54
Same error here! Could you solve or workaround it?

**Comment by joshtrichards** [comment] 2023-11-09 20:00
Duplicate of #1168 

Lets consolidate tracking there.

**Closed by joshtrichards** 2023-11-09 20:00 UTC
Labels: bug
