### ISSUE TITLE
collabora container must be restarted to open documents from nextcloud

### ISSUE THREAD

**Issue by gibberfishinc** [nextcloud/richdocuments#36] opened 2017-04-06 20:32 UTC
### Steps to reproduce
1. start up a fresh collabora container
2. have a nextcloud instance already configured to use it
3. try to open a document
4. Fail
5. restart the container
6. try to open a document
7. succeed!

### Expected behaviour
Step 4 succeeds

### Actual behaviour
Error message in nextcloud, and this output from collabora:

> collabora    | Generating RSA private key, 2048 bit long modulus
collabora    | ..........+++
collabora    | ...+++
collabora    | e is 65537 (0x10001)
collabora    | Generating RSA private key, 2048 bit long modulus
collabora    | ................+++
collabora    | ....................+++
collabora    | e is 65537 (0x10001)
collabora    | Signature ok
collabora    | subject=/C=DE/ST=BW/L=Stuttgart/O=Dummy Authority/CN=localhost
collabora    | Getting CA Private Key
collabora    | loolforkit version details: 2.0.4 - 2.0.4
collabora    | office version details: { "ProductName": "Collabora Office", "ProductVersion": "5.1", "ProductExtension": ".10.21", "BuildId": "e91d2c2d59b035e40bdefac5fe06fb210180ed86" }
collabora    | wsd-00026-0027 20:15:40.553692 [ client_req_hdl ] WRN  WOPI host did not pass optional access_token_ttl| wsd/FileServer.cpp:255
collabora    | wsd-00026-0029 20:15:41.550065 [ client_ws_0001 ] WRN  Missing JSON property [HidePrintOption]| wsd/Storage.cpp:353
collabora    | wsd-00026-0029 20:15:41.550235 [ client_ws_0001 ] WRN  Missing JSON property [HideSaveOption]| wsd/Storage.cpp:353
collabora    | wsd-00026-0029 20:15:41.550318 [ client_ws_0001 ] WRN  Missing JSON property [HideExportOption]| wsd/Storage.cpp:353
collabora    | wsd-00026-0029 20:15:41.550423 [ client_ws_0001 ] WRN  Missing JSON property [EnableOwnerTermination]| wsd/Storage.cpp:353
collabora    | wsd-00026-0029 20:15:41.550506 [ client_ws_0001 ] WRN  Missing JSON property [DisablePrint]| wsd/Storage.cpp:353
collabora    | wsd-00026-0029 20:15:41.550584 [ client_ws_0001 ] WRN  Missing JSON property [DisableExport]| wsd/Storage.cpp:353
collabora    | wsd-00026-0029 20:15:41.550656 [ client_ws_0001 ] WRN  Missing JSON property [DisableCopy]| wsd/Storage.cpp:353
collabora    | kit-00084-0172 20:15:42.194272 [ lok_handler ] ERR  Failed to load: file:///user/docs/84/how%20it%20works%201.docx, error: loadComponentFromURL returned an empty reference| kit/Kit.cpp:1149
collabora    | kit-00084-0172 20:15:42.194451 [ lok_handler ] ERR  Failed to get LoKitDocument instance.| kit/ChildSession.cpp:334
collabora    | wsd-00026-0029 20:15:42.290033 [ client_ws_0001 ] WRN  SocketProcessor [client_ws_0001]: Connection closed.| common/IoUtil.cpp:100

### Server configuration
**Operating system**:
Debian 8

**Web server:**
Apache 2,4

**Database:**
Mariadb 10

**PHP version:**
5.6.30

**Nextcloud version:** (see Nextcloud admin page)
11.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:**
Fresh

**Where did you install Nextcloud from:**
Tarball

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - calendar: 1.5.2
  - comments: 1.1.0
  - contacts: 1.5.3
  - dav: 1.1.1
  - deck: 0.1.2
  - direct_menu: 0.10.1
  - federatedfilesharing: 1.1.1
  - federation: 1.1.1
  - files: 1.6.1
  - files_accesscontrol: 1.1.2
  - files_automatedtagging: 1.1.1
  - files_pdfviewer: 1.0.1
  - files_retention: 1.0.1
  - files_sharing: 1.1.1
  - files_texteditor: 2.2
  - files_trashbin: 1.1.0
  - files_versions: 1.4.0
  - files_videoplayer: 1.0.0
  - firstrunwizard: 2.0
  - gallery: 16.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.0
  - notifications: 1.0.1
  - ojsxc: 3.1.1
  - password_policy: 1.1.0
  - provisioning_api: 1.1.0
  - richdocuments: 1.1.25
  - serverinfo: 1.1.1
  - sharebymail: 1.0.1
  - spreedme: 0.3.8
  - systemtags: 1.1.3
  - tasks: 0.9.5
  - theming: 1.1.1
  - twofactor_backupcodes: 1.0.0
  - twofactor_totp: 1.1.0
  - workflowengine: 1.1.1
Disabled:
  - activity
  - admin_audit
  - bookmarks
  - encryption
  - external
  - files_external
  - keeweb
  - onlyoffice
  - rainloop
  - spreed
  - survey_client
```
</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>

```
<?php
$CONFIG = array (
  'passwordsalt' => 'xxxxxxx',
  'secret' => 'xxxxxxx',
  'trusted_domains' => 
  array (
    0 => 'xxxxxxx',
  ),
  'datadirectory' => '/opt/nextcloud/data',
  'overwrite.cli.url' => 'http://localhost',
  'dbtype' => 'mysql',
  'version' => '11.0.2.7',
  'dbname' => 'nextcloud',
  'dbhost' => 'mariadb',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'xxxxxxx',
  'dbpassword' => 'xxxxxxx',
  'logtimezone' => 'UTC',
  'installed' => true,
  'instanceid' => 'xxxxxxx',
  'memcache.local' => '\\OC\\Memcache\\Redis',
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'redis' => 
  array (
    'host' => 'redis',
    'port' => 6379,
  ),
  'htaccess.RewriteBase' => '/',
  'maintenance' => false,
  'loglevel' => 2,
  'theme' => '',
  'mail_smtpmode' => 'php',
  'mail_from_address' => 'noreply',
  'mail_domain' => 'xxxxxxx',
);

```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:**
Chrome 57.x
**Operating system:**
Fedora 25

**Comment by maexbower** [comment] 2017-05-26 08:58
can confirm that: on:
Using Debian 8.7
Nextcloud 11.0.3.2
PHP 7.0.18
MySQL 5.5.54

Docker runs on:
CentOS Linux release 7.3.1611
Docker 1.12.6

**Comment by khanasif2** [comment] 2017-05-29 10:13
Similar Problem here, after 4-5 days I have restart or remove the collabora containner.

**Operating system:** Ubuntu 16.04.2 LTS (XENIAL) 
**Web server:** Apache/2.4.18
**Database:** 10.0.29-Mariadb
**PHP version**: 7.0.15
**Nextcloud version:** 12.0.0 

**Dockers Log:**
Generating RSA private key, 2048 bit long modulus
....................................................................................+++
...............................+++
e is 65537 (0x10001)
Generating RSA private key, 2048 bit long modulus
..+++
...............+++
e is 65537 (0x10001)
Signature ok
subject=/C=DE/ST=BW/L=Stuttgart/O=Dummy Authority/CN=localhost
Getting CA Private Key
loolforkit version details: 2.1.1 - 52f0568e
office version details: { "ProductName": "Collabora Office", "ProductVersion": "5.3", "ProductExtension": ".10.13", "BuildId": "e639c2ad9c05a793b16db13bd879342ed75dcf95" }
wsd-00026-00034 07:12:59.477586 [ websrv_poll ] WRN  WOPI host did not pass optional access_token_ttl| wsd/FileServer.cpp:317
wsd-00026-00036 07:13:01.474901 [ docbroker_001 ] WRN  Missing JSON property [HidePrintOption]| wsd/Storage.cpp:387
wsd-00026-00036 07:13:01.474961 [ docbroker_001 ] WRN  Missing JSON property [HideSaveOption]| wsd/Storage.cpp:387
wsd-00026-00036 07:13:01.474997 [ docbroker_001 ] WRN  Missing JSON property [HideExportOption]| wsd/Storage.cpp:387
wsd-00026-00036 07:13:01.475021 [ docbroker_001 ] WRN  Missing JSON property [EnableOwnerTermination]| wsd/Storage.cpp:387
wsd-00026-00036 07:13:01.475053 [ docbroker_001 ] WRN  Missing JSON property [DisablePrint]| wsd/Storage.cpp:387
wsd-00026-00036 07:13:01.475073 [ docbroker_001 ] WRN  Missing JSON property [DisableExport]| wsd/Storage.cpp:387
wsd-00026-00036 07:13:01.475104 [ docbroker_001 ] WRN  Missing JSON property [DisableCopy]| wsd/Storage.cpp:387
wsd-00026-00036 07:13:01.475124 [ docbroker_001 ] WRN  Missing JSON property [LastModifiedTime]| wsd/Storage.cpp:387
wsd-00026-00036 07:13:01.498861 [ docbroker_001 ] WRN  Attempted ping on non-upgraded websocket!| ./net/WebSocketHandler.hpp:285
wsd-00026-00036 07:13:15.800933 [ docbroker_001 ] ERR  Socket #18 SSL BIO error: error:140D00CF:SSL routines:SSL_write:protocol is shutdown (errno: Transport endpoint is not connected)| ./net/SslSocket.hpp:273
wsd-00026-00036 07:13:15.801173 [ docbroker_001 ] WRN  ToClient-0002: Exception while closing socket for docKey [nextcloud-forum-asia.org:443/apps/richdocuments/wopi/files/136750_ocuyeaonhtz6]: error:140D00CF:SSL routines:SSL_write:protocol is shutdown| wsd/ClientSession.cpp:805
wsd-00026-00027 07:13:15.803685 [ prisoner_poll ] WRN  Waking up dead poll thread [docbroker_001], started: true, finished: true| ./net/Socket.hpp:507
wsd-00026-00027 07:13:15.803735 [ prisoner_poll ] WRN  Waking up dead poll thread [docbroker_001], started: true, finished: true| ./net/Socket.hpp:507
wsd-00026-00027 07:13:15.803809 [ prisoner_poll ] WRN  Waking up dead poll thread [docbroker_001], started: false, finished: true| ./net/Socket.hpp:507
wsd-00026-00027 07:13:15.803831 [ prisoner_poll ] WRN  Waking up dead poll thread [docbroker_001], started: false, finished: true| ./net/Socket.hpp:507
wsd-00026-00034 09:25:55.031310 [ websrv_poll ] WRN  WOPI host did not pass optional access_token_ttl| wsd/FileServer.cpp:317
wsd-00026-00043 09:25:59.161378 [ docbroker_002 ] ERR  getWOPIValue: Invalid access: Can not convert empty value.| wsd/Storage.cpp:381
wsd-00026-00043 09:25:59.161440 [ docbroker_002 ] ERR  getWOPIValue: Invalid access: Can not convert empty value.| wsd/Storage.cpp:381
wsd-00026-00043 09:25:59.161484 [ docbroker_002 ] WRN  Missing JSON property [HidePrintOption]| wsd/Storage.cpp:387
wsd-00026-00043 09:25:59.161509 [ docbroker_002 ] WRN  Missing JSON property [HideSaveOption]| wsd/Storage.cpp:387
wsd-00026-00043 09:25:59.161531 [ docbroker_002 ] WRN  Missing JSON property [HideExportOption]| wsd/Storage.cpp:387
wsd-00026-00043 09:25:59.161555 [ docbroker_002 ] WRN  Missing JSON property [EnableOwnerTermination]| wsd/Storage.cpp:387
wsd-00026-00043 09:25:59.161572 [ docbroker_002 ] WRN  Missing JSON property [DisablePrint]| wsd/Storage.cpp:387
wsd-00026-00043 09:25:59.161587 [ docbroker_002 ] WRN  Missing JSON property [DisableExport]| wsd/Storage.cpp:387
wsd-00026-00043 09:25:59.161601 [ docbroker_002 ] WRN  Missing JSON property [DisableCopy]| wsd/Storage.cpp:387
wsd-00026-00043 09:25:59.161621 [ docbroker_002 ] WRN  Missing JSON property [LastModifiedTime]| wsd/Storage.cpp:387
wsd-00026-00043 09:25:59.192382 [ docbroker_002 ] WRN  Attempted ping on non-upgraded websocket!| ./net/WebSocketHandler.hpp:285
wsd-00026-00043 09:26:20.258363 [ docbroker_002 ] WRN  Attempted ping on non-upgraded websocket!| ./net/WebSocketHandler.hpp:285
wsd-00026-00043 09:26:20.258392 [ docbroker_002 ] WRN  Attempted ping on non-upgraded websocket!| ./net/WebSocketHandler.hpp:285
wsd-00026-00043 09:26:40.281547 [ docbroker_002 ] WRN  Attempted ping on non-upgraded websocket!| ./net/WebSocketHandler.hpp:285
wsd-00026-00043 09:26:40.281575 [ docbroker_002 ] WRN  Attempted ping on non-upgraded websocket!| ./net/WebSocketHandler.hpp:285
wsd-00026-00043 09:27:00.304137 [ docbroker_002 ] WRN  Attempted ping on non-upgraded websocket!| ./net/WebSocketHandler.hpp:285
wsd-00026-00043 09:27:00.304166 [ docbroker_002 ] WRN  Attempted ping on non-upgraded websocket!| ./net/WebSocketHandler.hpp:285
wsd-00026-00043 09:27:18.916601 [ docbroker_002 ] WRN  Attempted ping on non-upgraded websocket!| ./net/WebSocketHandler.hpp:285
wsd-00026-00043 09:27:18.916753 [ docbroker_002 ] WRN  Attempted ping on non-upgraded websocket!| ./net/WebSocketHandler.hpp:285
wsd-00026-00043 09:27:40.944348 [ docbroker_002 ] WRN  Attempted ping on non-upgraded websocket!| ./net/WebSocketHandler.hpp:285
wsd-00026-00043 09:27:40.944376 [ docbroker_002 ] WRN  Attempted ping on non-upgraded websocket!| ./net/WebSocketHandler.hpp:285
wsd-00026-00043 09:28:00.968568 [ docbroker_002 ] WRN  Attempted ping on non-upgraded websocket!| ./net/WebSocketHandler.hpp:285
wsd-00026-00043 09:28:00.968597 [ docbroker_002 ] WRN  Attempted ping on non-upgraded websocket!| ./net/WebSocketHandler.hpp:285

**Comment by justinr1234** [comment] 2018-04-02 17:17
Can't believe this just worked, restarting it fixed the problem.

**Comment by dongxiaoyong009** [comment] 2018-11-20 01:20
Can anyone solve this problem? I've tried a lot of versions with this problem? There are so many people in the company these days that I don't want to be sued all the time.

**Comment by juliushaertl** [comment] 2019-01-18 13:16
This is an issue of the CODE docker container. Please report issues related to that to the issue tracker at https://github.com/CollaboraOnline/Docker-CODE

**Closed by juliushaertl** 2019-01-18 13:16 UTC

**Comment by justinr1234** [comment] 2019-01-18 18:31
@juliushaertl What makes you say that, I didn't see anyone root cause this

**Comment by justinr1234** [comment] 2019-02-20 14:44
@juliushaertl Ant update?
