### ISSUE TITLE
Files are modified on the server even if they were not modified in Collabora

### ISSUE THREAD

**Issue by fulax** [nextcloud/richdocuments#2958] opened 2023-05-17 08:46 UTC
**Describe the bug**

Since upgrade (last week) from NC 22 to NC 25 and richdocuments from 4.2.9 to 7.1.3, every time a document is opened then closed, without edit, the LastModificationTime is nonetheless updated on the NC server.

I could reproduce the issue with a second nextcloud installation (slightly behind by a few bugfix updates).

This bug summary is very alike #2771 which has not resolution info. I was able to set the coolwsd log level to info, and get the WOPI::PutFile calls logged, as requested there.

I'm not sure if the issue is in richdocuments, or in collabora online. We upgraded both within a few days.

**To Reproduce**

1. Have an external Collabora Online server (self-hosted)
2. Go to Files
3. Click on a document that should open with Nextcloud Office
4. Click the upright close button
5. Refresh the file listing and observe "last modified a few seconds ago"

**Expected behavior**
I would expect that the modification time is not changed when the document has not been modified. According to our customer, the expected behavior was OK when running NC 22 and richdocuments 4.2.9.

**Screenshots**

**Client details:**
 - OS: Debian Bullseye
 - Browser: Firefox
 - Version: 102.11.0esr
 - Device: Desktop

## Server details

**Operating system:** Debian buster

**Web server:** apache 2.4.38, behind nginx 1.14.2 (tls offloading only)

**Database:** MariaDB 10.3.38-0+deb10u1

**PHP version:** 8.0.28-1+0\~20230409.51+debian10~1.gbp452b35

**Nextcloud version:** 25.0.6 and 25.0.3

**Version of the richdocuments app:** 7.1.3 and 7.1.1

## Collabora server details

**Operating system:**  Debian Bullseye
**Version of Collabora Online:** 22.05.13.1-1 (.deb version), upgraded from 22.05.12.4-1 two weeks ago)
**Setup configuration:** 2 servers behind haproxy loadbalancer, using WOPISrc as routing key

These servers are shared between most of our nextcloud customers, about a hundred nextcloud domains are allowed to use our shared collabora servers. Only a few customers use collabora online, most of them use nextcloud for sharing/storage purposes only.

<details>
<summary>Logs</summary>

#### WOPI log
Excerpt from `journalctl -u coolwsd -f` when closing the document:
```
mai 17 09:53:05 octocollab01 coolwsd[1192870]: wsd-1192870-1193380 2023-05-17 09:53:05.958321 +0200 [ docbroker_002 ] INF  ToClient-060: Disconnected, current global number of connections (inclusive): 2| wsd/ClientSession.cpp:2290
mai 17 09:53:05 octocollab01 coolwsd[1192870]: wsd-1192870-1193380 2023-05-17 09:53:05.958388 +0200 [ docbroker_002 ] INF  Removing session [060] on docKey [/index.php/apps/richdocuments/wopi/files/5133_ocsdrhxdhng5]. Have 1 sessions (1 active). IsLive: true, IsReadOnly: false, IsAllowChangeComments: true, IsEditable: true, Unloading: false, MarkToDestroy: false, LastEditableSession: true, DontSaveIfUnmodified: true, IsPossiblyModified: true| wsd/DocumentBroker.cpp:2508
mai 17 09:53:05 octocollab01 coolwsd[1192870]: wsd-1192870-1193380 2023-05-17 09:53:05.958417 +0200 [ docbroker_002 ] INF  Saving doc [/index.php/apps/richdocuments/wopi/files/5133_ocsdrhxdhng5] using session [060]| wsd/DocumentBroker.cpp:2340
mai 17 09:53:05 octocollab01 coolwsd[1192870]: wsd-1192870-1193380 2023-05-17 09:53:05.959259 +0200 [ docbroker_002 ] INF  ToClient-060: Command: unocommandresult: { "commandName": ".uno:Save", "success": false, "result": { "type": "string", "value": "unmodified"}}| wsd/ClientSession.cpp:1543
mai 17 09:53:05 octocollab01 coolwsd[1192870]: wsd-1192870-1193380 2023-05-17 09:53:05.959473 +0200 [ docbroker_002 ] INF  WOPI::PutFile uploading 77422 bytes from [/opt/cool/child-roots/YLwTyQ0ypNnUPvBr/tmp/user/docs/YLwTyQ0ypNnUPvBr/About (copie).odt.uploading] to URI via WOPI [https://*****.octopuce.fr/index.php/apps/richdocuments/wopi/files/5133_ocsdrhxdhng5/contents?access_token=*****&access_token_ttl=1684345979000]| wsd/Storage.cpp:1265
mai 17 09:53:06 octocollab01 coolwsd[1192870]: wsd-1192870-1193380 2023-05-17 09:53:06.178387 +0200 [ docbroker_002 ] INF  WOPI::PutFile uploaded 77422 bytes in 218ms from [/opt/cool/child-roots/YLwTyQ0ypNnUPvBr/tmp/user/docs/YLwTyQ0ypNnUPvBr/About (copie).odt.uploading] -> [https://*****.octopuce.fr/index.php/apps/richdocuments/wopi/files/5133_ocsdrhxdhng5/contents?access_token=*****&access_token_ttl=1684345979000]: 200 OK: {"LastModifiedTime":"2023-05-17T07:53:06.000000Z"}| wsd/Storage.cpp:1467
mai 17 09:53:06 octocollab01 coolwsd[1192870]: wsd-1192870-1193380 2023-05-17 09:53:06.178682 +0200 [ docbroker_002 ] INF  Finished polling doc [/index.php/apps/richdocuments/wopi/files/5133_ocsdrhxdhng5]. stop: true, continuePolling: true, CloseReason: [unloading], ShutdownRequestFlag: false, TerminationFlag: false| wsd/DocumentBroker.cpp:527
```
</details>

<details>
<summary>coolwsd.xml (save config)</summary>

```xml
<idlesave_duration_secs default="30" desc="The number of idle seconds after which document, if modified, should be saved. Defaults to 30 seconds." type="int">30</idlesave_duration_secs>
<autosave_duration_secs default="300" desc="The number of seconds after which document, if modified, should be saved. Defaults to 5 minutes." type="int">300</autosave_duration_secs>
<always_save_on_exit default="false" desc="On exiting the last editor, always perform the save, even if the document is not modified." type="bool">false</always_save_on_exit>
```

**Comment by joshtrichards** [comment] 2023-11-08 21:12
I think this is a matter in Collabora Online, not here.

It's also possible it's since been addressed - e.g.

https://github.com/CollaboraOnline/online/pull/6167

**Comment by joshtrichards** [comment] 2023-11-08 21:47
Duplicate of #3109 

Sorry also just noticed there's a duplicate issue that current has more participants in it so let's consolidate tracking this situation over there. Feel free to subscribe to #3109 and/or upvote it.

**Closed by joshtrichards** 2023-11-08 21:47 UTC
Labels: bug, upstream: online
