### ISSUE TITLE
Current user is not logged in

### ISSUE THREAD

**Issue by h8h** [nextcloud/richdocuments#1381] opened 2021-02-24 21:37 UTC
**Describe the bug**
With this plugin enabled it is no longer possible to create documents as "public" user. 

**To Reproduce**
1. As an authenticated  user create a new folder
2. Share this folder as link with the following settings: "Allow upload and edit" (I hope my translation is correct)
3. As a public user open this link
4. Click the "+" and create a new document or spreadsheet or presentation
5. Nothing happend
6. Open the web developer tools and look at the console's output: GET https://domain.tld/ocs/v2.php/apps/richdocuments/api/v1/templates/spreadsheet 401: {"ocs":{"meta":{"status":"failure","statuscode":997,"message":"Current user is not logged in"},"data":[]}}

**Expected behavior**
The document gets created. Because an authenticated user can create such a document and the public user can edit it, it should also be possible that an public user can create such an document. 

**Screenshots**
-

**Client details:**
 - Browser Firefox

## Server details

**Nextcloud** version: 20.0.4

**Version of the richdocuments app**  3.7.14

#### Browser log
Insert your browser log here, this could for example include:

a) The javascript console log: see above

**Comment by joshtrichards** [comment] 2023-11-07 14:46
This looks the same as #1581 which was fixed in v5.x. Also I can't reproduce this behavior today (works for me!). I'm going to close this, but please follow-up *if* you still experience this issue.

**Closed by joshtrichards** 2023-11-07 14:46 UTC
Labels: bug, 1. to develop
