### ISSUE TITLE
Internal Server Error - Failed to load external file

### ISSUE THREAD

**Issue by braxyxx** [nextcloud/richdocuments#246] opened 2018-08-23 08:43 UTC
They are a probleme when i try to edit a document share by another user from another server nextcloud.
When i click on it, the document doesn't open and i receive an error.

What i found is that nextcloud failed to GET fileId=322
### Steps to reproduce
1.Receive a share co-edit document from another server
2.Open this document
3.Internal Server Error

### Expected behaviour
The document should have open and I should have been able to edit it.

### Actual behaviour
I receive a Internal Server Error : 
![image](https://user-images.githubusercontent.com/23634608/44518316-381f9a80-a6ca-11e8-9bf3-1ef976a9ba35.png)

### Server configuration

**Operating system**:
 Ubuntu 16.04.5 LTS

**Web server:**

**Database:**
Mariadb
**Nextcloud version:** (see Nextcloud admin page)
Nextcloud 13.0.5
**Updated from an older Nextcloud/ownCloud or fresh install:**
Fresh install
**Where did you install Nextcloud from:**
Install from [https://nextcloud.com/collaboraonline/](url)
Instal with Docker, Image changed to run with proxy traefik : (link to image docker : [https://hub.docker.com/r/remifilament/collaboracode/](url) )

**Error logs **
Collabora error logs --> Nothing
Nextcloud logs --> No Error
Reverse proxy --> No Error
Internet logs : --> ReferenceError: oc_appconfig is not defined

![image](https://user-images.githubusercontent.com/23634608/44515716-939a5a00-a6c3-11e8-825f-bc551416727d.png)

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
``` 
No errors have been found.
</details> 

**List of activated apps:**

<details> 
<summary>App list</summary>
Collabora Online
ONLYOFFICE

### Client configuration
**Browser:**

**Operating system:**

### Logs
####Collabora error log
<details>
<summary>Collabora error log</summary>
```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by juliushaertl** [comment] 2019-01-18 12:39
Duplicate of https://github.com/nextcloud/richdocuments/issues/246

**Closed by juliushaertl** 2019-01-18 12:39 UTC
