### ISSUE TITLE
The richdocuments 3.4.2 version of the App is not compliant

### ISSUE THREAD

**Issue by TP75** [nextcloud/richdocuments#664] opened 2019-10-13 09:53 UTC
**Describe the bug**
On the commandline a `php occ app:check-code richdocuments`shows three (3) errors.  The 3.4.2 version of the **App is not compliant**.

**To Reproduce**
On the commandline execute `sudo -u www-data bash -c ' cd /var/www/nextcloud && php occ app:check-code richdocuments '` or similar.

**Expected behavior**
The 3.4.2 version of the app should pass the check-code analysis without error and the app should be compliant.

**Screenshots**
Output on the Un*x commandline was:

```
$ sudo -u www-data bash -c ' cd /var/www/nextcloud && php occ app:check-code richdocuments '
Nextcloud is in maintenance mode - no apps have been loaded

Analysing /var/www/nextcloud/apps/richdocuments/lib/Controller/DocumentController.php
 1 errors
    line  538: OC_Helper - Static method of private class must not be called
Analysing /var/www/nextcloud/apps/richdocuments/lib/Controller/WopiController.php
 1 errors
    line  332: OC_User - Static method of private class must not be called
Analysing /var/www/nextcloud/apps/richdocuments/appinfo/app.php
 1 errors
    line   53: OC_Helper - Static method of private class must not be called
App is not compliant
```

**Client details:**
_n.a._

## Server details

**Operating system:** Debian 10.1 Buster -- Linux cloudX 4.19.0-6-amd64 #1 SMP Debian 4.19.67-2+deb10u1 (2019-09-20) x86_64 GNU/Linux

**Web server:** apache2-bin/stable,stable,now 2.4.38-3+deb10u1 amd64

**Database:** mariadb-server-10.3/stable,now 1:10.3.17-0+deb10u1 amd64

**PHP version:** php7.3/stable,now 7.3.9-1~deb10u1 all

**Nextcloud version:** 16.0.5.1

**Version of the richdocuments app:** 3.4.2

**Version of Collabora Online:** collabora / code : 4.0.6.1 from docker
DIGEST: 1b53e1119f92

**Comment by juliushaertl** [comment] 2019-10-16 07:43
duplicate of #535

**Closed by juliushaertl** 2019-10-16 07:43 UTC
