### ISSUE TITLE
CODE / richdocuments can't save files (maybe because of redis?)

### ISSUE THREAD

**Issue by artemis-mike** [nextcloud/richdocuments#2001] opened 2022-01-22 15:33 UTC
**Describe the bug**
When editing a document and clicking the floppy-icon and/or using the file-save-menu, the file won't be saved. When closing and reopening the editor, all changes are lost.
Edit: I found out it only won't save files when creating them from one of the templates.

I'm using redis as `memcache.distributed` and I assume that messes with the save-mechanism.

From the `config.php`
```
[...]
'filelocking.enabled' => 'true',
'memcache.local' => '\OC\Memcache\APCu',
'memcache.locking' => ''\OC\Memcache\Redis',
'memcache.distributed' => '\OC\Memcache\Redis',
[...]
 ```

**To Reproduce**
1. Create file
2. Open file
3. Do some changes
4. Click on "Save"-Icon or use File-Save-Menu
5. Change-Indicator in Save-icon won't change
6. Close editor
7. Open editor
8. Changes are lost

**Expected behavior**
I expect the save-icon to save my changes when clicked.

**Client details:**
 - OS: Linux 
 - Browser Brave
 - Version: 1.34.80 Chromium: 97.0.4692.71
 - Device: Desktop

## Server details

**Operating system**: Debian 10 Buster

**Web server:** docker image nextcloud:23.0.0-apache

**Database:** docker image mysql:8.0.23

**PHP version:** 8.0

**Nextcloud version:** 23.0

**Version of the richdocuments app** 5.0.1

**Version of Collabora Online** docker image collabora/code:6.4.11.3

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

</details>

**Comment by Mikeatme** [comment] 2022-01-23 20:15
I found out it only won't save files when creating them from one of the templates.

**Comment by joergmschulz** [comment] 2022-01-24 22:17
Hi, this is a duplicate of #1563 . Allegedly (https://forum.collaboraonline.com/t/collabora-online-weekly-meeting-55/805 ), the fix for this issues is in the pipeline for an interim release. So: you can close this one and keep an eye on #1563

**Closed** 2022-01-28 23:25 UTC
