### ISSUE TITLE
Cannot open XLS/DOC office file on Favorite section

### ISSUE THREAD

**Issue by Bables55** [nextcloud/richdocuments#667] opened 2019-10-16 05:39 UTC
**Describe the bug**
The .xls or .doc format office files shared by other users can't be opened in the Favorites section.
When the user tries to open by desktop PC, the left pane disappears and only the list of favorite files is displayed. *Open on smartphone.

- The file owner can open the file anywhere.
- Other users can be opened if there is no editing authority in the sharing setting.
- Any users can open in the normal file hierarchy.
- xlsx or docs format office files are fine.

**To Reproduce**
1. Prepare an office (1997-2003) format file.
2. Share the file.
3. Allow others to edit.
4. Other user sets the shared file as a favorite.
5. Go to favorite drawer and select favorite menu.
6. Try to open the favorite file by Desktop PC.

**Expected behavior**
Collabora opens as usual.

**Client details:**
 - OS: Windows10 64bit 1903
 - Browser Firefox, Vivaldi
 - Version Firefox 60.9.0(ESR), 69.0.3 / Vivaldi 2.8
 - Device: Desktop

## Server details

**Operating system**:
CentOS 7.7
**Web server:**
Nginx 1.14.2
**Database:**
MariaDB 10.2.27
**PHP version:**
PHP 7.3.10
**Nextcloud version:**
17.0.0
**Version of the richdocuments app**
.4.2
**Version of Collabora Online**
Collabora Office 6.0-29

**Comment by juliushaertl** [comment] 2019-10-21 11:43
duplicate of #630

**Closed by juliushaertl** 2019-10-21 11:43 UTC
