### ISSUE TITLE
"Failed to load Collabora Online Development Edition - please try again later" while using my own server

### ISSUE THREAD

**Issue by BraindeadBZH** [nextcloud/richdocuments#1051] opened 2020-06-23 13:16 UTC
**Describe the bug**
I'm using my own Collabora server on my own NC 19 server, all managed with Docker Compose. I have just updated the App to 3.7.1, since everytime I try to open a ODT file I get the message "Failed to load Collabora Online Development Edition - please try again later" while in the Settings my server is in state "Collabora Online server is reachable."

**To Reproduce**
1. Go to the File app
2. Click on a ODT file
4. See "Failed to load Collabora Online Development Edition - please try again later"

**Expected behavior**
Launching Collabora Online to edit the ODT file.

**Screenshots**
![firefox_sAMTvyL65L](https://user-images.githubusercontent.com/3399852/85406735-81f59800-b562-11ea-835f-0ef5f5215f0d.png)

![firefox_u1qiC1LVfY](https://user-images.githubusercontent.com/3399852/85406987-e1ec3e80-b562-11ea-8f59-8abfa32eb3da.png)

**Client details:**
 - OS: Windows 10
 - Browser: Firefox 
 - Version: 77.0.1
 - Device: Laptop

## Server details

**Operating system**:
Arch Linux

**Web server:**
Nginx

**Database:**
PostgreSQL 12.3

**PHP version:**
PHP 7.4.7

**Nextcloud version:**
19.0.0 fpm-alpine

**Version of the richdocuments app**
3.7.1

**Version of Collabora Online**
Docker collabora/code latest

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
{"reqId":"<REMOVED ID>","level":3,"time":"2020-06-23T12:43:55+00:00","remoteAddr":"<REMOVED IP>","user":"<REMOVED USER>","app":"PHP","method":"POST","url":"/apps/richdocuments/settings/watermark","message":"Undefined index: watermark_text at /var/www/html/custom_apps/richdocuments/lib/Controller/SettingsController.php#237","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:77.0) Gecko/20100101 Firefox/77.0","version":"19.0.0.12"}
```

#### Browser log
```
jQuery is deprecated: The global jQuery is deprecated. It will be updated to v2.4 in Nextcloud 20 and v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. 12 main.js:1020:3628
$ is deprecated: The global jQuery is deprecated. It will be updated to v2.4 in Nextcloud 20 and v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. 21 main.js:1020:3628
jQuery is deprecated: The global jQuery is deprecated. It will be updated to v2.4 in Nextcloud 20 and v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. 8 main.js:1020:3628
$ is deprecated: The global jQuery is deprecated. It will be updated to v2.4 in Nextcloud 20 and v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. 5 main.js:1020:3628
Content Security Policy: Ignoring “'unsafe-inline'” within script-src or style-src: nonce-source or hash-source specified
Content Security Policy: Ignoring ‘x-frame-options’ because of ‘frame-ancestors’ directive.
Content Security Policy: Ignoring “'unsafe-inline'” within script-src or style-src: nonce-source or hash-source specified
Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”). onloadwff.js:71:798525
JQMIGRATE: Migrate is installed, version 1.4.1 main.js:565:531
This page uses the non standard property “zoom”. Consider using calc() in the relevant property values, or using “transform” along with “transform-origin: 0 0”. main.js:251:5836
$ is deprecated: The global jQuery is deprecated. It will be updated to v2.4 in Nextcloud 20 and v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. 3 main.js:1020:3628
Handlebars is deprecated: please ship your own, this will be removed in Nextcloud 20 main.js:1020:3628
$ is deprecated: The global jQuery is deprecated. It will be updated to v2.4 in Nextcloud 20 and v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. 3 main.js:1020:3628
Notifications permissions granted notifications.js:14:337495
jQuery is deprecated: The global jQuery is deprecated. It will be updated to v2.4 in Nextcloud 20 and v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. main.js:1020:3628
$ is deprecated: The global jQuery is deprecated. It will be updated to v2.4 in Nextcloud 20 and v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. 3 main.js:1020:3628
session heartbeat polling started main.js:489:963
$ is deprecated: The global jQuery is deprecated. It will be updated to v2.4 in Nextcloud 20 and v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. 6 main.js:1020:3628
TypeError: Object(...)() is null
document.js:23:103122
jQuery is deprecated: The global jQuery is deprecated. It will be updated to v2.4 in Nextcloud 20 and v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. 20 main.js:1020:3628
$ is deprecated: The global jQuery is deprecated. It will be updated to v2.4 in Nextcloud 20 and v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. 30 main.js:1020:3628
jQuery is deprecated: The global jQuery is deprecated. It will be updated to v2.4 in Nextcloud 20 and v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. 96 main.js:1020:3628
$ is deprecated: The global jQuery is deprecated. It will be updated to v2.4 in Nextcloud 20 and v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. 3 main.js:1020:3628
$ is deprecated: The global jQuery is deprecated. It will be updated to v2.4 in Nextcloud 20 and v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. 132 main.js:1020:3628
jQuery is deprecated: The global jQuery is deprecated. It will be updated to v2.4 in Nextcloud 20 and v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. 3 main.js:1020:3628
$ is deprecated: The global jQuery is deprecated. It will be updated to v2.4 in Nextcloud 20 and v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. 8 main.js:1020:3628
jQuery is deprecated: The global jQuery is deprecated. It will be updated to v2.4 in Nextcloud 20 and v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. 96 main.js:1020:3628
```

</details>

**Comment by juliushaertl** [comment] 2020-06-23 14:38
Duplicate of #1050 Fix pending in #1052

**Closed by juliushaertl** 2020-06-23 14:38 UTC
