### ISSUE TITLE
Nextcloud 15 "grid view" widget  overlaps the collabora close button.

### ISSUE THREAD

**Issue by rev138** [nextcloud/richdocuments#328] opened 2018-12-15 14:01 UTC
### Steps to reproduce
1. Install Nextcloud 15.0.0 with richdocuments
2. Open a document in Collabora Online

### Expected behaviour
The button to close the document in the upper right should be clickable.

### Actual behaviour
It's covered by the Nextcloud "grid view" widget, which also happens to be inapplicable in this app.

### Server configuration

**Operating system**: debian 9
**Web server:** nginx
**Database:** mariadb
**PHP version:** 7.2
**Nextcloud version:** 15.0.0
**Browser:** Firefox 63.0.3

![screenshot from 2018-12-15 08-53-30](https://user-images.githubusercontent.com/1538633/50043751-e1a6e500-0047-11e9-8e3d-b508cd163a9d.png)

**Comment by timar** [comment] 2018-12-15 14:49
Dupe of #317.

**Closed by timar** 2018-12-15 14:49 UTC
