### ISSUE TITLE
Can't activate

### ISSUE THREAD

**Issue by Dynag** [nextcloud/richdocuments#601] opened 2019-09-06 08:04 UTC
Hi,

I can't acivate Collabora. I have the last version of docker collabora, nextcloud.
When I am trying to activate it,  I got this error :

no app in context | OCP\AppFramework\QueryException: Could not resolve OCA\Federation\TrustedServers! Class OCA\Federation\TrustedServers does not exist/var/www/html/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php - line 119: OC\AppFramework\Utility\SimpleContainer->resolve("OCA\\Federa ... s")/var/www/html/nextcloud/lib/private/ServerContainer.php - line 150: OC\AppFramework\Utility\SimpleContainer->query("OCA\\Federa ... s")/var/www/html/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php - line 385: OC\ServerContainer->query("OCA\\Federa ... s")/var/www/html/nextcloud/apps/richdocuments/lib/AppInfo/Application.php - line 111: OC\AppFramework\DependencyInjection\DIContainer->query("OCA\\Federa ... s")/var/www/html/nextcloud/apps/richdocuments/appinfo/app.php - line 66: OCA\Richdocuments\AppInfo\Application->updateCSP("*** sensiti ... *")/var/www/html/nextcloud/lib/private/legacy/app.php - line 262: require_once("/var/www/ht ... p")/var/www/html/nextcloud/lib/private/legacy/app.php - line 155: OC_App::requireAppFile(OCA\Richdocu ... {})/var/www/html/nextcloud/lib/private/legacy/app.php - line 128: OC_App::loadApp("richdocuments")/var/www/html/nextcloud/apps/dav/appinfo/app.php - line 30: OC_App::loadApps([ "dav"])/var/www/html/nextcloud/lib/private/legacy/app.php - line 262: require_once("/var/www/ht ... p")/var/www/html/nextcloud/lib/private/legacy/app.php - line 155: OC_App::requireAppFile("dav")/var/www/html/nextcloud/lib/private/legacy/app.php - line 128: OC_App::loadApp("dav")/var/www/html/nextcloud/lib/private/legacy/util.php - line 196: OC_App::loadApps([ "filesystem"])/var/www/html/nextcloud/lib/private/Files/Filesystem.php - line 266: OC_Util::setupFS("")/var/www/html/nextcloud/lib/private/Server.php - line 291: OC\Files\Filesystem::getMountManager(null)/var/www/html/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php - line 118: OC\Server->OC\{closure}("*** sensiti ... *")/var/www/html/nextcloud/lib/private/ServerContainer.php - line 125: Pimple\Container->offsetGet("RootFolder")/var/www/html/nextcloud/lib/private/Server.php - line 313: OC\ServerContainer->query("RootFolder")<<closure>>OC\Server->OC\{closure}("*** sensiti ... *")/var/www/html/nextcloud/lib/private/Files/Node/LazyRoot.php - line 61: call_user_func(Closure {})/var/www/html/nextcloud/lib/private/Files/Node/LazyRoot.php - line 78: OC\Files\Node\LazyRoot->__call("listen", [ "\\OC\\Fil ... }])/var/www/html/nextcloud/apps/carnet/appinfo/app.php - line 45: OC\Files\Node\LazyRoot->listen("\\OC\\Files", "postWrite", Closure {})/var/www/html/nextcloud/apps/carnet/appinfo/app.php - line 59: OCA\Carnet\AppInfo\Application->connectWatcher(OC\AppFramew ... {})/var/www/html/nextcloud/lib/private/legacy/app.php - line 262: require_once("/var/www/ht ... p")/var/www/html/nextcloud/lib/private/legacy/app.php - line 155: OC_App::requireAppFile(OCA\Carnet\A ... {})/var/www/html/nextcloud/lib/private/legacy/app.php - line 128: OC_App::loadApp("carnet")/var/www/html/nextcloud/lib/base.php - line 960: OC_App::loadApps()/var/www/html/nextcloud/index.php - line 42: OC::handleRequest()
-- | --

**Comment by juliushaertl** [comment] 2019-09-06 08:34
duplicate of #592

**Closed by juliushaertl** 2019-09-06 08:34 UTC
