### ISSUE TITLE
Endless Loading Icon

### ISSUE THREAD

**Issue by a1pilot** [nextcloud/richdocuments#450] opened 2019-03-12 22:33 UTC
**Describe the bug**
When selecting an ods file in Nextcloud, it starts to load but gets stuck on the spinning wheel.

Debian server with Apache2 proxy.

I can access: https://office.xxxxxxxxx.uk/hosting/discovery and see the xml, so the container and redirect is running by the look of it.

No errors thrown anywhere.

**To Reproduce**
Click on any document in Nextcloud.  Watch the wheel spin.

**Expected behavior**
Document opens in editor.

## Server details

**Operating system**: Debian Buster

**Web server:** Apache2

**Database:** MariaDB

**PHP version:** 7.3

**Nextcloud version:** 15.0.5

**Version of the richdocuments app:** 3.2.3

**Version of Collabora Online:** Pulled from the latest docker, 12th March 2019.

<details>
<summary>Logs</summary>

No errors, no log entries.

</details>

**Comment by juliushaertl** [comment] 2019-03-18 10:37
Can you also access office.xxxxxxxxx.uk/hosting/capabilities?

**Comment by thebearon** [comment] 2019-03-18 18:49
Are there any errors (of log level ERR) in the container's logs?

**Comment by a1pilot** [comment] 2019-03-18 19:45
@thebearon How do I view them?

@juliushaertl I'll run it up and check.

**Comment by thebearon** [comment] 2019-03-18 21:11
@a1pilot [docker logs CONTAINER](https://docs.docker.com/engine/reference/commandline/logs/)

**Comment by a1pilot** [comment] 2019-03-19 20:23
@juliushaertl I get {"convert-to":{"available":false},"hasMobileSupport":true,"hasTemplateSaveAs":true}

**Comment by a1pilot** [comment] 2019-03-19 20:31
@thebearon 

`wsd-00029-00039 2019-03-19 20:27:18.434307 [ websrv_poll ] ERR  Requesting address is denied: ::ffff:172.17.0.1| wsd/LOOLWSD.cpp:1971
wsd-00029-00039 2019-03-19 20:27:21.507046 [ websrv_poll ] ERR  Requesting address is denied: ::ffff:172.17.0.1| wsd/LOOLWSD.cpp:1971
wsd-00029-00061 2019-03-19 20:27:33.157777 [ docbroker_006 ] ERR  Cannot get file info from WOPI storage uri [https://cloud.xxxxxx.uk/index.php/apps/richdocuments/wopi/files/636240_ocs9dprf147k?access_token=zMQVjQsNuRtYnxZuzpaeQSwrpqUalZsw&access_token_ttl=0&permission=edit]. Error: DNS error: Temporary DNS error while resolving: cloud.xxxxxx.uk| wsd/Storage.cpp:474
wsd-00029-00061 2019-03-19 20:27:33.158090 [ docbroker_006 ] ERR  Failed to add session to [/index.php/apps/richdocuments/wopi/files/636240_ocs9dprf147k] with URI [https://cloud.xxxxxx.uk/index.php/apps/richdocuments/wopi/files/636240_ocs9dprf147k?access_token=zMQVjQsNuRtYnxZuzpaeQSwrpqUalZsw&access_token_ttl=0&permission=edit]: DNS error| wsd/DocumentBroker.cpp:1091
wsd-00029-00061 2019-03-19 20:27:33.158267 [ docbroker_006 ] ERR  Error while loading : DNS error| wsd/LOOLWSD.cpp:2674
wsd-00029-00061 2019-03-19 20:27:33.158551 [ docbroker_006 ] WRN  Will not load document marked to destroy. DocKey: [/index.php/apps/richdocuments/wopi/files/636240_ocs9dprf147k].| wsd/DocumentBroker.cpp:463
wsd-00029-00061 2019-03-19 20:27:33.158656 [ docbroker_006 ] ERR  Failed to load document with URI [https://cloud.xxxxxx.uk/index.php/apps/richdocuments/wopi/files/636240_ocs9dprf147k?access_token=wnHUhRVMYuBLyR21pQwOg5Ks5uv7fHi1&access_token_ttl=0&permission=edit].| wsd/DocumentBroker.cpp:1112
wsd-00029-00061 2019-03-19 20:27:33.158826 [ docbroker_006 ] ERR  Failed to add session to [/index.php/apps/richdocuments/wopi/files/636240_ocs9dprf147k] with URI [https://cloud.xxxxxx.uk/index.php/apps/richdocuments/wopi/files/636240_ocs9dprf147k?access_token=wnHUhRVMYuBLyR21pQwOg5Ks5uv7fHi1&access_token_ttl=0&permission=edit]: Failed to load document with URI [https://cloud.xxxxxx.uk/index.php/apps/richdocuments/wopi/files/636240_ocs9dprf147k?access_token=wnHUhRVMYuBLyR21pQwOg5Ks5uv7fHi1&access_token_ttl=0&permission=edit].| wsd/DocumentBroker.cpp:1091
wsd-00029-00061 2019-03-19 20:27:33.158965 [ docbroker_006 ] ERR  Error while loading : Failed to load document with URI [https://cloud.xxxxxx.uk/index.php/apps/richdocuments/wopi/files/636240_ocs9dprf147k?access_token=wnHUhRVMYuBLyR21pQwOg5Ks5uv7fHi1&access_token_ttl=0&permission=edit].| wsd/LOOLWSD.cpp:2674
wsd-00029-00061 2019-03-19 20:27:33.159387 [ docbroker_006 ] WRN  Child session [003e] not found to forward message: load url=https://cloud.xxxxxx.uk/index.php/apps/richdocuments/wopi/files/636240_ocs9dprf147k?access_token=zMQVjQsNuRtYnxZuzpaeQSwrpqUalZsw&access_token_ttl=0&permission=edit readonly=0 lang=en-GB| wsd/DocumentBroker.cpp:1736
wsd-00029-00061 2019-03-19 20:27:33.159689 [ docbroker_006 ] WRN  Child session [0039] not found to forward message: load url=https://cloud.xxxxxx.uk/index.php/apps/richdocuments/wopi/files/636240_ocs9dprf147k?access_token=zMQVjQsNuRtYnxZuzpaeQSwrpqUalZsw&access_token_ttl=0&permission=edit readonly=0 lang=en-GB| wsd/DocumentBroker.cpp:1736
wsd-00029-00061 2019-03-19 20:27:33.160219 [ docbroker_006 ] ERR  Invalid or unknown session [0039] to remove.| wsd/DocumentBroker.cpp:1160
wsd-00029-00061 2019-03-19 20:27:34.159921 [ docbroker_006 ] ERR  Invalid or unknown session [003e] to remove.| wsd/DocumentBroker.cpp:11601m33
mkit-00058-00031 2019-03-19 20:27:34.159900 [ loolkit ] WRN  Kit connection lost without exit arriving from wsd. Setting TerminationFlag| kit/Kit.cpp:2218
wsd-00029-00061 2019-03-19 20:27:34.160069 [ docbroker_006 ] ERR  No socket associated with WebSocketHandler 0x7f78240010b0| ./net/WebSocketHandler.hpp:108
wsd-00029-00030 2019-03-19 20:27:34.160309 [ prisoner_poll ] WRN  Prisoner connection disconnected but without valid socket.| wsd/LOOLWSD.cpp:1776`

**Comment by a1pilot** [comment] 2019-03-21 19:45
Upgraded to latest docker image.  Disabled ipv6 with --dns-opt='options single-request' option on load.  No change.

**Comment by kousu** [comment] 2019-03-22 19:18
I just upgraded today and am seeing this problem too. I have NextCloud 15.0.5, richdocuments 3.2.4, and CODE is 4.0.2.

Here's the log of `systemctl restart loolwsd` followed by trying to open a .xlsx document within NextCloud:

[loolwsd.log](https://github.com/nextcloud/richdocuments/files/2997960/loolwsd.log)

My configs are:

Here's nginx:

[nginx.txt](https://github.com/nextcloud/richdocuments/files/2997968/nginx.txt)

Here's loolwsd.xml:

[loolwsd.xml](https://github.com/nextcloud/richdocuments/files/2997970/loolwsd.xml.txt)

I'm running it SSL-terminated (by nginx), following the guide on https://wiki.archlinux.org/index.php/Nextcloud#Collabora_Online_Office_integration. I've tried adding and removing various server_names in various places but no luck so far.

It keeps shutting down the socket almost immediately with no explanation:

```
Mar 22 14:59:25 server.example.com loolwsd[1909]: wsd-01909-01919 2019-03-22 18:59:25.880451 [ websrv_poll ] TRC  #20: Incoming data buffer 142 bytes, closeSocket? false| ./net/Socket.hpp:986
Mar 22 14:59:25 server.example.com loolwsd[1909]: wsd-01909-01919 2019-03-22 18:59:25.880492 [ websrv_poll ] TRC  #20 handling incoming 142 bytes.| net/Socket.cpp:440
Mar 22 14:59:25 server.example.com loolwsd[1909]: wsd-01909-01919 2019-03-22 18:59:25.880577 [ websrv_poll ] DBG  Wopi discovery request: /hosting/discovery| wsd/LOOLWSD.cpp:2230
Mar 22 14:59:25 server.example.com loolwsd[1909]: wsd-01909-01919 2019-03-22 18:59:25.880760 [ websrv_poll ] TRC  #20: Wrote outgoing data 16384 bytes.| ./net/Socket.hpp:1053
Mar 22 14:59:25 server.example.com loolwsd[1909]: wsd-01909-01919 2019-03-22 18:59:25.880787 [ websrv_poll ] TRC  #20: Wrote outgoing data 3329 bytes.| ./net/Socket.hpp:1053
Mar 22 14:59:25 server.example.com loolwsd[1909]: wsd-01909-01919 2019-03-22 18:59:25.880801 [ websrv_poll ] TRC  #20: Async shutdown requested.| ./net/Socket.hpp:819
Mar 22 14:59:25 server.example.com loolwsd[1909]: wsd-01909-01919 2019-03-22 18:59:25.880810 [ websrv_poll ] INF  Sent discovery.xml successfully.| wsd/LOOLWSD.cpp:2250
Mar 22 14:59:25 server.example.com loolwsd[1909]: wsd-01909-01919 2019-03-22 18:59:25.880827 [ websrv_poll ] TRC  #20: socket shutdown RDWR.| ./net/Socket.hpp:146
Mar 22 14:59:25 server.example.com loolwsd[1909]: wsd-01909-01919 2019-03-22 18:59:25.880841 [ websrv_poll ] TRC  #20: Closed. Firing onDisconnect.| ./net/Socket.hpp:1027
Mar 22 14:59:25 server.example.com loolwsd[1909]: wsd-01909-01919 2019-03-22 18:59:25.880888 [ websrv_poll ] DBG  Removing socket #20 (of 1) from websrv_poll| ./net/Socket.hpp:577
Mar 22 14:59:25 server.example.com loolwsd[1909]: wsd-01909-01919 2019-03-22 18:59:25.880898 [ websrv_poll ] DBG  StreamSocket dtor #20| ./net/Socket.hpp:796
Mar 22 14:59:25 server.example.com loolwsd[1909]: wsd-01909-01919 2019-03-22 18:59:25.880905 [ websrv_poll ] TRC  #20 Socket dtor.| ./net/Socket.hpp:116
```

**Comment by kousu** [comment] 2019-03-22 20:08
asdfasdfasfa

It's cleared up on me. I didn't change the configs at all. What I did do was `systemctl stop loolwsd; sleep 30; systemctl start loolwsd` instead of `systemctl restart loolwsd`. After that it started working.  Maybe it had cached a bad copy of the javascript? Maybe the javascript is dynamically generated to include the host allowlist? Why do daemons pretend to restart when they aren't actually restarting?

But I had a new problem. I can load documents, but if I try to make an edit my websocket connection drops and it says "Nick has left" "Nick has joined". I'll look into that and make a new bug report if I get anywhere.

**Comment by thebearon** [comment] 2019-03-22 22:52
> But I had a new problem. I can load documents, but if I try to make an edit my websocket connection drops and it says "Nick has left" "Nick has joined". I'll look into that and make a new bug report if I get anywhere.

Install a dictionary, eg. collaboraoffice6.0-dict-en, that should solve the problem. An update is coming in a few days.

**Comment by thebearon** [comment] 2019-03-22 22:55
> Upgraded to latest docker image. Disabled ipv6 with --dns-opt='options single-request' option on load. No change.

Any idea what this might be caused by: "Error: DNS error: Temporary DNS error while resolving: cloud.xxxxxx.uk"? Is there really a DNS resolution issue inside the docker?

**Closed** 2019-04-28 23:35 UTC
Labels: info needed, wontfix

**Comment by kousu** [comment] 2019-05-05 08:27
this is definitely not stale! I just and the same looping "Nick has left" behaviour is back. `systemctl stop loolwsd; sleep 30; systemctl start loolwsd` did not fix it like I thought it might.

I finally found some time to trace my second other bug after upgrading again (`pacman -Syu`!) to 16.0.0. On pressing any button with a document open, this pops up in the logs:
```
May 05 04:04:16 office.example.net loolwsd[6568]: kit-07400-07403 2019-05-05 08:04:16.924237 [ lo_startmain ] SIG   Fatal signal received: SIGABRT
May 05 04:04:16 office.example.net loolwsd[6568]: Backtrace 7400:
May 05 04:04:16 office.example.net loolwsd[6568]: /usr/bin/loolforkit(_ZN7SigUtil13dumpBacktraceEv+0x5f) [0x4b3d1f]
May 05 04:04:16 office.example.net loolwsd[6568]: /usr/bin/loolforkit() [0x4b4e60]
May 05 04:04:16 office.example.net loolwsd[6568]: /usr/lib/libpthread.so.0(+0x124d0) [0x7fd1f7cd04d0]
May 05 04:04:16 office.example.net loolwsd[6568]: /usr/lib/libc.so.6(gsignal+0x10f) [0x7fd1f7b3082f]
May 05 04:04:16 office.example.net loolwsd[6568]: /usr/lib/libc.so.6(abort+0x125) [0x7fd1f7b1b672]
May 05 04:04:16 office.example.net loolwsd[6568]: /opt/collaboraoffice6.0/program/libmergedlo.so(_ZN16SalUserEventList18DispatchUserEventsEb+0x39c) [0x7fd1f5de333c]
May 05 04:04:16 office.example.net loolwsd[6568]: /opt/collaboraoffice6.0/program/libmergedlo.so(_ZN14SvpSalInstance7DoYieldEbb+0x39) [0x7fd1f5e8f239]
May 05 04:04:16 office.example.net loolwsd[6568]: /opt/collaboraoffice6.0/program/libmergedlo.so(_ZN11Application5YieldEv+0x2e) [0x7fd1f5df451e]
May 05 04:04:16 office.example.net loolwsd[6568]: /opt/collaboraoffice6.0/program/libmergedlo.so(_ZN11Application7ExecuteEv+0x45) [0x7fd1f5df5e15]
May 05 04:04:16 office.example.net loolwsd[6568]: /opt/collaboraoffice6.0/program/libmergedlo.so(+0x1f0f70c) [0x7fd1f4dc470c]
May 05 04:04:16 office.example.net loolwsd[6568]: /opt/collaboraoffice6.0/program/libmergedlo.so(+0x2f467c6) [0x7fd1f5dfb7c6]
May 05 04:04:16 office.example.net loolwsd[6568]: /opt/collaboraoffice6.0/program/libmergedlo.so(_Z6SVMainv+0x22) [0x7fd1f5dfb8b2]
May 05 04:04:16 office.example.net loolwsd[6568]: /opt/collaboraoffice6.0/program/libmergedlo.so(soffice_main+0x8a) [0x7fd1f4de40ea]
May 05 04:04:16 office.example.net loolwsd[6568]: /opt/collaboraoffice6.0/program/libmergedlo.so(+0x1f3edd1) [0x7fd1f4df3dd1]
May 05 04:04:16 office.example.net loolwsd[6568]: /opt/collaboraoffice6.0/program/libuno_sal.so.3(+0x40ea7) [0x7fd1ef7bfea7]
May 05 04:04:16 office.example.net loolwsd[6568]: /usr/lib/libpthread.so.0(+0x7a92) [0x7fd1f7cc5a92]
May 05 04:04:16 office.example.net loolwsd[6568]: /usr/lib/libc.so.6(clone+0x43) [0x7fd1f7bf3cd3]
```

From @thebearon's clue, I rebuilt https://aur.archlinux.org/packages/collabora-online-server-nodocker and reinstalled, and the problem cleared up immediately. I didn't even need to restart `loolwsd`. I was at 4.0.2. Now I'm at 4.0.3. I don't know what fix you guys did but it looks like it worked for me! Thank you very much.
