### ISSUE TITLE
"Failed to create DocBroker with docKey" When Trying to Open Specific ODS

### ISSUE THREAD

**Issue by gohrner** [nextcloud/richdocuments#523] opened 2019-05-29 14:37 UTC
**Describe the bug**
We have an ODS file which cannot be opened in CODE any more (this morning, it worked still fine).

If I click the file, the NextCloud spinner is shown for a while before the file listing re-appears and an error message bubble at the top of the window "Fehler beim Verbinden mit Collabora Online Development Edition. Bitte versuchen Sie es noch einmal oder kontaktieren Sie Ihren Administrator." ("Error connecting to Collabora Online Development Edition. Please try again or contact your administrator.")

On the CODE machine, I get the following in the logs:

```
wsd-00030-00039` 2019-05-29 14:23:44.711949 [ websrv_poll ] ERR  Error while handling Client WS Request: Failed to create DocBroker with docKey [/apps/richdocuments/wopi/files/1292289_ocvgcqniu1rh].| wsd/LOOLWSD.cpp:2698
wsd-00030-00039 2019-05-29 14:23:45.781096 [ websrv_poll ] WRN  DocBroker with docKey [/apps/richdocuments/wopi/files/1292289_ocvgcqniu1rh] that is marked to be destroyed. Rejecting client request.| wsd/LOOLWSD.cpp:1674
```

This repeats a few times and stops when the error message appears in NextCloud.

There is nothing related in the NextCloud logs.

The file opens fine with Desktop Libre Office and also opens fine with CODE if copied to another name in the same directory (synced using the NX Desktop client) or copied to another directory via the NX Web Interface.

Renaming the original file in NextCloud does not help, it still cannot be opened.

How to debug this?

**Client details:**
 - OS: Ubuntu 18.04
 - Browser Chrome
 - Version Version 73.0.3683.86 (Offizieller Build) Built on Ubuntu
 - Device: x64 notebook

## Server details

**Operating system**: Debian 9 Stretch

**Web server:** Apache 2.4

**Database:** MariaDB

**PHP version:** 7.0.33

**Nextcloud version:** 15.0.8

**Version of the richdocuments app** 3.3.6 (latest released at the time of this writing)

**Version of Collabora Online** 4.0.4

**Comment by thebearon** [comment] 2019-05-30 00:24
Have you checked the admin console if there is a stuck session somehow?

**Comment by gohrner** [comment] 2019-05-30 09:36
No, I didn't, I didn't know there could be such a thing like a "stuck session" and that it might be related.

I did check now, and actually there is a session shown which is open since 22 hours now for the affected file. I'm not entirely sure that it's really for the affected file, as meanwhile I copied the file in question to a new name, deleted the non-working one and renamed the copy to the original name, so it also *could* possibly be an open session already for the new file. However, I think it's too old and probably stems from before the copy-renaming-workaround - so most likely it's the culprit.

How can "stuck sessions" happen and what can I do about it?

I already had a look at the Troubleshooting section at https://nextcloud.com/collaboraonline/ , but it does not mention anything related. Also Google does not seem to know anything about 'Collabora CODE "stuck session"'.
I can see the session in the admin panel, but I could not find any way to remove / terminate it there.

Also, how can I avoid this happening in the future?

**Comment by gohrner** [comment] 2019-05-30 11:11
Ok, after a restart of the CODE Docker container, the stale / stuck session is gone. Due to the workaround described above which I already made yesterday, I cannot test whether this would have helped, though.

I'm still curious how / why this did happen, and how to avoid it in the future...

**Comment by juliushaertl** [comment] 2019-07-01 09:30
I'll close this for now. @gohrner Feel free to reopen if it occurs again so we can have a look then on how to get more details to find the root cause.

**Closed by juliushaertl** 2019-07-01 09:30 UTC
Labels: wontfix

**Comment by lazka** [comment] 2019-07-09 23:14
Same issue. After I click the "Insert Special Character" button then nothing happens and I can no longer edit the document. After leaving the document it fails to reopen it forever.

**Comment by thebearon** [comment] 2019-07-10 00:09
@lazka that's a completely different issue, and is tracked in [tdf#125681](https://bugs.documentfoundation.org/show_bug.cgi?id=125681).

**Comment by lazka** [comment] 2019-07-10 07:11
OK, thanks. I just thought I'd mention it here since it produces the same exact error in the logs when trying to open a document.

**Comment by unteem** [comment] 2020-03-04 14:07
Hi facing the same issue here. I get the same error than @gohrner. 

We are running latest collabora-code, NC16 and richdocument 3.5.1

Sometimes, when a user tries to access a document it is not loading and ends up with a grey screen. This document is then not accessible anymore for anyone.

I can see the user with an inactive session on the admin interface, the session never gets closed even after idle timeout unless the process is manually killed.

In the browser console I get a timeout error. 

I have not been able to find a pattern in this, hard to replicate :/

Maybe you have some ideas.

Thanks
