### ISSUE TITLE
macOS - Primary Color becomes dark

### ISSUE THREAD

**Issue by Ezinnem** [nextcloud/richdocuments#2929] opened 2023-04-27 12:07 UTC
**Describe the bug**

The primary colour looks darker on macOS than on Linux.
See the screenshot in macOS:

![Screenshot 2023-04-27 at 14 53 27](https://user-images.githubusercontent.com/54344301/234851397-c814f4b4-1f2c-4d3c-b825-707700468e5d.png)

Screenshot on Linux:
![Screenshot from 2023-04-27 13-04-43](https://user-images.githubusercontent.com/54344301/234856674-d7100eab-6767-44d3-9301-01684ab80be4.png)

**To Reproduce**
1. on MacOS, Open a file using Collabora Online on Nextcloud Integration.
2. Select any text and click on Bold, see that the color is darker.

**Expected behavior**
The color should not be darker

**Actual behavior**
The colour is darker

**Screenshots**
See the screenshot in macOS:

![Screenshot 2023-04-27 at 14 53 27](https://user-images.githubusercontent.com/54344301/234851397-c814f4b4-1f2c-4d3c-b825-707700468e5d.png)

Screenshot on Linux:

![Screenshot from 2023-04-27 13-04-43](https://user-images.githubusercontent.com/54344301/234856674-d7100eab-6767-44d3-9301-01684ab80be4.png)

**Comment by Ezinnem** [comment] 2023-04-28 19:12
@pedropintosilva

**Comment by juliushaertl** [comment] 2023-05-02 10:41
Can you tell which version of Nextcloud and the richdocuments app and which browser on mac os was in use? Should actually be fixed by https://github.com/nextcloud/richdocuments/pull/2550

**Comment by juliushaertl** [comment] 2023-05-02 10:43
Also what is the current state of your operating system settings for dark mode and did you adjust the accessibility/appearance settings in Nextcloud manually for your user?

I cannot reproduce this with Safari on Nextcloud 26 at least:

![Screenshot 2023-05-02 at 12 43 12](https://user-images.githubusercontent.com/3404133/235645784-c0befc49-d2d5-48ae-a4e4-faa158356ad7.png)

**Comment by pedropintosilva** [comment] 2023-05-02 11:15
this was on staging.eu.collaboraonline.com/nextcloud/ nextcloud office 7.1.3

**Comment by pedropintosilva** [comment] 2023-05-02 11:19
@juliushaertl says that is is likely a caching problem and we should probably set 'debug' => false, in config.php for staging eu @timar

**Comment by juliushaertl** [comment] 2023-05-02 11:20
Likely that this is an outdated browser cache due to the debug mode.

debug mode is only for development purposes, 'loglevel' => 0, is more what you want if you need verbose logging on a semi-productive instance (or anything that is non-local)

**Closed** 2023-05-03 18:17 UTC
