### ISSUE TITLE
"New Documents" from template causes strange behaviour in editor

### ISSUE THREAD

**Issue by gohrner** [nextcloud/richdocuments#367] opened 2019-01-25 08:49 UTC
### Steps to reproduce
(Do not save during those steps.)
1.Create new document in NextCloud
2. Select the "empty" template (if not template is selected, the process crashes, but this already has been reported here as a separate bug)

### Expected behaviour
The editor opens, but with limited feature set. E.g. only two font sizes are available in the drop down list.
If you save and reopen the document, it works normally.

### Actual behaviour
The editor should behave as if the document had been opened normally.

## Server configuration detail

**Operating system:** Linux 4.9.0-8-amd64 #1 SMP Debian 4.9.130-2 (2018-10-27) x86_64

**Webserver:** Apache/2.4.25 (Debian) (apache2handler)

**Database:** mysql 10.1.37

**PHP version:** 

7.0.33-0+deb9u1
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, apache2handler, mysqlnd, PDO, xml, apcu, apc, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, igbinary, imagick, imap, intl, json, ldap, exif, mcrypt, mysqli, pdo_mysql, Phar, posix, readline, recode, redis, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Zend OPcache

**Nextcloud version:** 14.0.4 - 14.0.4.2

**Updated from an older Nextcloud/ownCloud or fresh install:** 

**Where did you install Nextcloud from:** unknown

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.0.1
 - activity: 2.7.0
 - apporder: 0.6.0
 - calendar: 1.6.4
 - cloud_federation_api: 0.0.1
 - comments: 1.4.0
 - contacts: 2.1.8
 - dav: 1.6.0
 - external: 3.1.0
 - federatedfilesharing: 1.4.0
 - federation: 1.4.0
 - files: 1.9.0
 - files_pdfviewer: 1.3.2
 - files_sharing: 1.6.2
 - files_texteditor: 2.6.0
 - files_trashbin: 1.4.1
 - files_versions: 1.7.1
 - files_videoplayer: 1.3.0
 - firstrunwizard: 2.3.0
 - gallery: 18.1.0
 - impersonate: 1.1.0
 - issuetemplate: 0.4.0
 - logreader: 2.0.0
 - lookup_server_connector: 1.2.0
 - mail: 0.11.0
 - nextcloud_announcements: 1.3.0
 - notes: 2.5.1
 - notifications: 2.2.1
 - oauth2: 1.2.1
 - password_policy: 1.4.0
 - polls: 0.9.5
 - provisioning_api: 1.4.0
 - richdocuments: 3.1.1
 - serverinfo: 1.4.0
 - sharebymail: 1.4.0
 - socialsharing_email: 1.0.5
 - spreed: 4.0.2
 - support: 1.0.0
 - survey_client: 1.2.0
 - systemtags: 1.4.0
 - tasks: 0.9.8
 - theming: 1.5.0
 - twofactor_backupcodes: 1.3.1
 - updatenotification: 1.4.1
 - user_ldap: 1.4.0
 - workflowengine: 1.4.0
Disabled:
 - admin_audit
 - circles
 - encryption
 - files_external
 - user_external

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "nextcloud.ohrner-it.com"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "overwrite.cli.url": "https:\/\/nextcloud.ohrner-it.com",
    "htaccess.RewriteBase": "\/",
    "dbtype": "mysql",
    "version": "14.0.4.2",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "ldapIgnoreNamingRules": false,
    "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpmode": "sendmail",
    "mail_smtpauthtype": "LOGIN",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "maintenance": false,
    "theme": "",
    "loglevel": 2,
    "app.mail.accounts.default": {
        "email": "%USERID%@ohrner-it.com",
        "imapHost": "luggage.ohrner.net",
        "imapPort": 993,
        "imapUser": "%USERID%",
        "imapSslMode": "ssl",
        "smtpHost": "luggage.ohrner.net",
        "smtpPort": 465,
        "smtpUser": "%USERID%",
        "smtpSslMode": "ssl"
    },
    "auth.bruteforce.protection.enabled": true,
    "memcache.local": "\\OC\\Memcache\\APCu",
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": 6379
    },
    "updater.release.channel": "production",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***"
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** 

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

<details><summary>LDAP configuration (delete this par if not used)</summary>

```
(too much personal detail here)
```
</details>

## Client configuration

**Browser:** Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/71.0.3578.98 Chrome/71.0.3578.98 Safari/537.36

**Operating system:** Debian GNU/Linux 9 Stretch

**Comment by juliushaertl** [comment] 2019-02-11 14:25
I cannot reproduce this issue, can you try again with the latest collabora and richdocuments version?

**Comment by thebearon** [comment] 2019-02-11 14:50
This was fixed by the following commit in Collabora Online, and will be part of 4.0.0 release: [3c9efeaad21159c11b43af614907ef9e5ddc6a61](https://cgit.freedesktop.org/libreoffice/online/commit/?h=distro/collabora/collabora-online-4&id=3c9efeaad21159c11b43af614907ef9e5ddc6a61)

**Closed by thebearon** 2019-02-11 14:50 UTC
Labels: question
