### ISSUE TITLE
Group Folder + Collabora Online = Not working

### ISSUE THREAD

**Issue by poisony** [nextcloud/richdocuments#70] opened 2017-05-24 15:44 UTC
As the title says. If you make a group folder and then create a New Document, Spreadsheet or Presentation you can't save/edit the document.

**Comment by thebearon** [comment] 2017-05-25 13:20
By group folder you mean a folder that is shared with a group rather than a single user, right?
Does it work for the owner of the folder, or not for the owner, either?
Which Nextcloud / richdocuments / Collabora Online versions are you using?

**Comment by poisony** [comment] 2017-05-26 14:07
Yes, that's correct. When using the new feature "Group Folder", creating a folder for a group. Then open that folder and create a new document. Then you are not able to save/edit the document because it says it's missing permissions. You can try this yourself. I'm using the latest Nextcloud 12 and the latest version of all apps including Collabora Online.

You can only create the document but not save/edit it. It's the same for all.

**Comment by thebearon** [comment] 2017-05-28 21:57
Is this the group folders you're referring to?
https://apps.nextcloud.com/apps/groupfolders

**Comment by poisony** [comment] 2017-05-30 15:56
Yes exactly!

**Comment by thebearon** [comment] 2017-06-22 02:46
I created a group folder, created a file there with a user from that group, and could edit and save it just fine. I used NC 12.0.0 and Collabora Online connector app 1.12.33. Can you check again, and give more details if you still get this issue?

**Comment by maxtheaviator** [comment] 2017-08-06 14:37
I have the same problem. Collabora works on personal folders but not in group folders.
NC 12.0.0, Collabora Connector 1.12.34

Do you have any suggestions to solve this issue? Files are going to be saved on closing, but users will complain about this message.

![collabora](https://user-images.githubusercontent.com/12231796/29004286-31f7db54-7ac5-11e7-94b9-820775125396.png)

**Comment by TP75** [comment] 2017-08-24 21:29
We have the same problem. The Collabora Office tool works on personal folders but not in group folders. 

_two virtual hosts, NC 12.0.0, Collabora Connector 1.12.34, nginx reverse proxy, Collabora Office tool running in docker container_

This is quite unfortunate as we had high expectations on collaboration and our team would have used group folders. We had deactivated the Group Folders App due to this issue but will now considering the outcome of first trials after updating to NC 12.0.2 and [Collabora Office 2.1.3](https://www.collaboraoffice.com/release-news/collabora-online-2-1-3-released/) but could find no changes relating to this issue in the [NC 12.0.2 Changelog](https://nextcloud.com/changelog/#latest12)

**Comment by TP75** [comment] 2017-08-28 15:46
Trials after updating to [NC 12.0.2](https://nextcloud.com/changelog/#latest12) and Collabora Office 2.1.3 with active [Collabora Online 1.12.34 App](https://apps.nextcloud.com/apps/richdocuments) showed no issues anymore. The users were able to save the documents opened from a group folder by the Collabora Office GUI again.

The problem seems to be solved now. Thanks to the developers.

**Comment by xbasic** [comment] 2017-12-26 03:55
There is still a problem if you use NC 12.0.4, Collabora Office, Collabora Online 1.12.39 and if you use tags for file access control.
You can download the document, but if you click and open it in Collabora Office, it says "Unable to read your document from storage"

**Comment by poisony** [comment] 2017-12-26 11:43
Today I have other problems with my Group Folders and Collabora. I cannot upload files to any Group Folder, it gives me "Bad Request, Internal Server Error" and I cannot see the file I just uploaded. If i upload the same file again to the same place, it will ask me to overwrite the file and if I choose "No, do not overwrite" and then refresh the page, the file I first uploaded shows up. Really strange problem and I dont know how to get rid of it. I might have to disable Group Folders :(

**Comment by phlbrz** [comment] 2018-08-09 17:32
Hello all,
@thebearon 
Just work with link share.

**Comment by dvaerum** [comment] 2018-11-12 15:36
This is still a problem and using link share as a workaround, is not something I am happy to do in production. Is there any news about this problem?

**Comment by lars-becker** [comment] 2018-11-12 21:58
Disable the versions app. Annoying, but it helps.

**Comment by TP75** [comment] 2018-12-17 12:23
**Group folders** and **Collabora Online** are working on NC 13 and NC 14 as applicable.

These _App_ versions are currently available: 

- **groupfolders 2.0.2**
- **richdocuments 3.0.6** (Collabora Online)

IMHO this issue can be called closed if @poisony would agree.
I would ask other contributors to establish a new issue at their deliberation.

Thanks to the contributors, mainly @icewind1991 and @LukasReschke , for developing the apps. I highly appreciate your efforts and time put into a free and open source app.

**Comment by lars-becker** [comment] 2018-12-17 14:45
Can confirm that the problem is fixed with NC15 and current apps. Thanks a lot, @icewind1991!

**Closed** 2018-12-19 11:01 UTC

**Comment by jothoma1** [comment] 2019-05-14 10:17
You closed but it seems to be still present in NC16. We have this problem too

**Comment by juliushaertl** [comment] 2019-05-15 09:53
I cannot reproduce this. If it is still happening please file a new issue with the full issue template filled out, especially log files and details about your storage setup might be helpful.
