### ISSUE TITLE
coolwsd logging is filling /tmp -- even faster by logging it is getting low on space in /tmp...

### ISSUE THREAD

**Issue by noseshimself** [nextcloud/richdocuments#2676] opened 2022-12-09 02:40 UTC
**Describe the bug**
/tmp is filled completely by coolwsd.log

**To Reproduce**
1. Install Nextcloud-office
2. Use it for a while
3. Wait for strange things happening due to lack of /tmp (e. g. not being able to update apps with an "An error occured during the request. Unable to proceed. Couldn't update app." error)

``/tmp/systemd-private-31e4fd1a5ed34ba9b565299e8e68e5fd-apache2.service-ZNykpg/tmp/coolwsd.JN32Vaplxe/`` (replace the unique identifiers) is filling up with a giant coolwsd.log and the jails are filling with temporary *.upload files.

/tmp is about 2GB and gets filled by this within a week.

The worst are not the uploads/downloads left behind but the log file that is growing from notices that /tmp is filling up. That's a self-fulfilling prophecy. 

**Expected behavior**
I expect coolwsd.log and I expect files below .../jails/... to be removed after uploads/downloads have been processed. If nothing else some slimmed-down logrotate utility limiting these logs that probably nobody is ever reading would be helpful.

**Client details:**
Any web client.

## Server details
**Operating system**
Debian 11

**Web server:**
nginx

**Database:**
mariadb

**PHP version:**
7.4.33

**Nextcloud version:**
24.0.6

**Version of the richdocuments app**
6.3.2

**Version of Collabora Online**
22.5.802

<details>
</details>

**Comment by andriusr** [comment] 2022-12-31 10:51
I am having the same issue with /tmp. Using build-in CODE server on Debian 10 with Appimage. Version of Collabora Online is 22.5.802, Nextcloud office 5.0.10, Nextcloud 23.0.12.
Since I installed office, /tmp is filling with files/folders that starts with php*, lu*, coolwsd*. Appimage folder has ~800 MB, and total is 3.9G just in one month and growing.
It seems that these temp folders are never removed - obviously this is not what one would expect. At least some instructions how to deal with all these folders would be very useful.

**Comment by joshtrichards** [comment] 2023-11-06 01:11
Duplicate of https://github.com/CollaboraOnline/richdocumentscode/issues/187 (among others)

I'm afraid your matter needs to be dealt with over in that repository:

https://github.com/CollaboraOnline/richdocumentscode/

It's not a matter of the Nextcloud Office integration app. Those files you're seeing are coming from the Built-in CODE Server app (`richdocumentscode`).

I encourage you to join the discussions in that repository.

Closing this issue here since we can't do anything about it.

**Closed by joshtrichards** 2023-11-06 01:11 UTC

**Comment by Githopp192** [comment] 2024-08-07 13:52
https://github.com/CollaboraOnline/richdocumentscode/issues/176
