### ISSUE TITLE
nextcloud gridview icon blocks close icon for office.

### ISSUE THREAD

**Issue by Luticus** [nextcloud/richdocuments#324] opened 2018-12-11 06:17 UTC
### Steps to reproduce
1.open any document
2.
3.

### Expected behaviour
Tell us what should happen
Really the gridview icon should probably be hidden when office is launched, but at the very least it shouldn't obstruct the close button.

### Actual behaviour
Tell us what happens instead
gridview obstructs close button
### Server configuration

**Operating system**:
Debian 9
**Web server:**
Apache 2.4
**Database:**
MariaDB
**PHP version:**
7.1
**Nextcloud version:** (see Nextcloud admin page)
15.0
**Updated from an older Nextcloud/ownCloud or fresh install:**
updated from 14
**Where did you install Nextcloud from:**
downloaded zip from nextcloud.com
**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.

No errors have been found.

```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
  - accessibility: 1.1.0
  - activity: 2.8.2
  - admin_audit: 1.5.0
  - announcementcenter: 3.4.0
  - apporder: 0.6.0
  - bookmarks: 0.14.3
  - bruteforcesettings: 1.2.0
  - calendar: 1.6.4
  - cloud_federation_api: 0.1.0
  - comments: 1.5.0
  - contacts: 2.1.8
  - dav: 1.8.0
  - event_update_notification: 0.3.1
  - external: 3.2.0
  - federatedfilesharing: 1.5.0
  - federation: 1.5.0
  - files: 1.10.0
  - files_antivirus: 2.0.0
  - files_automatedtagging: 1.5.0
  - files_downloadactivity: 1.4.0
  - files_external: 1.6.0
  - files_markdown: 2.0.5
  - files_pdfviewer: 1.4.0
  - files_retention: 1.4.0
  - files_sharing: 1.7.0
  - files_texteditor: 2.7.0
  - files_trashbin: 1.5.0
  - files_versions: 1.8.0
  - files_videoplayer: 1.4.0
  - gallery: 18.2.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.3.0
  - metadata: 0.8.0
  - news: 13.0.3
  - nextcloud_announcements: 1.4.0
  - notifications: 2.3.0
  - oauth2: 1.3.0
  - ojsxc: 3.4.3
  - ownbackup: 18.11.0
  - passman: 2.2.0
  - password_policy: 1.5.0
  - previewgenerator: 2.0.0
  - provisioning_api: 1.5.0
  - quota_warning: 1.4.0
  - rainloop: 6.0.2
  - richdocuments: 3.0.5
  - serverinfo: 1.5.0
  - sharebymail: 1.5.0
  - social: 0.1.0
  - spreed: 4.99.0
  - systemtags: 1.5.0
  - tasks: 0.9.8
  - theming: 1.6.0
  - twofactor_admin: 0.2.0
  - twofactor_backupcodes: 1.4.1
  - twofactor_nextcloud_notification: 1.0.1
  - twofactor_totp: 2.0.1
  - twofactor_u2f: 2.0.3
  - updatenotification: 1.5.0
  - user_ldap: 1.5.0
  - workflowengine: 1.5.0

```
</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>

```
<?php
$CONFIG = array (
  'installed' => true,
  'instanceid' => 'censored',
  'passwordsalt' => 'censored',
  'secret' => 'censored',
  'trusted_domains' => 
  array (
    censored
  ),
  'datadirectory' => 'censored',
  'defaultapp' => 'files',
  'dbtype' => 'mysql',
  'version' => '15.0.0.10',
  'dbname' => 'nextcloud',
  'dbhost' => 'database',
  'dbtableprefix' => 'prefix_',
  'dbuser' => 'censored',
  'dbpassword' => 'censored',
  'maintenance' => false,
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'memcache.distributed' => '\\OC\\Memcache\\Redis',
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'redis' => 
  array (
    'host' => 'redis',
    'port' => 6379,
    'dbindex' => 0,
    'password' => 'censored',
    'timeout' => 1.5,
  ),
  'theme' => '',
  'mail_smtpmode' => 'smtp',
  'mail_from_address' => 'censored',
  'mail_domain' => 'censored',
  'mail_smtphost' => 'censored',
  'mail_smtpport' => '465',
  'mail_smtptimeout' => 30,
  'forcessl' => true,
  'xframe_restriction' => false,
  'logtimezone' => 'US/Eastern',
  'logfile' => '/var/log/nextcloud.log',
  'loglevel' => 0,
  'log_authfailip' => true,
  'appstoreenabled' => true,
  'forceSSLforSubdomains' => false,
  'enable_previews' => true,
  'preview_max_scale_factor' => 1,
  'enabledPreviewProviders' => 
  array (
    0 => 'OC\\Preview\\PNG',
    1 => 'OC\\Preview\\JPEG',
    2 => 'OC\\Preview\\GIF',
    3 => 'OC\\Preview\\BMP',
    4 => 'OC\\Preview\\XBitmap',
    5 => 'OC\\Preview\\MP3',
    6 => 'OC\\Preview\\Image',
    7 => 'OC\\Preview\\Illustrator',
    8 => 'OC\\Preview\\Postscript',
    9 => 'OC\\Preview\\Photoshop',
    10 => 'OC\\Preview\\TIFF',
  ),
  'ldapIgnoreNamingRules' => false,
  'appstore.experimental.enabled' => true,
  'auth.bruteforce.protection.enabled' => false,
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtpauth' => 1,
  'mail_smtpname' => 'censored',
  'mail_smtppassword' => 'censored',
  'mail_smtpsecure' => 'ssl',
  'trashbin_retention_obligation' => 'auto',
  'htaccess.RewriteBase' => '/',
  'overwrite.cli.url' => 'https://censored',
  'ldapProviderFactory' => '\\OCA\\User_LDAP\\LDAPProviderFactory',
  'mysql.utf8mb4' => true,
  'app.mail.accounts.default' => 
  array (
    'email' => 'censored',
    'imapHost' => 'censored',
    'imapPort' => 993,
    'imapSslMode' => 'ssl',
    'smtpHost' => 'censored',
    'smtpPort' => 465,
    'smtpSslMode' => 'ssl',
  ),
);

```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
local
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
ldap

### Client configuration
**Browser:**
firefox 63
**Operating system:**
Debian

**Comment by thebearon** [comment] 2018-12-11 06:21
Dupe of #317.

**Closed by thebearon** 2018-12-11 06:21 UTC
