### ISSUE TITLE
Could not establish connection to the Collabora Online server. This might be due to a missing configuration of your web server. For more information, please visit: Connecting Collabora Online Single Click with Nginx

### ISSUE THREAD

**Issue by Pushergene** [nextcloud/richdocuments#1056] opened 2020-06-24 14:07 UTC
Hey. I am running the docker-compose example from github.com/nextcloud/docker.
I am using the fpm with mariadb. 
i replaced  location ~ ^/(?:index|remote|public|cron|core/ajax/update|status|ocs/v[12]|updater/.+|oc[ms]-provider/.+).php(?:$|/) {
with
location ~ ^/nextcloud/(?:index|remote|public|cron|core/ajax/update|status|ocs/v[12]|updater/.+|oc[ms]-provider/.+|.+/richdocumentscode/proxy).php(?:$|/) {

and it still doesnt work. I am using the last updated apps of collabora and the built in code server and i already did 1min ago "docker-compose pull" and restarted the docker container. Could you please fix it? Or do i need to allow some ports in my UFW?

**Comment by juliushaertl** [comment] 2020-06-24 15:34
Duplicate of https://github.com/CollaboraOnline/richdocumentscode/issues/26

**Comment by juliushaertl** [comment] 2020-06-24 15:35
Just a side note, if you are running docker anyways, it would be the best to just use the collabora code container then :wink:

**Closed by juliushaertl** 2020-06-24 15:34 UTC

**Comment by juliushaertl** [comment] 2020-06-25 13:51
Collabora can run on another port, e.g. 9980, but another common way is to have an nginx reverse proxy in front as shown in the examples here: https://github.com/nextcloud/docker/tree/master/.examples/docker-compose/with-nginx-proxy
