### ISSUE TITLE
v5.0.0 breaks NC 23 RC3

### ISSUE THREAD

**Issue by SimplyCorbett** [nextcloud/richdocuments#1886] opened 2021-11-30 18:42 UTC
**Describe the bug**
504 gateway timeout. Instance broken. Previous version worked correctly.

**To Reproduce**
Install v5.0.0

**Expected behavior**
Works as expected.

**Screenshots**

![nextcloud](https://user-images.githubusercontent.com/7935624/144107619-13de6720-4706-4559-bedc-380c073b12ea.png)

**Client details:**
 - OS: [e.g. iOS] Windows
 - Browser [e.g. chrome, safari] Firefox
 - Device: [e.g. iPhone6, desktop] Desktop

## Server details

**Operating system**:
Gentoo

**Web server:**
Nginx 1.21.4
**Database:**
Postgresql 14
**PHP version:**
8.0.13
**Nextcloud version:**
23 RC3
**Version of the richdocuments app**
5.0.0
**Version of Collabora Online**
No idea, instance broken. Was up to date before installing v5.0.0

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
No errors.
```
</details>

**Comment by SimplyCorbett** [comment] 2021-11-30 18:55
Note that I'm using the built in CODE server and not an external server.

**Comment by Aquariu** [comment] 2021-12-01 13:37
Same here on a self-hosted VM. Enabling richdocuments triggers the effect. It is not required to enable richdocumentscode.
On Nextcloud 23.0.0

**Comment by SimplyCorbett** [comment] 2021-12-02 17:18
No, there is no obvious error or bug. I've replicated this on a debian 11 install, too.

**Comment by jakobroehrl** [comment] 2021-12-03 11:31
Checkout https://help.nextcloud.com, there are tips to get this running.

**Comment by SimplyCorbett** [comment] 2021-12-03 12:35
> Checkout https://help.nextcloud.com, there are tips to get this running.

Mind sharing with the class?

**Comment by rakekniven** [comment] 2021-12-03 13:59
See https://help.nextcloud.com/t/psa-how-to-get-collabora-working-on-nextcloud-23/128511

**Comment by SimplyCorbett** [comment] 2021-12-03 14:01
Thanks!

**Comment by Aquariu** [comment] 2021-12-03 20:22
I can confirm that on my test instance, downgrading to a 4.x.y version of the richdocuments app solves the issue. The new way of integrating Collabora into nextcloud 23 seems to work as per design.

**Comment by henmohr** [comment] 2021-12-06 13:39
Hello! 
I have 
Collabora Online
4.2.3
Collabora Online - Built-in CODE Server
21.11.4

Nextcloud Version 22.2.0

I had to disable both because they were crashing the system.

**Comment by Wikinaut** [comment] 2021-12-19 00:54
https://github.com/nextcloud-releases/richdocuments/releases/download/v4.2.3/richdocuments.tar.gz works with NC23.
5.0.0 is broken and makes Collabora Online unusable in NC23.

**Comment by AngelMatilla** [comment] 2021-12-21 10:00
I just updated Richdocuments to 5.0.1 on NC 23 and the behavior is the same with my own collabora server (collabora/code:21.11.0.6.1). It never gets to open the documents. 
However, with Built-in CODE Server 21.11.6 it does now work (which is not the intended behavior for production). 
Right now we're using OnlyOffice in NC 23 through installing the apps: Onlyoffice 7.2.1 and Community Document Server 0.1.11

**Comment by jmechnich** [comment] 2021-12-21 14:14
I can confirm that richdocuments 5.0.1 works in combination with the built-in CODE server 21.11.6 of NC 23.
For me it was necessary to switch the server setting in the Office configuration tab to something else and back to "Use the built-in CODE (...)" to get it to work. Before that, NC just offered to download the files after clicking them.

Thanks!

**Comment by Wikinaut** [comment] 2021-12-21 16:48
@jmechnich But the icons are still missing.

**Comment by juliushaertl** [comment] 2021-12-21 20:00
Let me close this then, the icons issue will be addressed in https://github.com/nextcloud/richdocuments/pull/1938

A follow up to improve the automatic setup of the richdocumentscode app is started in https://github.com/nextcloud/richdocuments/pull/1901

**Closed by juliushaertl** 2021-12-21 20:00 UTC
Labels: bug, 2. developing, build-in code server

**Comment by AngelMatilla** [comment] 2021-12-21 20:42
@juliushaertl what do we do about the fact that it is still not working with an own deployed collabora server? Should I create a new issue about it? Are these issues not related?  

> I just updated Richdocuments to 5.0.1 on NC 23 and the behavior is the same with my own collabora server (collabora/code:21.11.0.6.1). It never gets to open the documents. However, with Built-in CODE Server 21.11.6 it does now work (which is not the intended behavior for production). Right now we're using OnlyOffice in NC 23 through installing the apps: Onlyoffice 7.2.1 and Community Document Server 0.1.11

**Comment by juliushaertl** [comment] 2021-12-21 20:46
Yes, please. Ideally also with full details about how you configured that part as well as an involved reverse proxy.

**Comment by juliushaertl** [comment] 2021-12-21 20:50
In case you upgraded from a previous version, we are currently working on extending our documentation in that regard. You might already want to checkout the draft on the migration guide: 

https://github.com/nextcloud/documentation/pull/7871/files#diff-8bcfdf328e9e538ca548bfa5561b6d24fa61aeb72427696b51c053445cf4cc33

**Comment by AngelMatilla** [comment] 2021-12-22 12:37
> In case you upgraded from a previous version, we are currently working on extending our documentation in that regard. You might already want to checkout the draft on the migration guide:
> 
> https://github.com/nextcloud/documentation/pull/7871/files#diff-8bcfdf328e9e538ca548bfa5561b6d24fa61aeb72427696b51c053445cf4cc33

Thank you, this part indeed did the trick for me. I reconfigured the reverse proxy: 

> - Paths with ``lool`` have been renamed to ``cool``
> - Paths with ``loleaflet`` have been renamed to ``browser``

In case this is interesting for anyone who stumbles upon this issue when migrating to NC 23

**Comment by natrius** [comment] 2022-06-27 20:47
It somehow seems i stumbled on this issue but my collabora is still not working. I made a new issue https://github.com/nextcloud/richdocuments/issues/2287 here with hopefully enough information. I started with updating an old collabora and ended up deleting the old one and now i'm stuck with the "Document could not load"
