### ISSUE TITLE
New spreadsheet or presentation opens wrong app

### ISSUE THREAD

**Issue by rkorn86** [nextcloud/richdocuments#1561] opened 2021-05-17 10:15 UTC
**Describe the bug**
When creating a new spreadsheet or presentation, an empty (word) document opens in LibreOffice Online. Old spreadsheets are not affected. This seems to be related #679

**To Reproduce**
1. Go to 'files app'
2. Click on +
3. Choose 'new spreadsheet (or presentation)'
4. new text (word) document opens in collabora

**Expected behavior**
The collabora spreadsheet app should start instead of text app. The file extension appears correct, in this case ods.

**Screenshots**

**Client details:**
 - OS: Archlinux
 - Browser: Chromium
 - Version: 90.0.4430.212
 - Device: Desktop

## Server details

**Operating system**: Official Nextcloud Docker Image

**Web server:** Nginx

**Database:** MySql

**PHP version:** 7.4.16

**Nextcloud version:** 21.0.1

**Version of the richdocuments app:** 4.1.0

**Version of Collabora Online:** LibreOffice Online from Source Code
```
LOOLWSD
7.0.1 (git hash: a9d8a533)
LOKit
LibreOffice 7.0.5.2.0 (git hash: ad661f0)
```

**Comment by hna61** [comment] 2021-08-30 20:58
I think, the reason is, that the template file beeing used, has the size of 0 bytes. So libre office interprets that as simple text file, opens it within the writer showing the empty dokument. writing formatted text, saving it and opening again will result in loosing any formatting, but keeing all the entered text. writer is in plain text mode. just like opening a *.txt file.

I have this issue since updating from nextcloud 20.x to 21.0.4 this evening. My richdocuments apps version is 4.4.0

Uploading new templates without content for each of the document types works as workaround.

**Comment by juliushaertl** [comment] 2021-10-05 12:37
Closing as a duplicate of https://github.com/nextcloud/richdocuments/issues/1563

**Closed by juliushaertl** 2021-10-05 12:37 UTC
