### ISSUE TITLE
document does not fit into the frame

### ISSUE THREAD

**Issue by ferdiga** [nextcloud/richdocuments#3246] opened 2023-10-21 09:51 UTC
**Describe the bug**
[A clear and concise description of what the bug is.]
<img width="693" alt="20231021 113722 test space xlsx - Files - ChriCar Storage Share" src="https://github.com/nextcloud/richdocuments/assets/6248560/18882398-879d-4a29-a521-edafee17831e">
Opening a calc document shifts down the frame a bit 
- on top a background is visible
- on the bottom the status bar is not (fully) visible

**To Reproduce**
1. Go to File Menu
2. Click on 'calc document"

**Expected behavior**
frame must be placed correctly - especially showing the status bar

**Screenshots**

**Client details:**
 - OS: MacOS 14.0
 - brave v1.59.122 (Oct 20, 2023)
 - opera version: 102.0.4880.78
 
 - Device: macbook

## Server details

**Operating system**:

**Web server:**

**Database:**

**PHP version:**8.2

**Nextcloud version: 27.0.2

**Version of the richdocuments app** :8.2.1

**Version of Collabora Online**Collabora Office 23.05.5.1

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

</details>

**Comment by web10crown** [comment] 2023-10-21 10:21
@ferdiga  screenshot with link can help alot to find the exact issue

**Comment by ferdiga** [comment] 2023-10-21 21:08
using a  shared link does not show this problem, as the complete browser window is used by the collabora content - without the nextcloud background
sorry - this does not help

**Comment by ferdiga** [comment] 2023-10-21 21:10
BTW IMO this issue was probably introduced with NC 27.0.2

**Comment by ferdiga** [comment] 2023-10-21 21:11
BTW "view full screen" does not enlarge the collabora window

**Comment by juliushaertl** [comment] 2023-10-23 06:48
I cannot reproduce this with 27.1.2 so it is likely an incompatibility between the old patch release of Nextcloud 27 (in the viewer app) and the latest richdocuments version.

Can you update your Nextcloud server to the latest patch release?

**Comment by ferdiga** [comment] 2023-10-23 20:06
So I updated one NC instance to 27.1.2 - problem persists
I tried to open an empty xlsx on both my collabora and the demo collabora server.
one can see a cut off line just above the collabora frame
<img width="487" alt="20231023 220328 test xlsx - Files - Nextcloud" src="https://github.com/nextcloud/richdocuments/assets/6248560/fb897056-0b96-4053-a815-d3667f1c51d0">

**Comment by juliushaertl** [comment] 2023-10-24 06:46
Any chance you can send me a temporary test account for this instance via mail? Would be curious to investigate this directly in the browser there as none of my instances with the same version shows this problem.

**Comment by ferdiga** [comment] 2023-10-24 07:18
@juliushaertl Yes I can, please contact me via my EMail directly

**Comment by Sere9aa** [comment] 2023-11-02 09:10
I had this problem due to a conflict with another application.

**Comment by ferdiga** [comment] 2023-11-02 19:29
indeed CADViewer is the culprit

**Comment by juliushaertl** [comment] 2023-11-03 11:51
Let me close this then here, please report this issue to the cadviewer app then as it likely just has too wide css rules applied that cause this.

**Closed** 2023-11-03 11:51 UTC
