### ISSUE TITLE
The Nextcloud sidebar shows up automatically and I don't understand its pattern

### ISSUE THREAD

**Issue by pedropintosilva** [nextcloud/richdocuments#3203] opened 2023-09-27 08:52 UTC
The sidebar box that shows who has shared the file/folder with me appears robbing me of value space on from document and the document's interface. This is particularity dramatic when working with finance related documents (spreadsheets).

Result: I have developed the habit of instantly move the mice to the to top right corner to close that box a soon as it appears
  * Problem: it doesn't always appear and I don't understand the pattern. Thus, sometimes I close the whole document by mistaken because in that very instance the other sidebar didn't appear and by newly learned skill/habit got the best of me.   

----

Versions 

Reported by Julie

* Nextcloud
  * This Nextcloud is on version 27.0.2 Enterprise
  * OC.getCapabilities().richdocuments.version
    * 10:18:03.123 "8.2.0" 
* Collabora Online
  * COOLWSD version: 23.05.4.1snapshot (git hash: d39d2cd (E))
  * LOKit version: Collabora Office 23.05.4.20230917 (git hash: 34a9524)
  * Served by: Debian GNU/Linux 12 (bookworm)
  * Server ID: 5da3ee77

**Comment by jancborchardt** [comment] 2023-09-27 12:02
Sounds good to me to not automatically show our sidebar. I think we initially did this to make sharing more present, but indeed the document should take precedence.

cc @juliushaertl @AndyScherzinger

**Comment by AndyScherzinger** [comment] 2023-09-27 12:03
I agree 

> document should take precedence.

**Comment by juliushaertl** [comment] 2023-10-09 07:10
I don't think we explicitly open it in richdocuments anywhere, so might be worth to check other places like the files app or viewer if there is some logic that may open the sidebar automatically when opening.

**Comment by juliushaertl** [comment] 2023-10-19 12:19
Thanks for that hint. Then it is the files app that shows the sidebar.

@jancborchardt I see two options here:

- We do not automatically show the sidebar for opening any file type (pdf, images, office, text, ...)
- We close it again if a office fileis opened (if we want to limit this behaviour to office itself)

From my perspective we should just not show it for any file type as we open the viewer directly and should probably give the content as much space as possible there.

**Comment by juliushaertl** [comment] 2023-10-19 12:20
Note this behaviour is currently broken on master due to the files2vue migration which does not support to open a file directly yet, but reproducible with 27 and lower

**Comment by jancborchardt** [comment] 2023-10-20 02:45
@juliushaertl I'd say making an exception for Office would be good, because we do want to show the sidebar features presently. It's just that Office already has so many things that it's overwhelming in addition.

**Comment by Darshan-upadhyay1110** [comment] 2023-10-23 10:58
@juliushaertl i am using docker for NC. i have setup for debugging richdocument with NC docker. but it seems this issue is related with files app.

 - so can you guide me if i can debug files app with NC or not ?
 - and also if you have any code pointers to start looking for this sidebar to close for internal link that would be very much usefull

**Comment by pedropintosilva** [comment] 2023-10-23 11:27
@Darshan-upadhyay1110 : Additional links : https://cloud.nextcloud.com/s/iyNGp8ryWxc7Efa?path=%2F1%20Setting%20up%20a%20development%20environment  ; https://docs.nextcloud.com/server/stable/developer_manual/getting_started/devenv.html

**Comment by juliushaertl** [comment] 2023-10-23 14:50
I think the easiest considering Jans comment would be to just trigger a sidebar close within richdocuments whenever we open a document. We can do this by calling the global API method `window.OCA?.Files?.Sidebar?.close()`

**Comment by juliushaertl** [comment] 2023-10-23 14:51
Best place might be here: https://github.com/nextcloud/richdocuments/blob/main/src/view/FilesAppIntegration.js#L77

**Comment by pedropintosilva** [comment] 2023-10-24 12:47
@juliushaertl said:

> if you prefer docker this might be better and faster than do it locally etc https://github.com/juliushaertl/nextcloud-docker-dev#standalone-containers 
```bash
docker run --rm -p 8080:80 -v ~/path/to/richdocuments:/var/www/html/apps-extra/richdocuments ghcr.io/juliushaertl/nextcloud-dev-php80:latest
```


@Darshan-upadhyay1110 said 

> Working on this now, tried to add global method to close the sidebar but it ends up to close and then right after opens again. I need to investigate it further

**Comment by Darshan-upadhyay1110** [comment] 2023-10-25 05:58
hello @juliushaertl i got a easy fix that will work from richdocuments. 

- I have called close sidebar global method at this point `initAfterReady` https://github.com/nextcloud/richdocuments/blob/d63e0ca7592fe7e806317e42b6bd18232204de80/src/view/FilesAppIntegration.js#L93
- and that works good

Query :
- but there is a little concern from my side that i can see the sidebar for fraction of seconds and then it closes. (i mean after file loading done sidebar closes)
- so this behaviour is okay ? can we go with that?

**Comment by juliushaertl** [comment] 2023-10-25 08:21
Yes, I'd say this is a good start. 

If we want to avoid the flickering we'd need to extend the files app to allow apps bocking the opening in https://github.com/nextcloud/server/blob/188e5d51345126bdc15d26a0d0999167b3058220/apps/files/src/components/FilesListVirtual.vue#L225-L232 right away but that might need more thinking on how to best achieve that.

**Closed** 2023-10-30 14:38 UTC
Labels: ux
