### ISSUE TITLE
Nextcloud Server Locks up Slow when Collabora Server is offline

### ISSUE THREAD

**Issue by ghost** [nextcloud/richdocuments#2486] opened 2022-10-06 17:24 UTC
**Describe the bug**

**To Reproduce**
1. Turn off Callobora Server VM for updates
2. After a while the Nextcloud server slows down and locks up

**Expected behavior**

**Screenshots**

**Client details:**
 - Device: [e.g. iPhone6, desktop]

## Server details

**Operating system**:
Ubuntu 20.0.4
**Web server:**
Apache
**Database:**
MariaDb
**PHP version:**
8.0
**Nextcloud version:**
NC 24.0.6 & NC 25 RC3
**Version of the richdocuments app**
6.2.0 & 7.0.0-beta.2
**Version of Collabora Online**
Collabora Office 22.05.6.3

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

</details>

**Comment by mritzmann** [comment] 2023-05-04 11:58
Duplicate of #2722

**Comment by joshtrichards** [comment] 2023-07-13 16:12
@mritzmann Other way around, but yeah :)

**Comment by juliusknorr** [comment] 2024-11-28 07:35
This was fixed by https://github.com/nextcloud/richdocuments/pull/3749 and https://github.com/nextcloud/richdocuments/pull/3762 but unfortunately rather complex so not backported and only available with Nextcloud 30.

**Closed by juliusknorr** 2024-11-28 07:35 UTC
Labels: bug, performance
