### ISSUE TITLE
Dark mode with font color and parts of tool bar colors being very dark

### ISSUE THREAD

**Issue by panomitrius** [nextcloud/richdocuments#3153] opened 2023-08-31 14:46 UTC
**Describe the bug**
When having Nextcloud set to dark theme, the font color and also some parts of the toolbar icons are remaining black which makes them close to invisible.

**To Reproduce**
I'm running nextcloud and nextcloud office on a docker setup, latest versions. 
Set theme to dark
Open rich document

**Expected behavior**
Font color and toolbar colors would change so to be clear and visible on the dark background.

**Screenshots**
![screenshot nextcloud office](https://github.com/nextcloud/richdocuments/assets/75156060/ec3ffddf-d330-4dd4-8929-b8062e5005fc)

**Client details:**
 - OS: macOS Ventura
 - Browser: Firefox, Brave, Safari (same in all of them, also with cleared cache)
 - Version: All versions up to date
 - Device: Macbook 

## Server details

**Operating system**: Ubuntu 22.02 Docker

**Web server:** nginx reverse proxy

**Database:** mariadb

**PHP version:**

**Nextcloud version:** 27.0.2.1

**Version of the richdocuments app**: 23.05.3.1

**Version of Collabora Online**: 23.05.3.1

**Comment by panomitrius** [comment] 2023-08-31 17:45
An update: when I change to dark mode within Nextcloud Office, the text shifts to visible white, but the icons in the toolbar remains dark..

**Comment by juliushaertl** [comment] 2023-09-01 14:15
This seems to be a regression with the latest code build, I'll have a look.

**Comment by MoritzDPTV** [comment] 2023-11-03 11:40
Is it possible to set the Nextcloud Office default theme globally for all users or even enforce it as for the regular Nextcloud theming?

**Comment by sskokorin** [comment] 2023-11-08 18:21
> Is it possible to set the Nextcloud Office default theme globally for all users independently from the defined Nextcloud theming?

I'm also interested in the answer to this question.

**Comment by joshtrichards** [comment] 2023-11-09 18:04
This appears to have been fixed in newer versions of CODE.

Or at least I can't reproduce it and there appear to be some relevant items in the release notes for >=23.05.4:

https://www.collaboraoffice.com/code-23-05-release-notes/

**Comment by juliushaertl** [comment] 2023-12-06 15:07
This very much depends on the document that you use (or template this is created from)

It would be good to know how you created that file and what file format it is using.

It is likely that for the case where this happens the font color is set to black on the new document instead of "Automatic" (see screenshot below) One can manually change that, but would of course be good to fix this in whatever case this still occurs.

<img width="208" alt="Screenshot 2023-12-06 at 16 06 16" src="https://github.com/nextcloud/richdocuments/assets/3404133/d68cd088-ec4c-4ba2-a7f6-54a86517284e">

**Comment by juliushaertl** [comment] 2023-12-06 16:20
Can you tell with what software? Interesting. I think MS Office also has a dark mode so would be curious how the file is rendered there?

**Comment by AndyXheli** [comment] 2023-12-06 18:07
Yea personally not a big fan! but that's a personal preference

**Comment by surfrock66** [comment] 2023-12-29 19:26
Additional details, there is a huge UI issue between the "Dark Theme" and "Dark Theme with High Contrast Mode" nextcloud themes.

Dark Theme:
![image](https://github.com/nextcloud/richdocuments/assets/1345467/960f5f81-1612-4d4c-bff7-5c1ada9275a9)

Dark Theme with High Contrast Mode for the same document:
![image](https://github.com/nextcloud/richdocuments/assets/1345467/d1fee3f2-fda7-43ad-8246-58e954a90fa6)

Collabora is it's own vm, 23.05.6.4.
Nextcloud is on Ubuntu Server 22.04, v27.1.5
Nextcloud Office app 8.2.3

**Comment by sskokorin** [comment] 2023-12-29 19:31
My only wish is to be able to disable the dark mode for all users forever

**Comment by mwinkens** [comment] 2024-01-26 13:00
Totally readable table right? This is full of data.
Currently users can toggle darkview in the `View` field which doesn't affect nextcloud. So you have lightview in collabora and nightview elsewhere. I wish for a button to disable darkview for every user in collabora.

![Bildschirmfoto vom 2024-01-26 13-56-20](https://github.com/nextcloud/richdocuments/assets/104770531/3606788c-13e5-4af4-b2c1-3c979f6c4ac7)

**Comment by pedropintosilva** [comment] 2024-01-26 15:02
Thank @mwinkens for taking the time to test, report and attach the screenshot. It really helps!

> Totally readable table right? This is full of data.

Could you please attach here the document? I think what's happening is that the document is being created with text styles that have static colour (in this case `Black`). 

I have just tried, on my end, and creating a spreadsheet in Nextcloud doesn't make use of hard coded black (the styles have `auto` which means they change depending on the mode).

Nevertheless this doesn't solve the problem of already created documents with styles that are set to `Black` or `White` within or outside of Nextcloud  (example: the user might want to print something with white text color on a colourful paper or on shape etc). Which leads to the question: should we just ignore the colours which the document was created with? At least when darkmode is toggle on? And all of them or just the styles with lack of contrast?

> Currently users can toggle darkview in the View field which doesn't affect nextcloud. So you have lightview in collabora and nightview elsewhere. I wish for a button to disable darkview for every user in collabora.

This seems to be a distinct comment but I'm not sure I understand. If I understood correctly you are hinting at the fact that inconsistency is undesirable/not wanted(?) Could you please expand on that?

**Comment by mwinkens** [comment] 2024-01-26 16:31
@pedropintosilva 
~~I think this has nothing to do with *static* colors, this is a xlsx file coming from (microsoft) excel, which is opened with the default dark mode setting from nextcloud.~~ I tried to reproduce this with a normal ods table and there the font was white and not black, but the user who created the file does use light theme.

I can't give you the original file, but I managed to reproduce this in a test file

[test.xlsx](https://github.com/nextcloud/richdocuments/files/14067153/test.xlsx)

![dunkler-modus](https://github.com/nextcloud/richdocuments/assets/104770531/9d3d2431-a223-4fad-86e6-f6a6f2e4c435)

>This seems to be a distinct comment but I'm not sure I understand. If I understood correctly you are hinting at the fact that inconsistency is undesirable/not wanted(?) Could you please expand on that?

Do you see the big red button in the screenshot saying "Dunkler Modus", when I klick that I can switch to light theme inside collabora making the table white and looking usable again:

![dunkler-modus2](https://github.com/nextcloud/richdocuments/assets/104770531/ec59fbf1-07c3-4d84-85a8-e9e36ebfa290)

**Comment by mejo-** [comment] 2024-04-25 21:42
I just experienced the same issue when I created a new spreadsheet from Nextcloud Files in dark mode (reproducible on the company instance). In Nextcloud appearance settings, system default theme is configured. But switching to dark theme  there doesn't change anything.

![2024-04-25T23:40:03,275010246+02:00](https://github.com/nextcloud/richdocuments/assets/3582805/06ed8eaf-db25-48f3-b986-feb9cfcb4770)

**Comment by DaanSelen** [comment] 2024-05-02 14:28
This issue is still there, dark mode is very dark. Can I disable this or make the bright mode default?

**Comment by kwaun** [comment] 2024-05-13 17:01
Same issue. When I set my browser (Brave) configured as "Auto Dark Mode for Web Contents": **Default (Disabled)**, the page looks perfect in Dark Mode.

![pure-dark-mode](https://github.com/nextcloud/richdocuments/assets/12612253/f5f258d0-9011-4b76-a7a2-9e06983639fb)

But when I configure my browser as "Auto Dark Mode for Web Contents": **Enabled**, the toolbar icons look way too dark in Dark Mode.

![browser-dark-mode](https://github.com/nextcloud/richdocuments/assets/12612253/5682fbe5-f8f1-4928-bdcf-d29fbac34434)

It seems like an icon palette color issue. The document looks fine btw.

collabora/code:24.04.2.1.1
nextcloud:29.0.0-apache

**Comment by DaanSelen** [comment] 2024-05-13 19:58
I have seen that Collabora has some trouble with finding certain dark icons with the latest docker image, could that be it?

**Comment by phirestalker** [comment] 2024-07-02 14:31
I can't find the option in collabora spreadsheet to set the text color to auto. Where is it located?

**Comment by JMarcosHP** [comment] 2024-08-06 17:35
Using android Chrome App.

![IMG_20240806_113248.jpg](https://github.com/user-attachments/assets/0e04976d-9f10-4a5a-b5c6-a746c4b06c44)

This is an .xlsm file form Excel.

**Comment by godfuture** [comment] 2024-08-23 20:41
> C Server 27.1.4

This is exactly how it looks for me with cp-23.05.10-1 and Nextcloud 28.0.4.

**Comment by godfuture** [comment] 2024-08-23 22:23
Btw. this helped me:
https://forum.collaboraonline.com/t/switch-between-light-dark-theme-code-22-05/1259/7

**Comment by juliushaertl** [comment] 2024-09-16 09:07
I'll close this as the initially reported button issues are fixed. For further bugs with the menubar and general UI please open separate issues. Regarding wrong colors in the document you may want to check first if there is an automatic color set in the document you are using itself. There is no automatic inversion of fixed colors like black borders or text within Collabora.

**Closed by juliushaertl** 2024-09-16 09:07 UTC
Labels: bug, 1. to develop, branding, regression
