### ISSUE TITLE
Overwriteprotocol option seems to be ignored

### ISSUE THREAD

**Issue by 13hannes11** [nextcloud/richdocuments#1092] opened 2020-07-22 11:28 UTC
**Describe the bug**
The nextcloud app tries to connect via http even though https is set via "overwriteprotocol": "https" in the config file of nextcloud.

**To Reproduce**
Open a file with nextcloud being behind a reverse proxy. The connection from the reverse proxy to nextcloud is via HTTP vut the reverse proxy itself is only reached from the outside via HTTPS.

**Expected behavior**
The conenction should be made to https://exaple.com if overwriteprotocol is set to https.

**Client details:**
 - OS: Ubuntu 20.04
 - Browser Chrome (84.0.4147.89), Firefox (78.0.2)

## Server details
The server is running as docker application with traefik as a reverse proxy. They are both running on the same machine.

**Version of the richdocuments app**
4.2.503

**Version of Collabora Online**
3.7.3

#### Browser log
![image](https://user-images.githubusercontent.com/9381167/88171020-ee75bc80-cc1e-11ea-8efc-0b7df24293b4.png)

**Comment by juliushaertl** [comment] 2020-07-27 10:21
Duplicate of https://github.com/CollaboraOnline/richdocumentscode/issues/2

**Closed by juliushaertl** 2020-07-27 10:21 UTC
