### ISSUE TITLE
Collabora Online not working

### ISSUE THREAD

**Issue by janhsh** [nextcloud/richdocuments#132] opened 2017-10-29 14:34 UTC
### Steps to reproduce
1. (Collabora Online is active) - 
2.  Create New Spreadsheet or (New document) 
3. Click to the New Spreadsheet or( the New document) to open it

### Expected behaviour
The file must be open 

### Actual behaviour

This error message is displayed 
> Erreur interne du serveur
> Le serveur a rencontré une erreur interne et est incapable d'exécuter votre requête.
> Veuillez contacter l'administrateur du serveur si cette erreur apparaît plusieurs fois. Veuillez joindre les détails techniques à votre rapport.
> Le fichier journal du serveur peut fournir plus de renseignements.

### Server configuration
Basic condiguration

**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**Nextcloud version:** (see Nextcloud admin page)

**Updated from an older Nextcloud/ownCloud or fresh install:**

**Where did you install Nextcloud from:**

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>
```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by janhsh** [comment] 2017-10-29 14:35
Note:   Collabora Online release is 1.12.35

**Comment by janhsh** [comment] 2017-10-29 14:47
Logs

`

  | richdocuments | GuzzleHttp\Exception\RequestException: cURL error 3: <url> malformed/var/www/html/nextcloud/3rdparty/guzzlehttp/guzzle/src/RequestFsm.php - line 103:   GuzzleHttp\Exception\RequestException   wrapException(Object(GuzzleHttp\Message\Request),  Object(GuzzleHttp\Ring\Exception\RingException))/var/www/html/nextcloud/3rdparty/guzzlehttp/guzzle/src/RequestFsm.php - line 132:  GuzzleHttp\RequestFsm->__invoke(Object(GuzzleHttp\Transaction))/var/www/html/nextcloud/3rdparty/react/promise/src/FulfilledPromise.php - line 25:  GuzzleHttp\RequestFsm->GuzzleHttp\{closure}(Array)/var/www/html/nextcloud/3rdparty/guzzlehttp/ringphp/src/Future/CompletedFutureValue.php - line 55:  React\Promise\FulfilledPromise->then(Object(Closure), NULL, NULL)/var/www/html/nextcloud/3rdparty/guzzlehttp/guzzle/src/Message/FutureResponse.php - line 43:  GuzzleHttp\Ring\Future\CompletedFutureValue->then(Object(Closure), NULL, NULL)/var/www/html/nextcloud/3rdparty/guzzlehttp/guzzle/src/RequestFsm.php - line 134:  GuzzleHttp\Message\FutureResponse  proxy(Object(GuzzleHttp\Ring\Future\CompletedFutureArray), Object(Closure))/var/www/html/nextcloud/3rdparty/guzzlehttp/guzzle/src/Client.php - line 165:  GuzzleHttp\RequestFsm->__invoke(Object(GuzzleHttp\Transaction))/var/www/html/nextcloud/3rdparty/guzzlehttp/guzzle/src/Client.php - line 125:  GuzzleHttp\Client->send(Object(GuzzleHttp\Message\Request))/var/www/html/nextcloud/lib/private/Http/Client/Client.php - line 138:  GuzzleHttp\Client->get('/hosting/discov...', Array)/var/www/html/nextcloud/apps/richdocuments/lib/WOPI/DiscoveryManager.php - line 84:  OC\Http\Client\Client->get('/hosting/discov...')/var/www/html/nextcloud/apps/richdocuments/lib/WOPI/Parser.php - line 41:  OCA\Richdocuments\WOPI\DiscoveryManager->get()/var/www/html/nextcloud/apps/richdocuments/lib/TokenManager.php - line 117:  OCA\Richdocuments\WOPI\Parser->getUrlSrc('application/vnd...')/var/www/html/nextcloud/apps/richdocuments/lib/Controller/DocumentController.php - line 168:  OCA\Richdocuments\TokenManager->getToken(*** sensitive parameters replaced ***)[internal function] OCA\Richdocuments\Controller\DocumentController->index('468')/var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 160:  call_user_func_array(Array, Array)/var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 90:  OC\AppFramework\Http\Dispatcher->executeController(Object(OCA\Richdocuments\Controller\DocumentController), 'index')/var/www/html/nextcloud/lib/private/AppFramework/App.php - line 114:  OC\AppFramework\Http\Dispatcher->dispatch(Object(OCA\Richdocuments\Controller\DocumentController), 'index')/var/www/html/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php - line 47:  OC\AppFramework\App  main('OCA\\Richdocumen...', 'index', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)[internal function] OC\AppFramework\Routing\RouteActionHandler->__invoke(Array)/var/www/html/nextcloud/lib/private/Route/Router.php - line 299:  call_user_func(Object(OC\AppFramework\Routing\RouteActionHandler), Array)/var/www/html/nextcloud/lib/base.php - line 1004:  OC\Route\Router->match('/apps/richdocum...')/var/www/html/nextcloud/index.php - line 48:  OC  handleRequest(){main}
-- | -- | --


`

**Comment by thebearon** [comment] 2017-11-01 17:08
Duplicate of #58.

**Closed by thebearon** 2017-11-01 17:08 UTC

**Comment by usr-h** [comment] 2017-12-26 10:49
Hy,
This min. 3 year before working perfect in all nextclode installation...
100% :(
