### ISSUE TITLE
v5.0.0 don't work with Collabora

### ISSUE THREAD

**Issue by fatalerrors80** [nextcloud/richdocuments#1895] opened 2021-12-03 13:58 UTC
**Describe the bug**
When using Collabora Built-in CODE server, we obtain infinite loading screen.

**To Reproduce**
1. Install built-in CODE serveur
2. Install or upgrade Collabora/Nextcloud Office Plugin
3. Check Nextcloud Office is using built-in CODE server and connection is OK
4. Try to open an Open Document file

**Expected behavior**
Office document to be opened and editable

**Client details:**
 - OS: Debian Bulleyes
 - Browser Firefox
 - Version 78.15.0esr
 - Device: desktop

## Server details

**Operating system**: Debian Bullseye

**Web server:** Apache

**Database:** External PGSQL

**PHP version:** 7.4.25

**Nextcloud version:** 23

**Version of the richdocuments app** 5.0.0

**Version of Collabora Online** 21.2 (same behaviour with the older version=

<details>
Revert to version 4.1.2 fixes the problem, even if marked as unsupported by Nextcloud 23.
</details>

**Comment by SimplyCorbett** [comment] 2021-12-03 14:02
Yep, we have an issue for this already here :)

The solution is to fresh install nextcloud 23 and use v4.1.2 of collabora.

See here - https://help.nextcloud.com/t/psa-how-to-get-collabora-working-on-nextcloud-23/128511

**Comment by fatalerrors80** [comment] 2021-12-03 14:12
I suggest stopping distribution of v5.0.0 as it's obviously breaking a lot of Collabora instances. This is quite unprofessional to distribute such not tested enough plugin, especially when you put a lot of communication on it.

This also show that automatic plugin upgrade after Nextcloud upgrade, is not a great idea, particularly on third party plugins.

**Comment by leonardohlee** [comment] 2021-12-03 18:36
![image](https://user-images.githubusercontent.com/16806817/144654892-3651709b-87e8-460a-8536-342d9d6cce35.png)
same Issue with V5 here,  it shows enabled. but won't open office document .
OS ubuntu 20.04
Apache2
Php7.4
NC23

**Comment by Aquariu** [comment] 2021-12-04 15:14
Duplicate of https://github.com/nextcloud/richdocuments/issues/1886 ?

**Comment by fatalerrors80** [comment] 2021-12-04 23:16
> Duplicate of #1886 ?

I think you didn't read details of the issue to say that...

**Comment by Aquariu** [comment] 2021-12-05 15:26
I did read, but I'll accept that I misunderstood without resistance whatsoever.
My apologies.

**Comment by markuman** [comment] 2021-12-06 14:41
I wonder how nextcloud comes in mind to name this new "nextcloud office" feature in there release presentation if it is 
a) not working
b) was not released on release date of NC23 itself

**Comment by LunaSquee** [comment] 2021-12-11 21:33
Having the same issue with an external server.

**Closed** 2021-12-17 15:42 UTC
Labels: bug, 2. developing, build-in code server

**Comment by markuman** [comment] 2021-12-18 08:05
It's still not working here. Tested with a fresh new setup.

**Comment by beleon** [comment] 2021-12-18 15:42
The fix is not included in any release yet, currently just present in the git repo. Wait for #1922 to go through.

**Comment by fatalerrors80** [comment] 2021-12-21 22:40
Upgraded to 5.0.1, still not working and exact same behavior...

Now I really am disappointed

**Comment by beleon** [comment] 2021-12-21 23:13
It's working for me now. I use an nginx reverse proxy. Do you use the Built-in CODE server @fatalerrors80? A reverse proxy shouldn't be a problem when using the Built-in CODE server afaik.

**Comment by fatalerrors80** [comment] 2021-12-21 23:18
Yes I'm using bultin CODE server

**Comment by markuman** [comment] 2021-12-22 07:56
5.0.1 with build-in server works for me now on a fresh setup.

**Comment by markushagge** [comment] 2022-01-23 12:16
5.0.1 does not work here, neither for new installations, nor for updates (both With built-in Code-Server, latest version , in case of new installations loaded and installed with during installation)
