### ISSUE TITLE
Delete key not working anymore.

### ISSUE THREAD

**Issue by YoannPa** [nextcloud/richdocuments#3077] opened 2023-07-18 14:16 UTC
**Describe the bug**
In a document open in Collabora (Nextcloud Office) when I want to delete some text, the delete key does not work.

**To Reproduce**
1. Create or Open a document (.odt or .docx whatever)
2. Write some text in it.
3. Now try to delete manually the text using the delete key on your keyboard. It doesn't work.

**Expected behavior**
I never really paid attention to it, but I guess it always worked before: using the delete key should delete text, as in any text editor.

**Screenshots**
Not applicable.

**Client details:**
 - OS: Ubuntu 22.04 & Ubuntu 16.04
 - Browser: Firefox
 - Version: 115.0.2 (64-bit)
 - Device: Laptop Lenovo Legion Y520 & different desktops 

## Server details

**Operating system**: Ubuntu 16.04

**Web server:** Nginx

**Database:** Sqlite3 I guess.

**PHP version:** PHP 7.4.13 (cli) (built: Nov 28 2020 06:24:27) ( NTS )

**Nextcloud version:** 26.0.3 installed with snap

**Version of the richdocuments app** Did not find it but I have:
- Collabora Online - Built-in CODE Server 23.5.104
- Version COOLWSD 23.05.1.3

**Comment by thebearon** [comment] 2023-07-18 14:36
This seems to be duplicate of https://github.com/CollaboraOnline/online/issues/6631 and will be fixed with the next update.

**Closed by thebearon** 2023-07-18 14:36 UTC
