### ISSUE TITLE
Accessing file through the Android App makes it unavailable to the webapp, plus destroys content

### ISSUE THREAD

**Issue by apiraino** [nextcloud/richdocuments#413] opened 2019-02-24 01:29 UTC
**Describe the bug**
Cannot open a specific .ODS file anymore after having opened it from the NextCloud Android app

**To Reproduce**
1. Double click on the file
2. The loading appears as always
3. A popup appears saying that the document loading failed ("Lesen des Dokuments vom Speicher fehlgeschlagen. Bitte kontaktieren Sie den Administrator Ihres Speicherservers")
4. Retried to open from the app, didn't work, file became suddenly 0 bytes :-(

**Expected behavior**
Edit the document like it has always worked

And guys, possibly do not lose my files

**Client details:**
 - OS: Ubuntu/18
 - Browser: firefox
 - Version: 66.0b10 (64-bit)
 - Device: desktop and Android

## Server details

**Operating system**: Ubuntu server 18.0.2

**Web server:** apache 2.24

**Database:** mysql

**PHP version:** 7.2

**Nextcloud version:** 15.0.4

**Version of the richdocuments app:** 3.2.1

**Version of Collabora Online** 3.2.1

<details>
<summary>

wsd-00030-00128 2019-02-23 23:14:47.778695 [ docbroker_00b ] ERR  WOPI::GetFile failed with 503 Service\
 Unavailable| wsd/Storage.cpp:665                                                                       
                                                                                                        
wsd-00030-00128 2019-02-23 23:14:47.779229 [ docbroker_00b ] ERR  Failed to add session to [/index.php/\
apps/richdocuments/wopi/files/5393_octlaknhjopk] with URI [https://my.domain.com/index.php/apps/richdoc\
uments/wopi/files/5393_<app_id>?access_token=xxx&access_token_ttl=0&permission=edit]: WOPI::GetFile fai\
led| wsd/DocumentBroker.cpp:1091                                                                        
                                                                                                        
wsd-00030-00128 2019-02-23 23:14:47.779718 [ docbroker_00b ] WRN  Child session [00f3] not found to for\
ward message: load url=https://my.domain.com/index.php/apps/richdocuments/wopi/files/5393_<app_id>?\
access_token=xxx&access_token_ttl=0&permission=edit authorid=me xauthorid=meme author=me xauthor=meme a\
uthorextrainfo=%7B%0A%20%20%22avatar%22%20:%20%22https:%5C/%5C/my.domain.com%5C/index.php%5C/avatar%5C/\
me%5C/32%22%0A%7D readonly=0 lang=de| wsd/DocumentBroker.cpp:1736                                       
                                                                                                        
wsd-00030-00128 2019-02-23 23:14:47.844161 [ docbroker_00b ] ERR  Invalid or unknown session [00f3] to remove.| wsd/DocumentBroker.cpp:1160

</summary>

#### Nextcloud log (data/nextcloud.log)
```
{"reqId":"cL3DcMPNUR2pBGbCB0iA","level":0,"time":"2019-02-24T01:25:12+00:00","remoteAddr":"172.17.0.2","user":"--","app":"ric\
hdocuments","method":"GET","url":"\/index.php\/apps\/richdocuments\/wopi\/files\/5393_<nc_id>?access_token=xxx&access_token_t\
tl=0&permission=edit","message":"Loaded WOPI Token record: {\"id\":\"307\",\"owner_uid\":\"me\",\"editor_uid\":\"me\",\"guest\
_displayname\":null,\"fileid\":\"5393\",\"version\":\"0\",\"canwrite\":\"1\",\"server_host\":\"https:\/\/my.domain.com\/\",\"\
token\":\"PEOP9rkqweiIg7kJ9HGgoJ1BLPJBHb5f\",\"expiry\":\"1550973309\",\"template_destination\":\"0\"}.","userAgent":"LOOLWSD\
 WOPI Agent 4.0.0","version":"15.0.4.0"}                                                                                      
{"reqId":"cL3DcMPNUR2pBGbCB0iA","level":0,"time":"2019-02-24T01:25:12+00:00","remoteAddr":"172.17.0.2","user":"--","app":"no \
app in context","method":"GET","url":"\/index.php\/apps\/richdocuments\/wopi\/files\/5393_<nc_id>?access_token=xxx&access_tok\
en_ttl=0&permission=edit","message":"No cache entry found for \/appdata_<nc_id>\/avatar\/me\/avatar.jpg (storage: local::\/sr\
v\/nextcloud\/data\/, internalPath: appdata_<nc_id>\/avatar\/me\/avatar.jpg)","userAgent":"LOOLWSD WOPI Agent 4.0.0","version\
":"15.0.4.0"}                                                                                                                 
{"reqId":"X5WNgFEGtaY08w7TeDhu","level":0,"time":"2019-02-24T01:25:13+00:00","remoteAddr":"172.17.0.2","user":"--","app":"ric\
hdocuments","method":"GET","url":"\/index.php\/apps\/richdocuments\/wopi\/files\/5393_<nc_id>\/contents?access_token=xxx&acce\
ss_token_ttl=0&permission=edit","message":"Loaded WOPI Token record: {\"id\":\"307\",\"owner_uid\":\"me\",\"editor_uid\":\"me\
\",\"guest_displayname\":null,\"fileid\":\"5393\",\"version\":\"0\",\"canwrite\":\"1\",\"server_host\":\"https:\/\/my.domain.\
com\/\",\"token\":\"xxx\",\"expiry\":\"1550973309\",\"template_destination\":\"0\"}.","userAgent":"LOOLWSD WOPI Agent 4.0.0",\
"version":"15.0.4.0"}                                                                                                         
```

#### Browser log
```
nothing relevant

</details>

**Comment by apiraino** [comment] 2019-02-24 14:55
I tried reproducing my own bug without success, although what is described happended. Might have been a problematic file or a coincidence of factors, but I hope this report can give some insights on where to investigate. Losing access to files is no fun (especially when encrypted at rest, therefore not accessible from the filesystem).

**Comment by juliushaertl** [comment] 2019-02-26 20:45
> especially when encrypted at rest, therefore not accessible from the filesystem
@apiraino So you are using encryption? Can you paste your Nextcloud config as well?

I assume there are no more error messages in your nextcloud.log besides the ones you have posted?

**Comment by apiraino** [comment] 2019-02-26 21:32
Hi @juliushaertl , thanks for your feedback. Correct, the logs I posted are the only error I see. Actually there is a [recurring error in the logs](https://help.nextcloud.com/t/requesting-address-is-denied-172-17-0-1-wsd-loolwsd-cpp-1971/44179), but it is not relevant to this issue
but there are not relevant.

I tried to create randomly files on then access them from movile and web, edit and sync them. Just in one occasion I could reproduce the above issue, resulting in being locked out of the file.

The system config is as follows:

<details>

```
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.storiepvtride.it"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "15.0.4.0",
        "overwrite.cli.url": "https:\/\/cloud.storiepvtride.it",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "twofactor_enforced": "false",
        "twofactor_enforced_groups": [],
        "twofactor_enforced_excluded_groups": [],
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "mail_smtpauthtype": "LOGIN",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "tls",
        "mail_smtpport": "25",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "maintenance": false,
        "log_type": "file",
        "logfile": "\/var\/www\/cloud.storiepvtride.it\/logs\/nextcloud.log",
        "loglevel": "0",
        "theme": "",
        "versions_retention_obligation": "auto"
    },

```

</details>

**Comment by apiraino** [comment] 2019-02-27 08:28
Additional note: if I try to download the file I am redirected on this page:
`https://mycloud.com/remote.php/webdav/Documents/filename.ods?downloadStartSecret=xxx`

which returns a 500, see this `nextcloud.log` snippet:

<details>

```
{
    "reqId": "sOtt5ct37J3FfQ12LuMH",
    "level": 4,
    "time": "2019-02-27T08:21:25+00:00",
    "remoteAddr": "aaa.bb.ccc.ddd",
    "user": "myuser",
    "app": "webdav",
    "method": "GET",
    "url": "\/remote.php\/webdav\/Documents\/filename.ods?downloadStartSecret=xxx",
    "message": {
        "Exception": "OCP\\Encryption\\Exceptions\\GenericEncryptionException",
        "Message": "Bad Signature",
        "Code": 0,
        "Trace": [{
            "file": "\/var\/www\/nc.mydomain.com\/htdocs\/apps\/encryption\/lib\/Crypto\/Crypt.php",
            "line": 467,
            "function": "checkSignature",
            "class": "OCA\\Encryption\\Crypto\\Crypt",
            "type": "->",
            "args": ["<redacted>", null, "<redacted>"]
        }, {
            "file": "\/var\/www\/nc.mydomain.com\/htdocs\/apps\/encryption\/lib\/Crypto\/Encryption.php",
            "line": 379,
            "function": "symmetricDecryptFileContent",
            "class": "OCA\\Encryption\\Crypto\\Crypt",
            "type": "->",
            "args": ["*** sensitive parameter replaced ***", null, "AES-256-CTR", 3, "*** sensitive parameter replaced ***"]
        }, {
            "file": "\/var\/www\/nc.mydomain.com\/htdocs\/lib\/private\/Files\/Stream\/Encryption.php",
            "line": 479,
            "function": "decrypt",
            "class": "OCA\\Encryption\\Crypto\\Encryption",
            "type": "->",
            "args": ["*** sensitive parameters replaced ***"]
        }, {
            "file": "\/var\/www\/nc.mydomain.com\/htdocs\/lib\/private\/Files\/Stream\/Encryption.php",
            "line": 299,
            "function": "readCache",
            "class": "OC\\Files\\Stream\\Encryption",
            "type": "->",
            "args": []
        }, {
            "function": "stream_read",
            "class": "OC\\Files\\Stream\\Encryption",
            "type": "->",
            "args": [8192]
        }, {
            "file": "\/var\/www\/nc.mydomain.com\/htdocs\/3rdparty\/icewind\/streams\/src\/Wrapper.php",
            "line": 91,
            "function": "fread",
            "args": [null, 8192]
        }, {
            "file": "\/var\/www\/nc.mydomain.com\/htdocs\/3rdparty\/icewind\/streams\/src\/CallbackWrapper.php",
            "line": 91,
            "function": "stream_read",
            "class": "Icewind\\Streams\\Wrapper",
            "type": "->",
            "args": [8192]
        }, {
            "function": "stream_read",
            "class": "Icewind\\Streams\\CallbackWrapper",
            "type": "->",
            "args": [8192]
        }, {
            "file": "\/var\/www\/nc.mydomain.com\/htdocs\/3rdparty\/sabre\/http\/lib\/Sapi.php",
            "line": 80,
            "function": "stream_copy_to_stream",
            "args": [null, null, "14595"]
        }, {
            "file": "\/var\/www\/nc.mydomain.com\/htdocs\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php",
            "line": 498,
            "function": "sendResponse",
            "class": "Sabre\\HTTP\\Sapi",
            "type": "::",
            "args": [{
                "__class__": "Sabre\\HTTP\\Response"
            }]
        }, {
            "file": "\/var\/www\/nc.mydomain.com\/htdocs\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php",
            "line": 254,
            "function": "invokeMethod",
            "class": "Sabre\\DAV\\Server",
            "type": "->",
            "args": [{
                "absoluteUrl": "https:\/\/nc.mydomain.com\/remote.php\/webdav\/Documents\/spese.ods?downloadStartSecret=z5f74vctn8",
                "__class__": "Sabre\\HTTP\\Request"
            }, {
                "__class__": "Sabre\\HTTP\\Response"
            }]
        }, {
            "file": "\/var\/www\/nc.mydomain.com\/htdocs\/apps\/dav\/appinfo\/v1\/webdav.php",
            "line": 80,
            "function": "exec",
            "class": "Sabre\\DAV\\Server",
            "type": "->",
            "args": []
        }, {
            "file": "\/var\/www\/nc.mydomain.com\/htdocs\/remote.php",
            "line": 163,
            "args": ["\/var\/www\/nc.mydomain.com\/htdocs\/apps\/dav\/appinfo\/v1\/webdav.php"],
            "function": "require_once"
        }],
        "File": "\/var\/www\/nc.mydomain.com\/htdocs\/apps\/encryption\/lib\/Crypto\/Crypt.php",
        "Line": 487,
        "Hint": "Ung\u00fcltige Signatur",
        "CustomMessage": "--"
    },
    "userAgent": "Mozilla\/5.0 (X11; Linux x86_64; rv:66.0) Gecko\/20100101 Firefox\/66.0",
    "version": "15.0.4.0"
}
```

</details>

**Comment by juliushaertl** [comment] 2021-01-08 16:07
Is this still an issue? Are you using a master key with encryption being enabled?

**Comment by apiraino** [comment] 2021-01-08 16:21
Hi @juliushaertl I can't really say, I've stopped using Collabora since then.

Feel free to close this issue or keep it open for other purposes.

**Comment by juliushaertl** [comment] 2021-01-11 07:17
OK, let me close it then since i couldn't reproduce any issue with encryption enabled. If anyone still encounters an issue feel free to just open a new one then.

**Closed by juliushaertl** 2021-01-11 07:17 UTC
Labels: bug, info needed
