### ISSUE TITLE
Collabora online not working on mobile at all

### ISSUE THREAD

**Issue by l3eochan** [nextcloud/richdocuments#2910] opened 2023-04-10 18:42 UTC
**Describe the bug**
Collabora does not work on mobile, when you try to open a word, excel or powerpoint file, it just loads endlessly and you have the "loading takes very long..." messages that appear at the bottom. 

**To Reproduce**
1. Open nextcloud app on a phone or tablet
2. Select a random document or create a new one
3. Try to open it 
4. It's stuck in an endless loading

**Expected behavior**
Document should open in the editor like it does in a browser

**Client details:**
 - OS: Android 13
 - Device: Samsung Galaxy Tab S5e

## Server details

**Operating system**: Ubuntu 22.04.2 LTS

**Web server:** Apache 2 2.4.52

**Database:** MariaDB

**PHP version:** php 8.1.2

**Nextcloud version:** NC 26.0.0

**Version of the richdocuments app** 8.0.0

**Version of Collabora Online** 22.05.12.3

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
Nothing
```

#### Browser log
```
Not obtainable from NC mobile app
```

</details>

**Comment by small1** [comment] 2023-04-10 18:44
Duplicate of #2873

**Closed** 2023-04-11 12:04 UTC
