### ISSUE TITLE
Online document is not refreshed

### ISSUE THREAD

**Issue by oparoz** [nextcloud/richdocuments#25] opened 2017-02-27 13:28 UTC
### Steps to reproduce

1. Open the document online
1. Ask a friend to open the document online
1. Take a screenshot
1. Close the document
1. Refresh the document on the desktop
1. Open the document online again
1. Take another screenshot
1. Compare screenshots

*Note: the friend keeps the doc opened the whole time*

### Expected behaviour

The screenshots should be different

### Actual behaviour

The screenshots are the same.

If I download the file instead I get the latest version. Collabora just refuses to show it online.
I suspect this happens because someone is still viewing the old version, but it shouldn't have an impact.

**Comment by juliushaertl** [comment] 2019-01-17 22:59
Cannot reproduce anymore, so closing for now.

**Closed by juliushaertl** 2019-01-17 22:59 UTC
Labels: bug
