### ISSUE TITLE
after closing a document the current directory is lost 

### ISSUE THREAD

**Issue by wdehoog** [nextcloud/richdocuments#644] opened 2019-09-30 13:05 UTC
After closing collabora-online the current directory is lost and the user is back in it's home directory.

The address bar shows:

Before opening: 
../nextcloud/index.php/apps/files/?dir=/X/Y&fileid=16766

While editing:
.../nextcloud/index.php/apps/files/?dir=/X/Y&fileid=16766

After closing:
.../nextcloud/index.php/apps/files/?dir=/&fileid=104

**Client details:**
firefox

## Server details

**Web server:**
Apache 2.4

**Database:**

**PHP version:**

**Nextcloud version:**
16.0.4

**Version of the richdocuments app**
3.4.2

**Version of Collabora Online**
4.0.6

**Comment by gary-kim** [comment] 2019-10-08 08:06
I can confirm that this is an issue.

**Comment by juliushaertl** [comment] 2019-10-08 08:23
I cannot reproduce that. @gary-kim Are you also on 16? Does it always happen? It could be some race condition with the file list reload and history handling that is done on close.

**Comment by gary-kim** [comment] 2019-10-08 08:33
Yes, I'm on 16. It always happens but sometimes, it still loads the correct contents of the directory while losing the directory path. So the breadcrumb will show root but the directory contents will be for the directory you were in.

**Comment by tk7936** [comment] 2019-10-09 11:01
I have the same Problem but on Edge not Firefox, On Firefox  it works fine for me. Very annoying for my Edge Users.

**Comment by andrem1987** [comment] 2019-10-09 12:14
We have the same Problem. We are running Nextcloud 16.0.5, richdocuments 3.4.2 and Collabora 4.0.6.

**Comment by manu-p** [comment] 2019-11-05 17:13
Same here with FF, but not with Brave nor Chromium. 
NC 16.0.5 + Collabora Online 3.4.3

**Comment by tk7936** [comment] 2019-11-11 02:18
It has started on Firefox for me as well now. It started after update to FF 70.0.0. Now Chrome is the only Browser still working. Im in big trouble if it fails there to. Hope it wasnt a mistake to trust in Nextcloud.

**Comment by xtrasimplicity** [comment] 2019-11-11 07:51
Same issue here, with some browser combinations. Not sure why, exactly. Will investigate further when I get a moment. 👍

**Comment by g4rf** [comment] 2019-11-11 14:36
We have two installations of Nextcloud on different servers: One with this issue, the other one not. They have nearly the same configuration and apps, the biggest difference: The working one runs on **Apache** with **HTTP/1.1**, the buggy one on **Nginx** with **HTTP/2.0**.

I did a check in the network analysis of the developer tools of Firefox and there is a difference in the http calls: The buggy one does a **double** request to the directory after closing the document.
```
code: 207
type: PROPFIND
address: https://*****.de/remote.php/dav/files/theuser/
```
The working one sends this request only one time and to the right sub-directory, not the root directory.

Hope, that'll help. If you need more information I'll try to provide more.

**Comment by xtrasimplicity** [comment] 2019-11-11 20:32
It looks like this is a Firefox issue, not a HTTP1.1/2.0 issue. I've posted the headers for the AJAX requests that are triggered when File > Close Document is clicked.

**Firefox (Broken)**
```
PROPFIND /remote.php/dav/files/username/folder/ HTTP/1.1
Host: ...
User-Agent: Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:70.0) Gecko/20100101 Firefox/70.0
Accept: */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
X-Requested-With: XMLHttpRequest
requesttoken: .....
Depth: 1
Content-Type: application/xml; charset=utf-8
Content-Length: 621
Origin: https://.......
Connection: keep-alive
Cookie: ...
Pragma: no-cache
Cache-Control: no-cache
```

```
PROPFIND /remote.php/dav/files/username/ HTTP/1.1
Host: ....
User-Agent: Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:70.0) Gecko/20100101 Firefox/70.0
Accept: */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
X-Requested-With: XMLHttpRequest
requesttoken: ....
Depth: 1
Content-Type: application/xml; charset=utf-8
Content-Length: 621
Origin: https://...
Connection: keep-alive
Cookie: ....
Pragma: no-cache
Cache-Control: no-cache
```

When using Chrome, as noted by @g4rf above, there's only single XHR request to the parent directory rather than one to the parent directory **and** one to the user's home directory.

**Comment by xtrasimplicity** [comment] 2019-11-11 20:57
Interestingly, it looks like Collabora is detecting Firefox as a **mobile** client. When closing a document in Firefox, `callMobileMessage('close')` is called (defined in https://github.com/nextcloud/richdocuments/blob/37a7c7372105bdc4ee888b0c62a18ab5780e0553/src/helpers/mobile.js), but is **not** called when using Chrome*.

* I'm sure of this, as `callMobileMessage`'s function definition logs to the console:
```javascript
const callMobileMessage = (messageName, attributes) => {
	console.debug('callMobileMessage', messageName, attributes)
        ....
}
```

**Comment by tk7936** [comment] 2019-11-11 21:22
I do have this Problem on edge also, not sure if that means its the same code issue.

**Comment by xtrasimplicity** [comment] 2019-11-13 21:39
After logging all XHR requests and the current URL prior to the request, with the JS below, it's appears that the issue isn't actually with the Collabora implementation, but rather something with NextCloud itself.

```
 var old = XMLHttpRequest.prototype.open;
    XMLHttpRequest.prototype.open = function(method, url) {
      console.log("Starting ", method, "request to: ", url, ". Current URL is ", location.href);

      old.apply(this, arguments);
    };
```
When closing a document with Firefox, the following is printed to the console:
![Firefox](https://user-images.githubusercontent.com/9316813/68805614-48011100-06b8-11ea-959d-606c097067f0.png)

Whereas when closing a document with Chrome, the following is printed to the console:
![Chrome](https://user-images.githubusercontent.com/9316813/68805771-93b3ba80-06b8-11ea-8a08-95c48b9b9602.png)

On Firefox, after the first `PROPFIND` request, the current URL is changed to `/app/files/?#`, which then forces the user's home directory to be loaded (hence the subsequent `PROPFIND` request).

On Chrome, the user is never redirected to `/app/files/?#`, so the user's home directory isn't loaded.

When updating the JS above to include a `debugger` call before the  XHR request, the following call stack can be seen.
![Call stack](https://user-images.githubusercontent.com/9316813/68806483-1721db80-06ba-11ea-816c-fd01da664871.png)

Will investigate further when I get another moment.

**Comment by g4rf** [comment] 2019-11-14 15:11
> When using Chrome, as noted by @g4rf above, there's only single XHR request to the parent directory rather than one to the parent directory **and** one to the user's home directory.

To make it clear: I used the same Firefox (actual version on Ubuntu) to test the two nextcloud setups. On the Nginx one it made two requests to the users root, on the Apache one it made one request to the current directory.

**Comment by expert-geeks** [comment] 2019-11-17 09:58
same issue nc 17

**Comment by danxuliu** [comment] 2019-11-25 14:24
If I am not mistaken the problem comes from [`location.hash = ""`](https://github.com/nextcloud/richdocuments/blob/8b7cb593cfd7a96746bd3aab087b5464af7185d9/src/viewer.js#L197) and the fact that some browsers (like Firefox) trigger `onpopstate` and some browsers (like Chromium) do not (you can [try it here](https://jsfiddle.net/mgs0r9fy/)).

The Files app [listens to _popstate_ events](https://github.com/nextcloud/server/blob/master/apps/files/js/app.js#L200) and [triggers _urlChanged_ events](https://github.com/nextcloud/server/blob/master/apps/files/js/app.js#L297), which cause [the file list to change to the new directory](https://github.com/nextcloud/server/blob/master/apps/files/js/filelist.js#L736). When the _RichDocuments_ viewer is closed it [first clears the state (the _?dir=/XXX&fileid=YYY_ part) of the URL](https://github.com/nextcloud/richdocuments/blob/8b7cb593cfd7a96746bd3aab087b5464af7185d9/src/viewer.js#L196) (note that this [does not trigger an _onpopstate_ event](https://developer.mozilla.org/en-US/docs/Web/API/WindowEventHandlers/onpopstate)) and then sets `location.hash = ""`. In Chromium no `popstate` event is triggered, so everything works as expected. But in Firefox this triggers a `popstate` event, and as the state was cleared the URL now refers to the root folder and the file list changes to it.

**Comment by juliushaertl** [comment] 2019-11-25 16:05
Thanks a lot @danxuliu for digging into that. The strange thing is that i still don't see the behaviour with the latest FF, but i could reproduce it with ESR indeed. Not sure what is wrong there. However removing fixes the issue and I cannot see a reason why this would still be needed, even from the original introducing commit https://github.com/nextcloud/richdocuments/commit/d106de7102ef81e7ac3f37022fcfd1f7bcb39062

**Closed** 2019-11-26 08:29 UTC
Labels: 1. to develop, bug

**Comment by xtrasimplicity** [comment] 2019-11-27 01:21
Thanks for releasing this as part of v3.4.5, @juliushaertl!

**Comment by tk7936** [comment] 2019-11-27 01:48
just tested the update, all works again! Thanks to everyone!

**Comment by manu-p** [comment] 2019-11-27 08:21
Thanks very much to all of you involved in this issue resolution!
