### ISSUE TITLE
Migration Database Error

### ISSUE THREAD

**Issue by SamKer** [nextcloud/richdocuments#1054] opened 2020-06-24 09:35 UTC
### Steps to reproduce
1. upgrade richdocuments 3.2.4 to 3.7.0

### Expected behaviour
basic usage of collabora

### Actual behaviour
fatal error 

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
```
{"reqId":"CQ2TT6wB1EovkARUKiWL","level":3,"time":"2020-06-24T08:24:39+00:00","remoteAddr":"*.*.*.*","user":"me","app":"richdocuments","method":"GET","url":"\/partage\/index.phpdocuments\/index?fileId=431426&requesttoken=rfMvjP
x9K%2FV3vj6y5AnEQtR4y1vpTDZHADg0bxOlkYM%3D%3An4B3w7tFXJIv32zXqU6wGJEtnBGiL0cIU2hRRFfm5eQ%3D","message":{"Exception":"D
octrine\\DBAL\\Exception\\InvalidFieldNameException","Message":"An exception occurred while executing 'INSERT INTO \"o
c_richdocuments_wopi\"(\"fileid\",\"owner_uid\",\"editor_uid\",\"version\",\"canwrite\",\"server_host\",\"token\",\"ex
piry\",\"template_destination\",\"hide_download\",\"direct\",\"is_remote_token\",\"template_id\") VALUES(?,?,?,?,?,?,?
,?,?,?,?,?,?)' with params [431426, \"me\", \"me\", 0, true, \"https:\\\/\\\/mycloud\\\/jjj\\\/\", \"LQAP6mL85uMRulVvCngskWpeDDtQOHDM\", 1592988879, 0, false, false, false, 0]:\n\nSQLSTATE[42703]: Undefined column: 7 ERROR:  column \"template_id\" of relation \"oc_richdocuments_wopi\" does not exist\nLINE 1: ...ation\",\"hide_download\",\"direct\",\"is_remote_token\",\"template_
```
</details>

<details>
<summary>same error for </summary>
same error on table richdocuments_wopi for column:
-  remote_server_token
- remote_server
- is_remote_token
- direct 
- hide_download
- template_id
</details>

**Comment by juliushaertl** [comment] 2020-06-24 14:01
Actually this is a duplicate of #917 so let's use that as it is the older one.

**Closed by juliushaertl** 2020-06-24 14:01 UTC
