### ISSUE TITLE
Office files not opening in Android app. Again...

### ISSUE THREAD

**Issue by kocherjj** [nextcloud/richdocuments#3511] opened 2024-03-03 21:54 UTC
**Describe the bug**
When I open an Office file in a browser, it opens using Collabora as expected. When I attempt to open it using the Android App, I just get a spinning blue circle.

**To Reproduce**
1. Go to an Office file in the Android App
2. Attempt to open the file
3. See error

**Expected behavior**
I expect the file to open and be editable like it used to.

**Screenshots**

![share_5115993043597462227](https://github.com/nextcloud/richdocuments/assets/50033443/f2c8be11-61f2-4afe-9ec7-ae9268ea5506)

**Client details:**
 - OS: Android 14
 - Browser N/A
 - Version 3.27.0
 - Device: Pixel 6 Pro, Galaxy Tab, Samsung S22, other Android devices...

## Server details

**Operating system**: Ubuntu 22.04.4 LTS

**Web server:** Apache/2.4.52 (Ubuntu)

**Database:** MariaDB

**PHP version:** PHP 8.1.2-1ubuntu2.14 (cli) (built: Aug 18 2023 11:41:11) (NTS)

**Nextcloud version:** 28.0.1, 28.0.2, 28.0.3

**Version of the richdocuments app** 8.3.1, and previous recent versions

**Version of Collabora Online** 23.05.9.2 

**Configuration of the richdocuments app**
```
{
    "apps": {
        "richdocuments": {
            "disable_certificate_verification": "yes",
            "enabled": "yes",
            "installed_version": "8.3.1",
            "mobile_editing": "yes",
            "public_wopi_url": "https:\/\/collabora.mydomain.net",
            "types": "prevent_group_restriction",
            "wopi_allowlist": "<reverseproxyip>",
            "wopi_url": "https:\/\/collabora.mydomain.net"
        }
    }
}

```

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
Nothing is logged in this location when a file open is attempted, either from a browser when it succeeds, or an Android device when it fails. 
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
No Browser log relevant in the Android App.
```

</details>

**Comment by joshtrichards** [comment] 2024-03-04 20:17
> Version 3.27.0

This has already been fixed.

Duplicate of nextcloud/android#12338 
Fixed in nextcloud/android#12350 
Fixed in >v3.27.0

It was a regression specific to v3.27.0.

**Closed by joshtrichards** 2024-03-04 20:17 UTC

**Comment by joshtrichards** [comment] 2024-03-04 23:44
@contactnat I'm telling you that v3.27.0 of the Android client does *not* function with Collabora/Nextcloud Office. We've already reproduced the behavior the OP reported. And fixed it. OP is running the buggy version. 

I'm not sure what you're seeing in v3.28.0 (and I'm not seeing any problems personally in >=v3.28.0 builds, but I definitely could reproduce the earlier v3.27.0 bug). I'd be happy to try to look at your situation, but it is not the OP's so likely doesn't belong here in this issue. Feel free to send along a link here to somewhere I can see your config details however (either a dedicated Issue or a post on the Help Forum).

**Comment by contactnat** [comment] 2024-03-05 00:35
> @contactnat I'm telling you that v3.27.0 of the Android client does _not_ function with Collabora/Nextcloud Office. We've already reproduced the behavior the OP reported. And fixed it. OP is running the buggy version.
> 
> I'm not sure what you're seeing in v3.28.0 (and I'm not seeing any problems personally in >=v3.28.0 builds, but I definitely could reproduce the earlier v3.27.0 bug). I'd be happy to try to look at your situation, but it is not the OP's so likely doesn't belong here in this issue. Feel free to send along a link here to somewhere I can see your config details however (either a dedicated Issue or a post on the Help Forum).
> 
> EDIT: I can't find any reports involving this situation and v3.28.0 that we've closed on this end (or that are open for that matter). Every single one predates v3.28.0.

ah ok, sorry about that, must be my issue, I will open a new issue when I get some time, but might just run over my setup first. thanks for the helpful response though.  attached is a screenshot of the error I get, but like I said, I will open a new issue. 
![Screenshot_20240305_132408_Device care](https://github.com/nextcloud/richdocuments/assets/81800839/c63e9e70-b9e7-499c-92f0-34b2783bd108)

**Comment by joshtrichards** [comment] 2024-03-05 02:29
@contactnat That screenshot suggests your Android device has an app installed on it that is called "Collabora Office" and it's crashing or something. I don't think that's us.

**Comment by contactnat** [comment] 2024-03-05 03:18
> @contactnat That screenshot suggests your Android device has an app installed on it that is called "Collabora Office" and it's crashing or something. I don't think that's us.

that is the error that the nextcloud app gives when trying to open a document via the collabora office app, it suggests the nextcloud bug is causing the collabora app to close prematurely. your question makes me curious how you open docs via the android nextcloud app - do you not use the collabora app - if not how do you do it? thanks

**Comment by joshtrichards** [comment] 2024-03-05 04:02
> that is the error that the nextcloud app gives when trying to open a document via the nextcloud app --> open in = collabora office app, it suggests the nextcloud bug is causing the collabora app to close prematurely. your question makes me curious how you open docs via the android nextcloud app - do you not use the collabora app - if not how do you do it? thanks

This repository is for `richdocuments` (the Nextcloud Office integration app - a server-side app) which fully integrates a Collabora Online deployment into Nextcloud Server. Once that's in place, all Nextcloud clients can transparently open and collaborate on these documents without leaving the Nextcloud client or installing an office suite on every device.

You're using Collabora's external native Android app it sounds like. That has zero to do with `richdocuments`, but is another way of doing things. :-)

For what it's worth, I installed (from the Google Play Store) the native Android Collabora Office app (that I believe you're using) just now and was able to use it the way you're using it (e.g. using *Download/Sync* on a target file in the Nextcloud Android client then using *Open with* and choosing Collabora Office).

It also seems to support Android's Document Providers interface, which is great because the Nextcloud Android client provides access to all files in your private cloud via that to other apps that support it. So you can just open your CO app and select your Nextcloud cloud in the file list to open files you want directly. No need to *Download/Sync* files first or mess with *Open with* because the Nextcloud Android client provides those files as essentially a virtual drive.

But none of this has to do with richdocuments. :-)

Since this is getting out of scope for here, I suggest popping over to the Nextcloud Help Forum - https:://help.nextcloud.com - to see what others are doing.
