### ISSUE TITLE
richdocuments slow

### ISSUE THREAD

**Issue by SimplyCorbett** [nextcloud/richdocuments#1673] opened 2021-07-17 12:25 UTC
Steps to reproduce:

Follow instructions here: https://nextcloud.com/collaboraonline/

Load a document in collabora from nextcloud. Wait ~40 seconds for collabora to go from initializing to a fully loaded document.

Specs:

Main server:

Nextcloud 22
PHP 8.0.8
MySQL 8.0.23
Debian 10
Redis is in use as distributed and file locking.

Collabora is running on a local KVM. It is not on the same server.

![u3kjabXcW5](https://user-images.githubusercontent.com/7935624/126036768-51e50a3f-b90c-4317-82a0-830fe983b5d9.gif)

**Comment by baldrianbandit** [comment] 2021-08-18 07:32
I can confirm that. Initialization takes about 10 seconds now, independent from document type and size.

Arch Linux 5.13.10
Nextcloud 22.1.0
Richdocuments 4.2.1
Collabora/code latest image 2021-08-18

Cannot find any warning nor error yet. Although not sure if the delay is depending on the app or the document server.

**Comment by juliushaertl** [comment] 2021-10-05 15:25
Could you check if there are any long running requests that may block loading in the browsers network console? 

As for some further debugging you could also enable response time logging on your webserver to see which requests actually take long that may come from collabora to nextcloud.

**Comment by juliushaertl** [comment] 2021-12-06 21:51
Closing due to no feedback and I cannot reproduce any general slowdown. Feel free to reopen with the additional requested information.

**Closed by juliushaertl** 2021-12-06 21:51 UTC

**Comment by baldrianbandit** [comment] 2022-01-29 14:53
The issue is gone for me using Collabora Online 5.0.1 and Docker release 1.11.1.4.1.
