### ISSUE TITLE
Office.vue:198 FAILED

### ISSUE THREAD

**Issue by shaun-ba** [nextcloud/richdocuments#2016] opened 2022-02-03 10:56 UTC
**Describe the bug**
Intermittant failure to load documents in Nextcloud Office (Collabora)

**To Reproduce**
Open a document.

**Expected behavior**
It should open without error

**Screenshots**
![d65ab57c4c7dcfdb8d30301285d4157158209ce7](https://user-images.githubusercontent.com/3339587/152329497-9038b8fa-8a26-4975-860f-303cf6f007e5.jpeg)

**Client details:**
 - OS: Linux
 - Browser: Brave/Chrome/Firefox

## Server details
**PHP version:**
7.4

**Nextcloud version:**

23.0.1 RC1

**Version of the richdocuments app**
Latest

**Version of Collabora Online**
Latest

<details>
<summary>Logs</summary>

```
Office.vue:198 FAILED
(anonymous)	@	Office.vue:198
setTimeout (async)		
load	@	Office.vue:197
mounted	@	Office.vue:184
await in mounted (async)		
We	@	vue.runtime.esm.js:1863
un	@	vue.runtime.esm.js:4235
insert	@	vue.runtime.esm.js:3158
D	@	vue.runtime.esm.js:6390
vo.nodeOps	@	vue.runtime.esm.js:6609
e._update	@	vue.runtime.esm.js:3963
r	@	vue.runtime.esm.js:4081
bn.get	@	vue.runtime.esm.js:4495
bn.run	@	vue.runtime.esm.js:4570
yn	@	vue.runtime.esm.js:4326
(anonymous)	@	vue.runtime.esm.js:1989
et	@	vue.runtime.esm.js:1915
Promise.then (async)		
Xe	@	vue.runtime.esm.js:1942
it	@	vue.runtime.esm.js:1999
(anonymous)	@	vue.runtime.esm.js:4418
bn.update	@	vue.runtime.esm.js:4560
de.notify	@	vue.runtime.esm.js:730
set	@	vue.runtime.esm.js:1055
Cn.set	@	vue.runtime.esm.js:4644
(anonymous)	@	Viewer.vue:405
c	@	runtime.js:63
(anonymous)	@	runtime.js:294
(anonymous)	@	runtime.js:119
ka	@	viewer-main.js?v=f26e428a-0:2
a	@	viewer-main.js?v=f26e428a-0:2
Promise.then (async)		
ka	@	viewer-main.js?v=f26e428a-0:2
a	@	viewer-main.js?v=f26e428a-0:2
(anonymous)	@	viewer-main.js?v=f26e428a-0:2
(anonymous)	@	viewer-main.js?v=f26e428a-0:2
openFile	@	Viewer.vue:363
file	@	Viewer.vue:277
We	@	vue.runtime.esm.js:1863
bn.run	@	vue.runtime.esm.js:4584
yn	@	vue.runtime.esm.js:4326
(anonymous)	@	vue.runtime.esm.js:1989
et	@	vue.runtime.esm.js:1915
Promise.then (async)		
Xe	@	vue.runtime.esm.js:1942
it	@	vue.runtime.esm.js:1999
(anonymous)	@	vue.runtime.esm.js:4418
bn.update	@	vue.runtime.esm.js:4560
de.notify	@	vue.runtime.esm.js:730
set	@	vue.runtime.esm.js:1055
value	@	Viewer.js:183
na	@	FilesActionHandler.js:36
action	@	merged-index.js?v=f26e428a-0:2983
_onClickFile	@	merged-index.js?v=f26e428a-0:4917
Xe	@	_executeBound.js:8
(anonymous)	@	bind.js:10
(anonymous)	@	restArguments.js:16
dispatch	@	jquery.js:5183
g.handle	@	jquery.js:4991
```

**Comment by juliushaertl** [comment] 2022-02-14 10:22
Can you maybe post the full log output from the browser console? Looks similar to https://github.com/nextcloud/richdocuments/issues/2017

**Comment by joergmschulz** [comment] 2022-02-22 17:16
here this effect can be created when I rename my nextcloud installation (server.somewhere.com to server2.somewhere.com). Yes, all other apps work after I change the overwrite sections in the nc config files.
It happens regardless whether or not I use different / new browsers. The log files and console.log don't give away any information worth pasting here. Still investigating ....

**Comment by isdnfan** [comment] 2022-07-04 20:02
I see this issue on my docker installation running Nextcloud 24 and Collabora 21.11.5.3.1 (and 22.05.. as well). The error shows for short time and then the document load successfully. The period how long the error is shown slightly differs. So far I can see the problem is due to timeout defined in [Office.vue line 201](https://github.com/nextcloud/richdocuments/blob/7a387340a858a24a0e4c121903611d5b9c566dc5/src/view/Office.vue#L201) which is kind of expected in my system where containers are stored on magnetic disks and Collabora starts pretty slowly.. is there a way to extend this timeout?

the longest single request I see on the browser is:
https://mynextcloud.tld/apps/richdocuments/index?fileId=123456&requesttoken=E682.....8%3D&path=%2Fmydocument.ods
it takes 4171 msec

**Comment by eBug** [comment] 2022-08-10 11:12
> I see this issue on my docker installation running Nextcloud 24 and Collabora 21.11.5.3.1 (and 22.05.. as well). The error shows for short time and then the document load successfully. The period how long the error is shown slightly differs. So far I can see the problem is due to timeout defined in [Office.vue line 201](https://github.com/nextcloud/richdocuments/blob/7a387340a858a24a0e4c121903611d5b9c566dc5/src/view/Office.vue#L201) which is kind of expected in my system where containers are stored on magnetic disks and Collabora starts pretty slowly.. is there a way to extend this timeout?
> 
> the longest single request I see on the browser is: https://mynextcloud.tld/apps/richdocuments/index?fileId=123456&requesttoken=E682.....8%3D&path=%2Fmydocument.ods it takes 4171 msec
> 
> UPDATE: I solved my issue. The root cause was failing/long DNS resolution inside docker against DNS server running on same docker instance. This resulted in DNS requests to each ~docker container~ public fqdn hosted on same system took 5 or more seconds effectively running into the timeout mentioned before. Now once DNS resolution works fine richdocuments/Collabora runs fast as never did - documents loads in less than 2-3 secs, not more timeouts..

Could you give more details on how you solved the DNS problem?

**Comment by psarvaiya** [comment] 2023-02-28 13:50
Hi team,

I am facing the similar issue. Document loading fails in 15 secs, and it automatically loads completely, it takes around 27-30 secs.
Is there a way I can increase the timeout from 15 secs to 45 secs, that will reduce this probability of getting this.

**Comment by Mannshoch** [comment] 2023-08-11 15:04
Any news on that?

**Comment by Mannshoch** [comment] 2023-08-21 07:19
In my case I have the error, I assume it's not the same timeout like above described.
`loadingTimeout Office.vue:212`

**Comment by juliushaertl** [comment] 2024-07-31 15:53
We should have way better checks and hints for admins these days that help figure out why a document cannot be opened when configuring a Collabora server so I'll close this. If anyone still has troubles it would be interesting to have an individual ticket to investigate the reason in those specific cases and maybe further improve admin guidance

**Closed** 2024-07-31 15:54 UTC
Labels: bug, info needed, 1. to develop
