### ISSUE TITLE
Wrong color of selected buttons at the top bar.

### ISSUE THREAD

**Issue by Vexisu** [nextcloud/richdocuments#2273] opened 2022-06-11 09:54 UTC
**Describe the bug**
When using a built-in Nextcloud dark theme, buttons of selected options have a nearly black background. That makes icons and text in them nearly unreadable. It happens in compact mode, as well as in tabs mode.

**To Reproduce**
1. Enable dark theme in Accessibility options.
2. Open any document in Collabora and check i.e. bold text option.

**Expected behavior**
The buttons background should be white with a theme's main color hint (in my case #faf4ed).

**Screenshots**
#### Current
![Zrzut ekranu z 2022-06-11 11-33-00](https://user-images.githubusercontent.com/18292992/173182286-a6146dc0-0ebf-46b4-939e-565d66f9cba4.png)
![Zrzut ekranu z 2022-06-11 11-33-35](https://user-images.githubusercontent.com/18292992/173182312-20ca5790-83a8-432f-ae01-311fe344714c.png)
![Zrzut ekranu z 2022-06-11 11-34-15](https://user-images.githubusercontent.com/18292992/173182340-afbff8a8-38bd-4533-8d64-83a6163c1d91.png)
![Zrzut ekranu z 2022-06-11 11-34-43](https://user-images.githubusercontent.com/18292992/173182358-a4e27b53-cd55-47e3-b36a-35e833394de4.png)

#### Expected
![Zrzut ekranu z 2022-06-11 11-39-34](https://user-images.githubusercontent.com/18292992/173182591-f007f4d1-0f7c-4bfb-af2e-5fbf159e8f0e.png)

**Client details:**
 - OS: Fedora
 - Browser: Firefox, Epiphany
 - Version: 100.0.2 (64 bit), 42.2
 - Device: desktop

## Server details

**Operating system**: CentOS 8 Stream LXC

**Web server**:  Apache/2.4.37 (centos)

**Database**: MariaDB

**PHP version:** 7.4.29

**Nextcloud version:** 24.0.1

**Version of the richdocuments app**: 6.0.1

**Version of Collabora Online**: CODE ver. 21.11.402

**Comment by thebearon** [comment] 2022-06-24 20:20
Let's close this as duplicate of https://github.com/CollaboraOnline/online/issues/4592 .

**Closed by thebearon** 2022-06-24 20:20 UTC
