### ISSUE TITLE
Document can not be saved to storage. - richdocuments 3.5.3

### ISSUE THREAD

**Issue by JonnyTischbein** [nextcloud/richdocuments#933] opened 2020-04-29 08:46 UTC
### Steps to reproduce
1. Install Nextcloud 18.0.4
2. Enable basic encryption module (probably related ?)
3. Setup Collabora Instance (via docker)
4. Install and Activate collabora/richdocument app version 3.5.3 or 3.7.0
5. Try to edit / create textdocument and save content.

### Expected behaviour
The app saves current changes without an error.

### Actual behaviour
The app does not save current changes displays: 

    Document can not be saved on storage. Check your permissions or contact administrator of your storage server.
Probably related to #917 https://github.com/nextcloud/richdocuments/issues/781

### Workaround
1. Deactivate and remove collabora/richdocument app 3.5.3
2. Download and extract collabora/richdocument app version 3.5.0 to `{nextcloud-root}/apps/`, e.g. via [apps.nextcloud.com](https://apps.nextcloud.com/apps/richdocuments/releases?platform=18#18)
3. Activate the app
4. Open document and save changes

### Server configuration

**Operating system**:
`Linux xxx.org 4.19.0-6-amd64 #1 SMP Debian 4.19.67-2+deb10u2 (2019-11-11) x86_64 GNU/Linux`

**Web server:**
`nginx/stable,stable,now 1.14.2-2+deb10u1 all [installed]`

**Database:**
`mariadb-server/stable,now 1:10.3.22-0+deb10u1 all [installed]`

**PHP version:**
`php7.3/stable,now 7.3.14-1~deb10u1 all [installed]`

**Nextcloud version:** (see Nextcloud admin page)
Nextcloud 18.0.4

**Updated from an older Nextcloud/ownCloud or fresh install:**
- [x] Updated from an older Nextcloud (18.02)

**Where did you install Nextcloud from:**
https://nextcloud.com/install/#instructions-server
**Signing status:**
<details>
<summary>Signing status</summary>

```
https://cloud.xxx.org/settings/integrity/failed:
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.4.0
  - admin_audit: 1.8.0
  - bruteforcesettings: 1.6.0
  - calendar: 2.0.3
  - checksum: 0.4.4
  - cloud_federation_api: 1.1.0
  - comments: 1.8.0
  - contacts: 3.3.0
  - dav: 1.14.0
  - encryption: 2.6.0
  - federatedfilesharing: 1.8.0
  - federation: 1.8.0
  - files: 1.13.1
  - files_pdfviewer: 1.7.0
  - files_rightclick: 0.15.2
  - files_sharing: 1.10.1
  - files_trashbin: 1.8.0
  - files_versions: 1.11.0
  - files_videoplayer: 1.7.0
  - logreader: 2.3.0
  - lookup_server_connector: 1.6.0
  - notifications: 2.6.0
  - oauth2: 1.6.0
  - password_policy: 1.8.0
  - photos: 1.0.0
  - privacy: 1.2.0
  - provisioning_api: 1.8.0
  - recommendations: 0.6.0
  - richdocuments: 3.5.0
  - serverinfo: 1.8.0
  - settings: 1.0.0
  - sharebymail: 1.8.0
  - spreed: 8.0.8
  - systemtags: 1.8.0
  - tasks: 0.12.2
  - text: 2.0.0
  - theming: 1.9.0
  - twofactor_backupcodes: 1.7.0
  - updatenotification: 1.8.0
  - viewer: 1.2.0
  - workflowengine: 2.0.0
Disabled:
  - activity
  - documents
  - files_external
  - firstrunwizard
  - nextcloud_announcements
  - ownnote
  - support
  - survey_client
  - user_lda
```
</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": {
            "1": "cloud.xxx.org",
            "2": "cloud.xxxx.onion"
        },
        "overwrite.cli.url": "https:\/\/cloud.xxx.org",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "18.0.4.2",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "theme": "",
        "loglevel": 2,
        "maintenance": false,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "app_install_overwrite": [
            "tasks",
            "documents",
            "ownnote"
        ],
        "mysql.utf8mb4": true,
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}
```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** yes

**Are you using an external user-backend, if yes which one:** no

### Collabora configuration
Installed via dockerhub https://hub.docker.com/r/collabora/code

**Version**: `collabora/code                        latest              e2528d821ea7        12 days ago         1.39GB (29.04.2020)`

### Client configuration
**Browser:** `firefox/focal,now 75.0+build3-0ubuntu1 amd64 [installed,automatic]`

**Operating system:** `Linux xxxx 5.4.0-26-generic #30-Ubuntu SMP Mon Apr 20 16:58:30 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

#### Collabora log
<details>
<summary>Collabora log</summary>

```
ESC[39mwsd-00008-00008 2020-04-29 05:21:12.917446 [ loolwsd ] INF  WSD initialization complete: setting log-level to [warning] as configured.| wsd/LOOLWSD.cpp:3546ESC[0m
ESC[35mwsd-00008-00036 2020-04-29 05:21:24.949272 [ websrv_poll ] WRN  client - server version mismatch, disabling browser cache. Expected: adadb63| wsd/FileServer.cpp:284ESC[0m
ESC[1mESC[31mwsd-00008-00039 2020-04-29 05:21:30.278520 [ docbroker_001 ] ERR  Unexpected response to WOPI::PutFile : 500Cannot save file to WOPI storage uri [https://owncloud.riotcat.org/index.php/apps/richdocuments/wopi/files/159857_ocmnh2pks8dp/contents?access_token=u
lX68gyW0aP92ywlhD05scDMuuvnfVDR&access_token_ttl=0]. Error: | wsd/Storage.cpp:1112ESC[0m
ESC[1mESC[31mwsd-00008-00039 2020-04-29 05:21:30.278770 [ docbroker_001 ] ERR  Failed to save docKey [/index.php/apps/richdocuments/wopi/files/159857_ocmnh2pks8dp] to URI [https://owncloud.riotcat.org/index.php/apps/richdocuments/wopi/files/159857_ocmnh2pks8dp?access_tok
en=ulX68gyW0aP92ywlhD05scDMuuvnfVDR&access_token_ttl=0]. Notifying client.| wsd/DocumentBroker.cpp:1083ESC[0m
ESC[1mESC[31mwsd-00008-00039 2020-04-29 05:23:44.652482 [ docbroker_001 ] ERR  Unexpected response to WOPI::PutFile : 500Cannot save file to WOPI storage uri [https://owncloud.riotcat.org/index.php/apps/richdocuments/wopi/files/159857_ocmnh2pks8dp/contents?access_token=u
lX68gyW0aP92ywlhD05scDMuuvnfVDR&access_token_ttl=0]. Error: | wsd/Storage.cpp:1112ESC[0m
ESC[1mESC[31mwsd-00008-00039 2020-04-29 05:23:44.652728 [ docbroker_001 ] ERR  Failed to save docKey [/index.php/apps/richdocuments/wopi/files/159857_ocmnh2pks8dp] to URI [https://owncloud.riotcat.org/index.php/apps/richdocuments/wopi/files/159857_ocmnh2pks8dp?access_tok
en=ulX68gyW0aP92ywlhD05scDMuuvnfVDR&access_token_ttl=0]. Notifying client.| wsd/DocumentBroker.cpp:1083ESC[0m
ESC[35mwsd-00008-00036 2020-04-29 05:24:04.273265 [ websrv_poll ] WRN  client - server version mismatch, disabling browser cache. Expected: adadb63| wsd/FileServer.cpp:284ESC[0m
ESC[1mESC[31mwsd-00008-00043 2020-04-29 05:24:09.076451 [ docbroker_002 ] ERR  Unexpected response to WOPI::PutFile : 500Cannot save file to WOPI storage uri [https://owncloud.riotcat.org/index.php/apps/richdocuments/wopi/files/159857_ocmnh2pks8dp/contents?access_token=B
qgpZ0EToCZ0MTSZJihiBCoab0sBR0uv&access_token_ttl=0]. Error: | wsd/Storage.cpp:1112ESC[0m
ESC[1mESC[31mwsd-00008-00043 2020-04-29 05:24:09.076896 [ docbroker_002 ] ERR  Failed to save docKey [/index.php/apps/richdocuments/wopi/files/159857_ocmnh2pks8dp] to URI [https://owncloud.riotcat.org/index.php/apps/richdocuments/wopi/files/159857_ocmnh2pks8dp?access_tok
en=BqgpZ0EToCZ0MTSZJihiBCoab0sBR0uv&access_token_ttl=0]. Notifying client.| wsd/DocumentBroker.cpp:1083ESC[0m
ESC[1mESC[31mwsd-00008-00048 2020-04-29 05:26:31.525075 [ docbroker_003 ] ERR  Unexpected response to WOPI::PutFile : 500Cannot save file to WOPI storage uri [https://owncloud.riotcat.org/index.php/apps/richdocuments/wopi/files/159857_ocmnh2pks8dp/contents?access_token=F
e7F4DNs0d14g8ARyRQQ9ScOYryA6jXo&access_token_ttl=0]. Error: | wsd/Storage.cpp:1112ESC[0m
ESC[1mESC[31mwsd-00008-00048 2020-04-29 05:26:31.525304 [ docbroker_003 ] ERR  Failed to save docKey [/index.php/apps/richdocuments/wopi/files/159857_ocmnh2pks8dp] to URI [https://owncloud.riotcat.org/index.php/apps/richdocuments/wopi/files/159857_ocmnh2pks8dp?access_tok
en=Fe7F4DNs0d14g8ARyRQQ9ScOYryA6jXo&access_token_ttl=0]. Notifying client.| wsd/DocumentBroker.cpp:1083ESC[0m
ESC[1mESC[31mwsd-00008-00058 2020-04-29 05:27:00.504589 [ docbroker_005 ] ERR  Unexpected response to WOPI::PutFile : 500Cannot save file to WOPI storage uri [https://owncloud.riotcat.org/index.php/apps/richdocuments/wopi/files/162686_ocmnh2pks8dp/contents?access_token=D
pi8lkhtR4zhSL2adiVLky8uAI0bBVAc&access_token_ttl=0]. Error: | wsd/Storage.cpp:1112ESC[0m
ESC[1mESC[31mwsd-00008-00058 2020-04-29 05:27:00.504806 [ docbroker_005 ] ERR  Failed to save docKey [/index.php/apps/richdocuments/wopi/files/162686_ocmnh2pks8dp] to URI [https://owncloud.riotcat.org/index.php/apps/richdocuments/wopi/files/162686_ocmnh2pks8dp?access_tok
en=Dpi8lkhtR4zhSL2adiVLky8uAI0bBVAc&access_token_ttl=0]. Notifying client.| wsd/DocumentBroker.cpp:1083ESC[0m
ESC[1mESC[31mwsd-00008-00058 2020-04-29 05:27:06.599689 [ docbroker_005 ] ERR  Unexpected response to WOPI::PutFile : 500Cannot save file to WOPI storage uri [https://owncloud.riotcat.org/index.php/apps/richdocuments/wopi/files/162686_ocmnh2pks8dp/contents?access_token=D
pi8lkhtR4zhSL2adiVLky8uAI0bBVAc&access_token_ttl=0]. Error: | wsd/Storage.cpp:1112ESC[0m
ESC[1mESC[31mwsd-00008-00058 2020-04-29 05:27:06.600029 [ docbroker_005 ] ERR  Failed to save docKey [/index.php/apps/richdocuments/wopi/files/162686_ocmnh2pks8dp] to URI [https://owncloud.riotcat.org/index.php/apps/richdocuments/wopi/files/162686_ocmnh2pks8dp?access_tok
en=Dpi8lkhtR4zhSL2adiVLky8uAI0bBVAc&access_token_ttl=0]. Notifying client.| wsd/DocumentBroker.cpp:1083ESC[0m
```

</details>

#### Nextcloud log (data/nextcloud.log)

<details>
<summary>Nextcloud log</summary>

```
[PHP] Error: fread(): Length parameter must be greater than 0 at /var/www/nextcloud/apps/files_external/3rdparty/icewind/streams/src/Wrapper.php#91

GET /apps/files_versions/preview?file=%2FDocuments%2FFinanzplan.ods&version=1527418571
from 46.142.20.167 by jonny at 2020-04-29T05:36:06+00:00

[richdocuments] Error: OCA\Encryption\Exceptions\PrivateKeyMissingException: Private Key missing for user: please try to log-out and log-in again at <<closure>>

 0. /var/www/nextcloud/apps/encryption/lib/KeyManager.php line 444
    OCA\Encryption\Session->getPrivateKey()
 1. /var/www/nextcloud/apps/encryption/lib/Crypto/Encryption.php line 202
    OCA\Encryption\KeyManager->getFileKey("/jonny/files/Documents/Finanzplan.ods", "jonny")
 2. /var/www/nextcloud/lib/private/Files/Stream/Encryption.php line 269
    OCA\Encryption\Crypto\Encryption->begin("/jonny/files/Documents/Finanzplan.ods", "jonny", "w", {oc_encryption_m ... "}, {users: ["jonny"],public: true})
 3. <<closure>>
    OC\Files\Stream\Encryption->stream_open("ocencryption://", "w", 0, null)
 4. /var/www/nextcloud/lib/private/Files/Stream/Encryption.php line 207
    fopen("ocencryption://", "w", false, null)
 5. /var/www/nextcloud/lib/private/Files/Stream/Encryption.php line 187
    OC\Files\Stream\Encryption::wrapSource(null, null, "ocencryption", "OC\\Files\\Stream\\Encryption", "w")
 6. /var/www/nextcloud/lib/private/Files/Storage/Wrapper/Encryption.php line 469
    OC\Files\Stream\Encryption::wrap(null, "files/Documents/Finanzplan.ods", "/jonny/files/Documents/Finanzplan.ods", {oc_encryption_m ... "}, "jonny", OCA\Encryption\Crypto\Encryption {}, OC\Files\Storage ... l}, OC\Files\Storage ... l}, OC\Encryption\Util {}, OC\Encryption\File {}, "w", 0, 20552, 0, true)
 7. /var/www/nextcloud/lib/private/Files/Storage/Wrapper/Wrapper.php line 299
    OC\Files\Storage\Wrapper\Encryption->fopen("files/Documents/Finanzplan.ods", "w")
 8. /var/www/nextcloud/lib/private/Files/View.php line 670
    OC\Files\Storage\Wrapper\Wrapper->fopen("files/Documents/Finanzplan.ods", "w")
 9. /var/www/nextcloud/lib/private/Files/Node/File.php line 71
    OC\Files\View->file_put_contents("/jonny/files/Documents/Finanzplan.ods", null)
10. /var/www/nextcloud/apps/richdocuments/lib/Controller/WopiController.php line 454
    OC\Files\Node\File->putContent(null)
11. /var/www/nextcloud/apps/richdocuments/lib/Controller/WopiController.php line 627
    OCA\Richdocuments\Controller\WopiController->OCA\Richdocuments\Controller\{closure}("*** sensitive parameters replaced ***")
12. /var/www/nextcloud/apps/richdocuments/lib/Controller/WopiController.php line 455
    OCA\Richdocuments\Controller\WopiController->retryOperation(Closure {})
13. /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 170
    OCA\Richdocuments\Controller\WopiController->putFile("27970", "P9Lq4EIpJwM8RFHpi4fYaDLErMmdeYwt")
14. /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 99
    OC\AppFramework\Http\Dispatcher->executeController(OCA\Richdocument ... {}, "putFile")
15. /var/www/nextcloud/lib/private/AppFramework/App.php line 125
    OC\AppFramework\Http\Dispatcher->dispatch(OCA\Richdocument ... {}, "putFile")
16. /var/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php line 47
    OC\AppFramework\App::main("OCA\\Richdocume ... r", "putFile", OC\AppFramework\ ... {}, {fileId: "27970_ ... "})
17. <<closure>>
    OC\AppFramework\Routing\RouteActionHandler->__invoke({fileId: "27970_ ... "})
18. /var/www/nextcloud/lib/private/Route/Router.php line 299
    call_user_func(OC\AppFramework\ ... {}, {fileId: "27970_ ... "})
19. /var/www/nextcloud/lib/base.php line 1008
    OC\Route\Router->match("/apps/richdocum ... s")
20. /var/www/nextcloud/index.php line 38
    OC::handleRequest()

POST /index.php/apps/richdocuments/wopi/files/27970_ocmnh2pks8dp/contents?access_token=P9Lq4EIpJwM8RFHpi4fYaDLErMmdeYwt&access_token_ttl=0
from 172.17.0.6 by jonny at 2020-04-29T05:36:02+00:00
```

</details>

**Comment by jimbolaya** [comment] 2020-06-01 19:52
I'm disappointed this is marked "stale because it has not had recent activity" and marked wontfix. 

Are there any indications that this is an issue that needs to be solved on the Nextcloud side? Are there resources that will allow us to troubleshoot this?

I'm stuck with 3.5.0 since I have the same issue with 3.6.0 (as well as 3.5.3).

**Comment by JonnyTischbein** [comment] 2020-06-02 16:07
Thanks your post! I currently didn't get it running, but I haven't tested 3.5.0.

I'm disappointed too! I do not even unterstand what is excatly the error..

**Comment by JonnyTischbein** [comment] 2020-06-02 16:12
Today (June 2, 2020, 11:52 a.m.) Version 3.7.0 was released. But didn't fix my issue

**Comment by juliushaertl** [comment] 2020-06-25 07:03
duplicate of https://github.com/nextcloud/richdocuments/issues/833

**Closed by juliushaertl** 2020-06-25 07:03 UTC
