### ISSUE TITLE
After last update to 3.7.2. in NC 18.0.6 - no editing possible for not logged in users

### ISSUE THREAD

**Issue by skillz-xx** [nextcloud/richdocuments#1058] opened 2020-06-24 20:32 UTC
**Describe the bug**
a document is shared with option to edit for a user outside of nextcloud
user opens url and gets a "Not Found
The requested URL was not found on this server."

happens since update to 3.7.2. from last version, running NC 18.0.6

**Comment by juliushaertl** [comment] 2020-06-25 06:57
I cannot reproduce, please fill out the full issue template. 

> Not Found. The requested URL was not found on this server.

This usually indicates that the share link is not valid

**Comment by juliushaertl** [comment] 2020-06-25 14:52
Fixed with #1061

**Closed by juliushaertl** 2020-06-25 14:52 UTC
Labels: info needed

**Comment by skillz-xx** [comment] 2020-06-25 14:58
ok super, when will this be available as an update for the plugin in nextcloud?
