### ISSUE TITLE
Nexctloud 19.0.5: high TTFB and slow Nextcloud Server 

### ISSUE THREAD

**Issue by n0r** [nextcloud/richdocuments#1267] opened 2020-11-23 11:28 UTC
**Describe the bug**
When the plugin is activated i get extremly slow Nextcloud Speeds/responses from the server. TTFBs from 2–4 minutes.
I was researching for the problem yesterday after installing an update and tried several things, so these can not be the reason:
-Re-installed php7.4-fpm and made config regarding to Nextcloud documentation
-Checked MariaDB
-Checked Server resources (all fine)
-Checked nginx config

After running out of ideas i started deactivating plugins.
When deactivating Collabora Online, my nextcloud was speedy again as before. To validate, that the reason is this plugin, i re-enabled it -> Nextcloud was slow again.

**To Reproduce**
Activate the plugin

**Expected behavior**
Nextcloud not to slow down.

**Client details:**
 - OS: MacOS BigSur 11.0.1, but issue is present on all clients
 - Browser newest Chrome
 - Device: MacBook 2018

## Server details

**Operating system**:
Ubuntu Server 18.04.5 LTS

**Web server:**
Nginx 1.14.0

**Database:**
10.1.47-MariaDB

**PHP version:**
php7.4-fpm

**Nextcloud version:**
19.0.5

**Version of the richdocuments app**
-

**Version of Collabora Online**
3.7.9. no Update available atm

#### Nextcloud log (data/nextcloud.log)
```
Nothing in logs
```

#### Browser log
```
Nothing special here.
Only thing is ttfb for files/ which are about 2–4 minutes
```

</details>

**Comment by juliushaertl** [comment] 2020-11-23 12:22
Are you using a full Collabora Online server or the built-in one? Also do you have memory caching (apcu or redis) enabled on your server?

**Comment by n0rsworld** [comment] 2020-11-23 12:48
Both, but problem occurs when activating first one:
<img width="1383" alt="Screenshot 2020-11-23 at 13 46 51" src="https://user-images.githubusercontent.com/57767438/99963691-6d782e80-2d92-11eb-8f26-f0dba7f2a2e1.png">

I have Redis enabled, but temporarily disabled it yesterday for researching. Sorry didn't mention it.

**Comment by babolivier** [comment] 2020-12-03 15:13
I've also been experiencing extreme slowness, both when running my own full Collabora Online server, and the built-in one (I recently switched to the latter, with no improvement in terms of performance). Disabling the Collabora Online extension (not the Built-in CODE Server one) seems to make my Nextcloud much faster. FWIW I'm using Zend OPCache and APCu for memory caching and Redis to cache file locks.

**Comment by b3nis** [comment] 2020-12-05 21:32
I am so glad that I found this bug report. 
I have the exact same thing and couldn't find the root cause for hours.

I also noticed that Collabora is creating a zombie process.

OS: Ubuntu 20.04.1 Server
NC: 19.0.5
Environment: Docker (with nginx, letsencryptit and MariaDB)

**Comment by XXDoMi77** [comment] 2020-12-06 14:03
Same issue on Raspberry Pi 4 8GB with Ubuntu Server 20.04.1 LTS aarch64, the server works fine from the app store, but the client slows down the entirety of Nextcloud. It slows down to a point, where nginx just throws an error when you try to access the site, when the Collabore Online app is enabled...

OS: Ubuntu Server 20.04.1 LTS aarch64
NC: 20.0.2
Web server: nginx
PHP: php7.4.3-fpm
Cache: Redis

**Comment by XXDoMi77** [comment] 2020-12-11 14:19
@juliushaertl @babolivier @b3nis @n0r

It seems to be fixed in 20.0.3

**Comment by b3nis** [comment] 2020-12-11 14:31
> @juliushaertl @babolivier @b3nis @n0r
> 
> It seems to be fixed in 20.0.3

Would prefer to stay on 19 for a while. Did you try 19.0.6 or just went straight to 20.0.3?

**Comment by XXDoMi77** [comment] 2020-12-11 14:34
@b3nis 

I tried an older version from the app store and that worked. I was on 20.0.2 though, so your experience might be different, but you could give it a try...

**Comment by b3nis** [comment] 2020-12-11 21:30
I tried both 19.0.6 and 20.0.3 and same issue with latest version of Collabora CODE. Will try to install an earlier version of Collabora CODE.

**Comment by avimanyu786** [comment] 2020-12-24 09:00
Same on 20.0.2, 20.0.3 and 20.0.4

https://github.com/nextcloud/richdocuments/issues/1282

**Comment by juliushaertl** [comment] 2021-01-08 15:24
Closing as a duplicate of https://github.com/nextcloud/richdocuments/issues/1282 since most people are assinged over there, please follow the other issue.

**Closed by juliushaertl** 2021-01-08 15:24 UTC
