### ISSUE TITLE
fails to open document, "WOPI::CheckFileInfo failed: | wsd/DocumentBroker.cpp:2332", "ERR Storage error while starting session"

### ISSUE THREAD

**Issue by vasyugan** [nextcloud/richdocuments#2954] opened 2023-05-14 14:44 UTC
**Describe the bug**

I experience this problem with one of my nextcloud instances, running on a synology diskstation. It occurs only when I use natively installed coolwsd. It does NOT occur with collabora running in docker. It also does not affect my other Nextcloud instances on other servers, using the same instance of collbora. They all work fine with both the native and the dockerized version. However, one instance stubbornly refused to cooperate withe native version while working fine with the dockerized version.

I have reported the same issue to collabora. I don't know on which side this has to be fixed, see https://github.com/CollaboraOnline/online/issues/5855

**To Reproduce**

Install Collabora on Ubuntu 22.04 LTS using the native debian packages for this distro
Shut down the collabora docker instance, edit /etc/coolwsd.xml to accept connections from the same Nextcloud instances that used the dockerized version.
On the target Nextcloud instance try to open a document in "Nextcloud office"
See error "Document cannot be opened, please try again later"

**Expected behavior**
Should open the document, just as the dockerized version did.
 

**Client details:**
 - OS: Windows / GNU/Linux 
 - Browser Firefox
 - Version 110
 - Device: desktop

## Server details

Nextcloud running on Synology Workstation  DS918+, Collabora server running on amd64 server Ubuntu 22.04 

**Operating system**:

Nextcloud: DSM 7.1.1-42962 Update 3, Collabora: Ubuntu 22.04

**Web server:**

Apache

**Database:**

Mariadb

**PHP version:** 8.0

**Nextcloud version:** 26.0.1

**Version of the richdocuments app** 8.0.1

**Version of Collabora Online**  22.05.14.3-1

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
{"reqId":"9vK0NoI2YZY3Z4VdFKga","level":3,"time":"2023-05-14T14:53:35+00:00","remoteAddr":"93.224.53.193","user":"jr","app":"PHP","method":"GET","url":"/index.php/core/preview?fileId=10789&c=292b8fbc4b2c845aaac9e3f592b8d25b&x=250&y=250&forceIcon=0&a=1","message":"is_file(): open_basedir restriction in effect. File(/proc/cpuinfo) is not within the allowed path(s): (/volume1/web/nextcloud:/tmp:/var/services/tmp:/var/services/web:/volume1/NextcloudData) at /volume1/web/nextcloud/lib/private/Preview/Generator.php#351","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/110.0","version":"26.0.1.1","data":{"app":"PHP"}}


```

  
```
Feb 07 12:08:23 ****.*****.*** coolwsd[3158473]: wsd-3158473-3261494 2023-02-07 12:08:23.997352 +0100 [ docbroker_022 ] ERR  #35: Read failed, have 0 buffered bytes (EPIPE: Broken pipe)| net/Socket.hpp:1135
Feb 07 12:08:23 ****.*****.*** coolwsd[3158473]: wsd-3158473-3261494 2023-02-07 12:08:23.997424 +0100 [ docbroker_022 ] ERR  #35: Socket write returned -1 (EPIPE: Broken pipe)| net/Socket.hpp:1436
Feb 07 12:08:23 ****.*****.*** coolwsd[3158473]: wsd-3158473-3261494 2023-02-07 12:08:23.997444 +0100 [ docbroker_022 ] ERR  #35: Socket write returned -1 (EPIPE: Broken pipe)| net/Socket.hpp:1436
Feb 07 12:08:23 ****.*****.*** coolwsd[3158473]: wsd-3158473-3261494 2023-02-07 12:08:23.997498 +0100 [ docbroker_022 ] ERR  WOPI::CheckFileInfo failed for URI [https://*****.diskstation.me:4433/index.php/apps/richdocuments/wopi/files/12094_oclsffxzupxe?access_token=QBlTGZtR19qXO4UMeeFh98gH4yB25jKK&access_token_ttl=1675804102000]: 0 . Headers:         Body: []| wsd/Storage.cpp:689
Feb 07 12:08:23 ****.*****.*** coolwsd[3158473]: wsd-3158473-3261494 2023-02-07 12:08:23.997544 +0100 [ docbroker_022 ] ERR  loading document exception: WOPI::CheckFileInfo failed: | wsd/DocumentBroker.cpp:2370
Feb 07 12:08:23 ****.*****.*** coolwsd[3158473]: wsd-3158473-3261494 2023-02-07 12:08:23.997566 +0100 [ docbroker_022 ] ERR  Failed to add session to [https://*****.diskstation.me:4433/index.php/apps/richdocuments/wopi/files/12094_oclsffxzupxe] with URI [https://*****.diskstation.me:4433/index.php/apps/richdocuments/wopi/files/12094_oclsffxzupxe?access_token=QBlTGZtR19qXO4UMeeFh98gH4yB25jKK&access_token_ttl=1675804102000]: WOPI::CheckFileInfo failed: | wsd/DocumentBroker.cpp:2332
Feb 07 12:08:23 ****.*****.*** coolwsd[3158473]: wsd-3158473-3261494 2023-02-07 12:08:23.997591 +0100 [ docbroker_022 ] ERR  Storage error while starting session on https://*****.diskstation.me:4433/index.php/apps/richdocuments/wopi/files/12094_oclsffxzupxe for socket #29. Terminating connection. Error: WOPI::CheckFileInfo failed: | wsd/COOLWSD.cpp:4856
Feb 07 12:08:24 ****.*****.*** coolwsd[3158473]: wsd-3158473-3261494 2023-02-07 12:08:24.005434 +0100 [ docbroker_022 ] ERR  #28: Read failed, have 0 buffered bytes (ECONNRESET: Connection reset by peer)| net/Socket.hpp:1135
Feb 07 12:08:24 ****.*****.*** coolwsd[3158473]: wsd-3158473-3261494 2023-02-07 12:08:24.005478 +0100 [ docbroker_022 ] WRN  Unassociated Kit (3259405) disconnected unexpectedly| wsd/COOLWSD.cpp:3395
Feb 07 12:08:24 ****.*****.*** coolwsd[3158473]: wsd-3158473-3261531 2023-02-07 12:08:24.586365 +0100 [ docbroker_023 ] ERR  #33: Read failed, have 0 buffered bytes (EPIPE: Broken pipe)| net/Socket.hpp:1135
Feb 07 12:08:24 ****.*****.*** coolwsd[3158473]: wsd-3158473-3261531 2023-02-07 12:08:24.586441 +0100 [ docbroker_023 ] ERR  #33: Socket write returned -1 (EPIPE: Broken pipe)| net/Socket.hpp:1436
Feb 07 12:08:24 ****.*****.*** coolwsd[3158473]: wsd-3158473-3261531 2023-02-07 12:08:24.586458 +0100 [ docbroker_023 ] ERR  #33: Socket write returned -1 (EPIPE: Broken pipe)| net/Socket.hpp:1436
Feb 07 12:08:24 ****.*****.*** coolwsd[3158473]: wsd-3158473-3261531 2023-02-07 12:08:24.586509 +0100 [ docbroker_023 ] ERR  WOPI::CheckFileInfo failed for URI [https://*****.diskstation.me:4433/index.php/apps/richdocuments/wopi/files/12094_oclsffxzupxe?access_token=QBlTGZtR19qXO4UMeeFh98gH4yB25jKK&access_token_ttl=1675804102000&permission=edit]: 0 . Headers:         Body: []| wsd/Storage.cpp:689
Feb 07 12:08:24 ****.*****.*** coolwsd[3158473]: wsd-3158473-3261531 2023-02-07 12:08:24.586551 +0100 [ docbroker_023 ] ERR  loading document exception: WOPI::CheckFileInfo failed: | wsd/DocumentBroker.cpp:2370
Feb 07 12:08:24 ****.*****.*** coolwsd[3158473]: wsd-3158473-3261531 2023-02-07 12:08:24.586566 +0100 [ docbroker_023 ] ERR  Failed to add session to [https://*****.diskstation.me:4433/index.php/apps/richdocuments/wopi/files/12094_oclsffxzupxe] with URI [https://*****.diskstation.me:4433/index.php/apps/richdocuments/wopi/files/12094_oclsffxzupxe?access_token=QBlTGZtR19qXO4UMeeFh98gH4yB25jKK&access_token_ttl=1675804102000&permission=edit]: WOPI::CheckFileInfo failed: | wsd/DocumentBroker.cpp:2332
Feb 07 12:08:24 ****.*****.*** coolwsd[3158473]: wsd-3158473-3261531 2023-02-07 12:08:24.586594 +0100 [ docbroker_023 ] ERR  Storage error while starting session on https://*****.diskstation.me:4433/index.php/apps/richdocuments/wopi/files/12094_oclsffxzupxe for socket #28. Terminating connection. Error: WOPI::CheckFileInfo failed: | wsd/COOLWSD.cpp:4856
Feb 07 12:08:24 ****.*****.*** coolwsd[3158473]: wsd-3158473-3261531 2023-02-07 12:08:24.592599 +0100 [ docbroker_023 ] ERR  #36: Read failed, have 0 buffered bytes (ECONNRESET: Connection reset by peer)| net/Socket.hpp:1135
Feb 07 12:08:24 ****.*****.*** coolwsd[3158473]: wsd-3158473-3261531 2023-02-07 12:08:24.592643 +0100 [ docbroker_023 ] WRN  Unassociated Kit (3261496) disconnected unexpectedly| wsd/COOLWSD.cpp:3395
Feb 07 12:08:25 ****.*****.*** coolwsd[3158473]: wsd-3158473-3261550 2023-02-07 12:08:25.088910 +0100 [ docbroker_024 ] ERR  #35: Read failed, have 0 buffered bytes (EPIPE: Broken pipe)| net/Socket.hpp:1135
Feb 07 12:08:25 ****.*****.*** coolwsd[3158473]: wsd-3158473-3261550 2023-02-07 12:08:25.088993 +0100 [ docbroker_024 ] ERR  #35: Socket write returned -1 (EPIPE: Broken pipe)| net/Socket.hpp:1436
Feb 07 12:08:25 ****.*****.*** coolwsd[3158473]: wsd-3158473-3261550 2023-02-07 12:08:25.089021 +0100 [ docbroker_024 ] ERR  #35: Socket write returned -1 (EPIPE: Broken pipe)| net/Socket.hpp:1436
Feb 07 12:08:25 ****.*****.*** coolwsd[3158473]: wsd-3158473-3261550 2023-02-07 12:08:25.089091 +0100 [ docbroker_024 ] ERR  WOPI::CheckFileInfo failed for URI [https://*****.diskstation.me:4433/index.php/apps/richdocuments/wopi/files/12094_oclsffxzupxe?access_token=QBlTGZtR19qXO4UMeeFh98gH4yB25jKK&access_token_ttl=1675804102000&permission=edit]: 0 . Headers:         Body: []| wsd/Storage.cpp:689
Feb 07 12:08:25 ****.*****.*** coolwsd[3158473]: wsd-3158473-3261550 2023-02-07 12:08:25.089148 +0100 [ docbroker_024 ] ERR  loading document exception: WOPI::CheckFileInfo failed: | wsd/DocumentBroker.cpp:2370
Feb 07 12:08:25 ****.*****.*** coolwsd[3158473]: wsd-3158473-3261550 2023-02-07 12:08:25.089174 +0100 [ docbroker_024 ] ERR  Failed to add session to [https://*****.diskstation.me:4433/index.php/apps/richdocuments/wopi/files/12094_oclsffxzupxe] with URI [https://*****.diskstation.me:4433/index.php/apps/richdocuments/wopi/files/12094_oclsffxzupxe?access_token=QBlTGZtR19qXO4UMeeFh98gH4yB25jKK&access_token_ttl=1675804102000&permission=edit]: WOPI::CheckFileInfo failed: | wsd/DocumentBroker.cpp:2332
Feb 07 12:08:25 ****.*****.*** coolwsd[3158473]: wsd-3158473-3261550 2023-02-07 12:08:25.089208 +0100 [ docbroker_024 ] ERR  Storage error while starting session on https://*****.diskstation.me:4433/index.php/apps/richdocuments/wopi/files/12094_oclsffxzupxe for socket #29. Terminating connection. Error: WOPI::CheckFileInfo failed: | wsd/COOLWSD.cpp:4856
Feb 07 12:08:25 ****.*****.*** coolwsd[3158473]: wsd-3158473-3261550 2023-02-07 12:08:25.098836 +0100 [ docbroker_024 ] ERR  #28: Read failed, have 0 buffered bytes (ECONNRESET: Connection reset by peer)| net/Socket.hpp:1135
Feb 07 12:08:25 ****.*****.*** coolwsd[3158473]: wsd-3158473-3261550 2023-02-07 12:08:25.098886 +0100 [ docbroker_024 ] WRN  Unassociated Kit (3261538) disconnected unexpectedly| wsd/COOLWSD.cpp:3395
```

</details>

**Comment by FamousL** [comment] 2023-05-16 15:19
this looks like https://github.com/nextcloud/richdocuments/issues/2906

**Comment by joshtrichards** [comment] 2023-11-09 22:10
Duplicate of #2906 

Please check/follow that issue for details.

**Closed by joshtrichards** 2023-11-09 22:10 UTC

**Comment by vasyugan** [comment] 2024-01-04 14:47
In my case, it was strangely related to the dyndns service offered by synology. Now, the instance is running under a domain name offered by FreeDNS.Afraid.org and everything is fine. I would be lying if I said I understand the reason, but that's how it is.
