### ISSUE TITLE
Sheet tabs are not showing up on smartphone

### ISSUE THREAD

**Issue by Bables55** [nextcloud/richdocuments#2647] opened 2022-11-28 00:21 UTC
**Describe the bug**
When users opens spreadsheet document on smartphones, the sheet tabs do not appear and cannot be switched.
On some devices, the edit mode (+) button is also hidden.

I learned that it was caused by the Nextcloud Office app side.
_Originally posted by @thebearon in https://github.com/CollaboraOnline/online/issues/5446#issuecomment-1316334114_

I try with an app called WOPI and the sheet appears fine.
Sheets are not displayed in the Nextcloud Office app.

**To Reproduce**
1. Open the spreadsheet document containing sheets by any(Android/iPhone) smartphones.

**Expected behavior**
Sheets are displayed and the user can switch between sheets.

**Client details:**
 - OS: Android / iOS
 - Device: any Androids, iPhones

## Server details

**Operating system**:
CentOS 7.9
**Web server:**
Nginx
**Database:**
MariaDB 10.5.22
**PHP version:**
8.1.12
**Nextcloud version:**
24.0.7
**Version of the richdocuments app**
6.3.1
**Version of Collabora Online**
22.05.8.4

**Comment by joshtrichards** [comment] 2023-11-08 20:08
Hi @Bables55 - Thanks for reporting this. I'm unable to reproduce this behavior today. Are you still experiencing it?

**Comment by joshtrichards** [comment] 2024-07-26 21:16
Closing due to no further response after >6 months.

**Closed by joshtrichards** 2024-07-26 21:16 UTC
Labels: bug, needs info
