### ISSUE TITLE
Cannot save edits in documents which are created from global template

### ISSUE THREAD

**Issue by gjongenelen** [nextcloud/richdocuments#1890] opened 2021-12-01 15:09 UTC
Cannot save edits in documents which are created from global template

**Steps to reproduce**
1. Add a spreadsheet in global templates (/index.php/settings/admin/richdocuments)
2. Go to "Files"
3. Create new spreadsheet and select the global template
4. Make an edit and click "save"
5. Nothing happens

**Expected behavior**
The document is saved and the red dot-icon on the save-icon disappears. 

**Client details:**
 - OS: MacOS / Windows
 - Browser: Safari / Chrome

## Server details

**Operating system**: Ubuntu 20.04

**Web server:** Apache 2.4.41

**Database:** MySQL 8.0.27

**PHP version:** 7.4

**Nextcloud version:** 22.2.3

**Version of the richdocuments app** 4.2.3

**Version of Collabora Online** 21.06.8.1 (COOLWSD 21.11.0.3)

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
Nothing show up in logs (not even with loglevel => 0)
```

#### Websocket log
```
unocommandresult: { "commandName": ".uno:Save", "success": false, "result": { "type": "void"}}	1638370737.3898091
```

</details>

**Comment by joergmschulz** [comment] 2021-12-02 09:19
This is a duplicate of #1563

**Closed** 2021-12-02 17:08 UTC
